import { t } from './i18n.js';
/* ===========================================================
   Tagda Timer — 2x2 algorithm library: alternates per case.

   GENERATED by tools/gen-222.mjs. Do not hand-edit.

   Lazy-loaded by js/alglibrary.js, never on the timer's boot path.

   Every alternate is a shortest — or one-move-from-shortest —
   solution of its case in <R, U, F>, listed with the R/U-only ones
   first because those are the ones that execute without a regrip.
   =========================================================== */

import { OLL_222, PBL_222, CLL_222, EG1_222, EG2_222 } from './algs2.js';

const OLL_LIBRARY = {
  "222OLL-Sune": { alternates: [
    { alg: "F' R F2 U2 R F'", moveCount: 6 },
    { alg: "R' U2 R U R' U R", moveCount: 7 },
    { alg: "U R' U F2 R2 U F'", moveCount: 7 },
    { alg: "U' R' F U2 R2 F R'", moveCount: 7 },
  ] },
  "222OLL-Antisune": { alternates: [
    { alg: "R F' R2 U2 F' R", moveCount: 6 },
    { alg: "R' F R F' R U R'", moveCount: 7 },
    { alg: "R' F' R U' R' F2 R", moveCount: 7 },
  ] },
  "222OLL-T": { alternates: [
    { alg: "R U R' U' F' U' F", moveCount: 7 },
    { alg: "R U2 F R F' U2 R'", moveCount: 7 },
    { alg: "F' U F U2 R U2 R'", moveCount: 7 },
    { alg: "R' F' R U F U F'", moveCount: 7 },
  ] },
  "222OLL-U": { alternates: [
    { alg: "R U F R' F' R'", moveCount: 6 },
    { alg: "R' F' U' F U R", moveCount: 6 },
    { alg: "R U2 R U2 R U R2", moveCount: 7 },
  ] },
  "222OLL-L": { alternates: [
    { alg: "F R' F' U' R' U R", moveCount: 7 },
    { alg: "F R2 U R' U' R2 F'", moveCount: 7 },
    { alg: "F R2 F' U2 R' U' R", moveCount: 7 },
    { alg: "R' F R U F U' F'", moveCount: 7 },
  ] },
  "222OLL-Pi": { alternates: [
    { alg: "F R F2 U' F2 R F'", moveCount: 7 },
    { alg: "F R' F2 U F2 R' F'", moveCount: 7 },
    { alg: "F' U F2 R' F2 U F", moveCount: 7 },
    { alg: "F' U' F2 R F2 U' F", moveCount: 7 },
  ] },
  "222OLL-H": { alternates: [
    { alg: "F2 U2 F U2 F2", moveCount: 5 },
    { alg: "F2 U2 F' U2 F2", moveCount: 5 },
    { alg: "U R2 U2 R U2 R2", moveCount: 6 },
    { alg: "U R2 U2 R' U2 R2", moveCount: 6 },
  ] },
};

const PBL_LIBRARY = {
  "222PBL-solved-adjacent-swap-1": { alternates: [
    { alg: "R2 F2 R' U' R F2 R' U R'", moveCount: 9 },
    { alg: "F' U F' R2 F U' F' R2 F2", moveCount: 9 },
    { alg: "R2 U R' F' U' F U' R' U2 R'", moveCount: 10 },
    { alg: "R2 U R2 U' F2 U R2 U' F2 R2", moveCount: 10 },
  ] },
  "222PBL-solved-diagonal-swap-2": { alternates: [
    { alg: "R2 U' R U F R2 F U' R' U F'", moveCount: 11 },
    { alg: "R2 U' R F' R' U R2 U F U F'", moveCount: 11 },
    { alg: "R' U R2 U F U F' R2 U' R F'", moveCount: 11 },
    { alg: "F R' U R2 F U' F' U' R2 U' R", moveCount: 11 },
  ] },
  "222PBL-adjacent-swap-solved-3": { alternates: [
    { alg: "R' U F' R2 F R' F' R2 F2", moveCount: 9 },
    { alg: "F2 R2 F' U' R F2 R' F R'", moveCount: 9 },
    { alg: "R' U2 R' F' R U' F' R' U F2", moveCount: 10 },
    { alg: "F2 U R' U' R' F U' R' F2 R'", moveCount: 10 },
  ] },
  "222PBL-adjacent-swap-adjacent-swap-4": { alternates: [
    { alg: "R2 U F2 U2 R2 U R2", moveCount: 7 },
    { alg: "R2 U' R2 U2 F2 U' R2", moveCount: 7 },
    { alg: "R2 U R2 U2 R2 F2 U' R2", moveCount: 8 },
    { alg: "R2 U F2 R2 U2 R2 U' R2", moveCount: 8 },
  ] },
  "222PBL-adjacent-swap-diagonal-swap-5": { alternates: [
    { alg: "R' F U' R2 U F' R", moveCount: 7 },
    { alg: "R U' F U2 F' U R' U2", moveCount: 8 },
    { alg: "U2 R U' F U2 F' U R'", moveCount: 8 },
  ] },
  "222PBL-diagonal-swap-solved-6": { alternates: [
    { alg: "R U' R U R' F2 R' U' R' U F2", moveCount: 11 },
    { alg: "F2 U' R U R F2 R U' R' U R'", moveCount: 11 },
    { alg: "R U' F' R' U2 R' U F R' U F2", moveCount: 11 },
    { alg: "R F' R' U' R2 U' R U F' U F2", moveCount: 11 },
  ] },
  "222PBL-diagonal-swap-adjacent-swap-7": { alternates: [
    { alg: "R U' R F2 R' U R'", moveCount: 7 },
    { alg: "R' F R' F2 R U' R U2", moveCount: 8 },
    { alg: "U2 R' U R' F2 R F' R", moveCount: 8 },
  ] },
  "222PBL-diagonal-swap-diagonal-swap-8": { alternates: [
    { alg: "R2 F2 R2", moveCount: 3 },
    { alg: "F2 R2 F2", moveCount: 3 },
  ] },
};

const CLL_LIBRARY = {
  "CLL-Sune-1": { alternates: [
    { alg: "F R F2 R' U2 R F", moveCount: 7 },
    { alg: "R' U2 R U R' U R U'", moveCount: 8 },
    { alg: "U' R F U' F R F2 R'", moveCount: 8 },
    { alg: "U' F' R2 F R U' R F", moveCount: 8 },
  ] },
  "CLL-Sune-2": { alternates: [
    { alg: "R F' U' F R' U' R", moveCount: 7 },
  ] },
  "CLL-Sune-3": { alternates: [
    { alg: "R U' R' F U2 F U2 F'", moveCount: 8 },
  ] },
  "CLL-Sune-4": { alternates: [
    { alg: "R' U2 R U2 R F' U' F", moveCount: 8 },
  ] },
  "CLL-Sune-5": { alternates: [
    { alg: "R2 U' F' U2 F U' R2 U R'", moveCount: 9 },
    { alg: "R' F R2 F' R U2 R' U' R2", moveCount: 9 },
    { alg: "R' F R2 F' U' R' U' R2 U R'", moveCount: 10 },
    { alg: "R2 U' R F' R' U2 F U' R F", moveCount: 10 },
  ] },
  "CLL-Sune-6": { alternates: [
    { alg: "F2 R U R2 F R2 U' R' F2", moveCount: 9 },
    { alg: "F2 R U' R2 F' R2 U R' F2", moveCount: 9 },
    { alg: "F2 R' F R2 U' R2 F' R F2", moveCount: 9 },
    { alg: "F2 R' F' R2 U R2 F R F2", moveCount: 9 },
  ] },
  "CLL-Antisune-1": { alternates: [
    { alg: "R' F R F' R U R'", moveCount: 7 },
  ] },
  "CLL-Antisune-2": { alternates: [
    { alg: "R' F' R U' R' F2 R", moveCount: 7 },
    { alg: "F U2 F' U' F U' F'", moveCount: 7 },
    { alg: "R' F' R2 F U2 F' R' U'", moveCount: 8 },
    { alg: "F R F2 U F R2 U R", moveCount: 8 },
  ] },
  "CLL-Antisune-3": { alternates: [
    { alg: "F U2 F' U2 F' R U R'", moveCount: 8 },
  ] },
  "CLL-Antisune-4": { alternates: [
    { alg: "F' U F R' U2 R' U2 R", moveCount: 8 },
  ] },
  "CLL-Antisune-5": { alternates: [
    { alg: "R U' R2 U F' U2 F U R2", moveCount: 9 },
    { alg: "R2 U R U2 R' F R2 F' R", moveCount: 9 },
    { alg: "R U' R2 U R U F R2 F' R", moveCount: 10 },
    { alg: "F' R' U F' U2 R F R' U R2", moveCount: 10 },
  ] },
  "CLL-Antisune-6": { alternates: [
    { alg: "F2 R U F2 R' F2 U' R' F2", moveCount: 9 },
    { alg: "F2 R U' F2 R F2 U R' F2", moveCount: 9 },
    { alg: "F2 R' F U2 R U2 F' R F2", moveCount: 9 },
    { alg: "F2 R' F' U2 R' U2 F R F2", moveCount: 9 },
  ] },
  "CLL-T-1": { alternates: [
    { alg: "F R F' U' R' U' R", moveCount: 7 },
    { alg: "R2 U' F' U F R U' R", moveCount: 8 },
    { alg: "R' U R U2 F R2 F' U2", moveCount: 8 },
    { alg: "U2 F U2 R U R' U2 F'", moveCount: 8 },
  ] },
  "CLL-T-2": { alternates: [
    { alg: "F' R' U R U F R'", moveCount: 7 },
    { alg: "R2 U R U' F' U' F R'", moveCount: 8 },
    { alg: "U2 R U' R' U2 F' U2 F", moveCount: 8 },
    { alg: "F' U2 F R2 U R' U' R2", moveCount: 8 },
  ] },
  "CLL-T-3": { alternates: [
    { alg: "R F2 R U2 R' F2 R F2 R2", moveCount: 9 },
    { alg: "R F' R' U F' U' R U' F U'", moveCount: 10 },
    { alg: "R' U' F' U R' U F U' R F", moveCount: 10 },
    { alg: "U' F U' R' U F' R' F U' R", moveCount: 10 },
  ] },
  "CLL-T-4": { alternates: [
    { alg: "F' R U' R U' F U R2 F2", moveCount: 9 },
    { alg: "F' R2 U2 F U R' F R' F", moveCount: 9 },
    { alg: "F R' F R' U R' U' R2 F2 U2", moveCount: 10 },
    { alg: "F' R U' R U' F' R2 F2 U' R2", moveCount: 10 },
  ] },
  "CLL-T-5": { alternates: [
    { alg: "R' U' R U' F2 U R' U' F2", moveCount: 9 },
    { alg: "R U R' U F2 U' F U F2", moveCount: 9 },
    { alg: "F2 U F U' F2 U R' F R", moveCount: 9 },
    { alg: "F2 U' R' F U2 F' U F' R'", moveCount: 9 },
  ] },
  "CLL-T-6": { alternates: [
    { alg: "R F R F' U' R U2 R' U2 R2", moveCount: 10 },
    { alg: "R2 U F' U' F R U R' U2 R2", moveCount: 10 },
    { alg: "R2 U' R F R' F' U' R' U2 R2", moveCount: 10 },
    { alg: "R' U' F' U F R' U2 R' U2 R2", moveCount: 10 },
  ] },
  "CLL-U-1": { alternates: [
    { alg: "F R U R' U' F'", moveCount: 6 },
    { alg: "F' U' R' F R F", moveCount: 6 },
  ] },
  "CLL-U-2": { alternates: [
    { alg: "R2 U R' F2 R F' R' F2 R'", moveCount: 9 },
    { alg: "R2 U F' R' F2 R' F' R2 F", moveCount: 9 },
    { alg: "R2 U2 R' U' F R' F' R' U R'", moveCount: 10 },
    { alg: "R U R' F2 R' U F' U' R2 F", moveCount: 10 },
  ] },
  "CLL-U-3": { alternates: [
    { alg: "F2 R2 F R2 F' U2 F R2 F", moveCount: 9 },
    { alg: "R F U' R U F' U R' U' F'", moveCount: 10 },
    { alg: "U' R U' F U' R' U F' R' F", moveCount: 10 },
    { alg: "U' R' F U' R F R' U R F'", moveCount: 10 },
  ] },
  "CLL-U-4": { alternates: [
    { alg: "F2 U' R F R2 F R F2 R'", moveCount: 9 },
    { alg: "F2 U' F R2 F' R F R2 F", moveCount: 9 },
    { alg: "R U' R2 U R' F U2 F2 R2 F", moveCount: 10 },
    { alg: "R U' R2 U R' F' R2 F2 U2 F'", moveCount: 10 },
  ] },
  "CLL-U-5": { alternates: [
    { alg: "R U' F U' F R F2 U2 R'", moveCount: 9 },
    { alg: "R2 F2 U F R' F R' U R'", moveCount: 9 },
    { alg: "R' F U' R U' R' U2 F2 R U2", moveCount: 10 },
    { alg: "U2 R2 F2 U' R' U F' R U' R", moveCount: 10 },
  ] },
  "CLL-U-6": { alternates: [
    { alg: "R2 U2 R' F' R' U2 R' U2 R' F'", moveCount: 10 },
    { alg: "R2 U' R2 U' F' U R2 U2 R F'", moveCount: 10 },
    { alg: "R2 U' R2 U' F' U' R2 U2 R' F'", moveCount: 10 },
    { alg: "R F' R' U' F2 U' R' U2 R' F'", moveCount: 10 },
  ] },
  "CLL-L-1": { alternates: [
    { alg: "R' U R U F R' F'", moveCount: 7 },
    { alg: "R' U R' F' U' F U R2", moveCount: 8 },
    { alg: "U2 F R2 U R' U' R2 F'", moveCount: 8 },
    { alg: "U2 F R2 F' U2 R' U' R", moveCount: 8 },
  ] },
  "CLL-L-2": { alternates: [
    { alg: "R F' U' R' U' R F", moveCount: 7 },
    { alg: "R F' U F U R' U' R2", moveCount: 8 },
    { alg: "R2 U R U' R2 F' U2 F", moveCount: 8 },
    { alg: "F' U2 F U2 R U R' U2", moveCount: 8 },
  ] },
  "CLL-L-3": { alternates: [
    { alg: "R F2 R' F' R2 F' R' U F2", moveCount: 9 },
    { alg: "F' R2 F' R' F R2 F' U F2", moveCount: 9 },
    { alg: "F U2 F2 R2 F R U' R2 U R'", moveCount: 10 },
    { alg: "F' R2 F2 U2 F' R U' R2 U R'", moveCount: 10 },
  ] },
  "CLL-L-4": { alternates: [
    { alg: "R F2 R F R' F2 R U' R2", moveCount: 9 },
    { alg: "F' R2 F R F2 R F U' R2", moveCount: 9 },
    { alg: "R U' R F R F' U R U2 R2", moveCount: 10 },
    { alg: "F' R2 U F U' R F2 R U' R'", moveCount: 10 },
  ] },
  "CLL-L-5": { alternates: [
    { alg: "F U2 F' R U F2 U2 R F", moveCount: 9 },
    { alg: "F U2 F' R U' R' F2 U2 F'", moveCount: 9 },
    { alg: "F R F2 U2 F R F' U2 F", moveCount: 9 },
    { alg: "F' U2 F2 R' F' R F' U2 F", moveCount: 9 },
  ] },
  "CLL-L-6": { alternates: [
    { alg: "R2 U F' R2 F U2 F' U R2", moveCount: 9 },
    { alg: "F2 R' F' R U' R U R' U F'", moveCount: 10 },
    { alg: "F2 U' R F2 R' U2 R U' F2 U2", moveCount: 10 },
    { alg: "F' R F' U R U' F U' R' F2", moveCount: 10 },
  ] },
  "CLL-Pi-1": { alternates: [
    { alg: "R2 U2 F' U' R2 U' R2 U' F'", moveCount: 9 },
    { alg: "R2 U2 F U F2 U R2 U F", moveCount: 9 },
    { alg: "U2 F R2 U' R2 U R2 U R2 F'", moveCount: 10 },
    { alg: "U2 F U2 R2 U R2 U' R2 U' F'", moveCount: 10 },
  ] },
  "CLL-Pi-2": { alternates: [
    { alg: "F2 U R2 F' R2 F R2 U' F2", moveCount: 9 },
    { alg: "F2 U' R2 F U2 F' R2 U F2", moveCount: 9 },
    { alg: "R F2 R2 U2 F' U' R U R F2", moveCount: 10 },
    { alg: "R F2 U2 F U' R U R U2 F2", moveCount: 10 },
  ] },
  "CLL-Pi-3": { alternates: [
    { alg: "R F' U2 F U2 F R2 F' R", moveCount: 9 },
    { alg: "R' F R2 F' U2 F' U2 F R'", moveCount: 9 },
    { alg: "R F2 R2 F' U2 F R2 F2 R'", moveCount: 9 },
    { alg: "R F2 R2 F' U2 F' R2 F2 R", moveCount: 9 },
  ] },
  "CLL-Pi-4": { alternates: [
    { alg: "R U2 R' F2 U R' F2 R U F'", moveCount: 10 },
    { alg: "F' U R U2 R' U F2 R' F2 R", moveCount: 10 },
    { alg: "R U2 R' F2 U2 R U' R' U' F2 U", moveCount: 11 },
    { alg: "R U2 R' F U2 R' F R U F' U", moveCount: 11 },
  ] },
  "CLL-Pi-5": { alternates: [
    { alg: "F' U F R' U2 F2 U R' U' F2", moveCount: 10 },
    { alg: "F' U F' U2 F2 R U' R' U' F2", moveCount: 10 },
    { alg: "F U' F U2 F2 R' F R U F2", moveCount: 10 },
    { alg: "F U' F' R F2 U2 F' R U F2", moveCount: 10 },
  ] },
  "CLL-Pi-6": { alternates: [
    { alg: "R' F2 R F2 U' R U2 R' U' F", moveCount: 10 },
    { alg: "F U' R' F2 R U' F2 R U2 R'", moveCount: 10 },
    { alg: "U' F2 U R U R' U2 F2 R U2 R'", moveCount: 11 },
    { alg: "R U R U' R F' R2 F U2 R' F'", moveCount: 11 },
  ] },
  "CLL-H-1": { alternates: [
    { alg: "F2 U2 F' U2 F2", moveCount: 5 },
    { alg: "U2 F2 U2 F U2 F2", moveCount: 6 },
    { alg: "F2 U2 F U2 F2 U2", moveCount: 6 },
  ] },
  "CLL-H-2": { alternates: [
    { alg: "R2 F R2 F2 U2 F R2", moveCount: 7 },
    { alg: "R2 F' U2 F2 R2 F' R2", moveCount: 7 },
    { alg: "R2 F R2 U2 F2 U2 F' R2", moveCount: 8 },
    { alg: "R2 F U2 F2 R2 F R2 U2", moveCount: 8 },
  ] },
  "CLL-H-3": { alternates: [
    { alg: "F U R2 U R2 U F U2 R2", moveCount: 9 },
    { alg: "F' U' R2 U' F2 U' F' U2 R2", moveCount: 9 },
    { alg: "U2 F R U2 R U2 R' U2 R2 F'", moveCount: 10 },
    { alg: "U2 F U2 R' U2 R' U2 R U2 F'", moveCount: 10 },
  ] },
  "CLL-H-4": { alternates: [
    { alg: "F2 U R U R' F2 U2 F U' F", moveCount: 10 },
    { alg: "F2 U R U' F2 U2 R F' U' F", moveCount: 10 },
    { alg: "F2 U' R' F U2 F2 R' F U F'", moveCount: 10 },
    { alg: "F2 U' R' F' R F2 U2 F' U F'", moveCount: 10 },
  ] },
};

const EG1_LIBRARY = {
  "EG1-Sune-1": { alternates: [
    { alg: "F' R F2 U2 R F'", moveCount: 6 },
    { alg: "F' R U2 R' F2 U2 F", moveCount: 7 },
    { alg: "F U2 F2 R' F2 R F'", moveCount: 7 },
  ] },
  "EG1-Sune-2": { alternates: [
    { alg: "F2 U' R F' U R' F R2", moveCount: 8 },
  ] },
  "EG1-Sune-3": { alternates: [
    { alg: "F' U R2 F2 U R F2 R2", moveCount: 8 },
    { alg: "U2 F' U R' U2 R' F2 U R'", moveCount: 9 },
    { alg: "R U2 F U F' U2 R2 F' R", moveCount: 9 },
    { alg: "U' F U F2 R U2 R2 F' R", moveCount: 9 },
  ] },
  "EG1-Sune-4": { alternates: [
    { alg: "R U F2 U2 R F' U' F2", moveCount: 8 },
    { alg: "R U' R' F2 U2 F U' F2", moveCount: 8 },
    { alg: "R U F2 U F2 R' F' U R", moveCount: 9 },
    { alg: "R U' R' U2 F2 U2 F' U' F2", moveCount: 9 },
  ] },
  "EG1-Sune-5": { alternates: [
    { alg: "F U2 F U' F2 R U2 R'", moveCount: 8 },
    { alg: "U' F2 U' F U' R U' R' F2", moveCount: 9 },
    { alg: "F U2 F U F2 R' U2 F2 R'", moveCount: 9 },
  ] },
  "EG1-Sune-6": { alternates: [
    { alg: "F R2 F2 U' R' F2 R' U R'", moveCount: 9 },
    { alg: "F' U R2 F2 R F2 R' U R'", moveCount: 9 },
    { alg: "R' F R' F2 R F2 R2 U F'", moveCount: 9 },
    { alg: "R' F R' F2 R' U' F2 R2 F", moveCount: 9 },
  ] },
  "EG1-Antisune-1": { alternates: [
    { alg: "F R' U2 F2 R' F", moveCount: 6 },
    { alg: "F' U2 F2 R U2 R' F", moveCount: 7 },
    { alg: "F R' F2 R F2 U2 F'", moveCount: 7 },
  ] },
  "EG1-Antisune-2": { alternates: [
    { alg: "R2 F' R U' F R' U F2", moveCount: 8 },
  ] },
  "EG1-Antisune-3": { alternates: [
    { alg: "F U' R F2 R U2 F' R", moveCount: 8 },
    { alg: "R' U F2 U F R2 U' R2 F", moveCount: 9 },
    { alg: "R' U F2 U F' R2 U R2 F'", moveCount: 9 },
    { alg: "U' F' U' F2 R U' R2 F2 R", moveCount: 9 },
  ] },
  "EG1-Antisune-4": { alternates: [
    { alg: "F2 U F' U R' F R F2", moveCount: 8 },
    { alg: "F2 U F R' U2 F2 U' R' U'", moveCount: 9 },
    { alg: "F2 U F' U2 F2 R U R' U'", moveCount: 9 },
    { alg: "U' F' U2 F' U F2 R' F2 R", moveCount: 9 },
  ] },
  "EG1-Antisune-5": { alternates: [
    { alg: "F2 R U R' U F' U F2", moveCount: 8 },
    { alg: "R U2 R' F2 U F' U2 F' U'", moveCount: 9 },
    { alg: "U' R' F R F2 U2 F' U F2", moveCount: 9 },
    { alg: "U' R' F' U2 F2 R' F U F2", moveCount: 9 },
  ] },
  "EG1-Antisune-6": { alternates: [
    { alg: "R U' R F2 R U F2 R2 F'", moveCount: 9 },
    { alg: "R U' R F2 R' F2 R2 U' F", moveCount: 9 },
    { alg: "F U' R2 F2 R' F2 R F' R", moveCount: 9 },
    { alg: "F' R2 F2 U R F2 R F' R", moveCount: 9 },
  ] },
  "EG1-T-1": { alternates: [
    { alg: "F' R F R2 F R U2 R", moveCount: 8 },
    { alg: "F' U' F R' F2 U' R U R", moveCount: 9 },
    { alg: "U2 R2 F' U F U2 F U' R'", moveCount: 9 },
    { alg: "R F R F2 U2 F' U' F R2", moveCount: 9 },
  ] },
  "EG1-T-2": { alternates: [
    { alg: "F R' U' F2 U' R' F2 R'", moveCount: 8 },
    { alg: "R' U R2 U2 F U' R F' R2", moveCount: 9 },
    { alg: "R' U' F' U2 R2 U R F' R2", moveCount: 9 },
    { alg: "U2 R2 F R' U' R2 U' F R", moveCount: 9 },
  ] },
  "EG1-T-3": { alternates: [
    { alg: "R F U2 F' U R2 F' R", moveCount: 8 },
    { alg: "R' U' R2 U F' R2 U R' U2", moveCount: 9 },
    { alg: "F' U' F2 U R U2 R2 F' R", moveCount: 9 },
    { alg: "F' U' F2 U R' F R2 U2 R'", moveCount: 9 },
  ] },
  "EG1-T-4": { alternates: [
    { alg: "R2 F2 U' F' U2 F' R2 F'", moveCount: 8 },
    { alg: "R2 F2 U F R2 F R2 F U2", moveCount: 9 },
    { alg: "F2 U R2 F' U2 F U2 F R2", moveCount: 9 },
    { alg: "F2 U F2 R2 F U2 F' R2 F'", moveCount: 9 },
  ] },
  "EG1-T-5": { alternates: [
    { alg: "R2 F' R F R' U' R' U2 F2", moveCount: 9 },
    { alg: "R2 F2 R F2 U R2 U' R2 F", moveCount: 9 },
    { alg: "R2 F U' F' R F R U2 F2", moveCount: 9 },
    { alg: "R2 F2 R' F2 U' F2 U R2 F'", moveCount: 9 },
  ] },
  "EG1-T-6": { alternates: [
    { alg: "F R' F2 R F U2 R' F' R", moveCount: 9 },
    { alg: "U2 F' R U2 R' F' U2 R U R'", moveCount: 10 },
    { alg: "R' F U' R' F R' U R F' U2", moveCount: 10 },
    { alg: "U' F2 R F R U' R U' F' R'", moveCount: 10 },
  ] },
  "EG1-U-1": { alternates: [
    { alg: "F' U2 R U2 R' U2 F", moveCount: 7 },
    { alg: "F U2 R' F2 R U2 F'", moveCount: 7 },
    { alg: "F U2 R' U2 F2 R' U2 F", moveCount: 8 },
    { alg: "F' U2 R F2 U2 R U2 F'", moveCount: 8 },
  ] },
  "EG1-U-2": { alternates: [
    { alg: "F2 U F U2 F U2 F", moveCount: 7 },
    { alg: "F2 U' F' U2 F' U2 F' U2", moveCount: 8 },
  ] },
  "EG1-U-3": { alternates: [
    { alg: "F' R2 F' R2 F' U' F2 R2", moveCount: 8 },
    { alg: "R2 F R2 F R2 F' R2 U F2", moveCount: 9 },
    { alg: "U2 F R2 F U2 F U F2 R2", moveCount: 9 },
    { alg: "F' R2 F' R2 F R2 F2 U F2", moveCount: 9 },
  ] },
  "EG1-U-4": { alternates: [
    { alg: "F' U R U2 R' F U2 F", moveCount: 8 },
    { alg: "F2 R' F2 R U F2 U2 F", moveCount: 8 },
    { alg: "F2 R' F2 R U' F2 U2 F'", moveCount: 8 },
    { alg: "F' R' U' R2 F2 U F R F2", moveCount: 9 },
  ] },
  "EG1-U-5": { alternates: [
    { alg: "R U2 F' R U R2 U' F", moveCount: 8 },
    { alg: "R U2 F2 R' U2 R U F2", moveCount: 8 },
    { alg: "R F2 R U2 F2 R U F2", moveCount: 8 },
    { alg: "R U' R2 U' R' F' U R F", moveCount: 9 },
  ] },
  "EG1-U-6": { alternates: [
    { alg: "F2 U2 R U R F' R' F R2", moveCount: 9 },
    { alg: "F' R2 U R2 U' F2 R' F2 R2", moveCount: 9 },
    { alg: "F2 U2 R' F' R' F U F' R2", moveCount: 9 },
    { alg: "F R2 U' F2 U F2 R F2 R2", moveCount: 9 },
  ] },
  "EG1-L-1": { alternates: [
    { alg: "R' U2 R' F' R2 F' R' F", moveCount: 8 },
    { alg: "R' U' R' U F2 R F' U F", moveCount: 9 },
    { alg: "R U F' U2 F' U' F R2 U2", moveCount: 9 },
    { alg: "R2 F' U F U2 F2 R' F' R'", moveCount: 9 },
  ] },
  "EG1-L-2": { alternates: [
    { alg: "R F2 R U F2 U R F'", moveCount: 8 },
    { alg: "R2 F R' U F' U2 R2 U' R", moveCount: 9 },
    { alg: "R2 F R' U' R2 U2 F U R", moveCount: 9 },
    { alg: "R' F' U R2 U R F' R2 U2", moveCount: 9 },
  ] },
  "EG1-L-3": { alternates: [
    { alg: "F U2 F2 U R U2 R' F2", moveCount: 8 },
    { alg: "F' U2 F2 U' R U2 R' F2", moveCount: 8 },
    { alg: "F U2 F R' F2 R U F'", moveCount: 8 },
    { alg: "F2 R U F R2 U2 F' R' F'", moveCount: 9 },
  ] },
  "EG1-L-4": { alternates: [
    { alg: "F2 U R U2 F2 R U2 R", moveCount: 8 },
    { alg: "F U' R2 U F U' F2 R", moveCount: 8 },
    { alg: "F2 U R F2 R' U2 F2 R", moveCount: 8 },
    { alg: "R' U2 F R U2 R U' R2 F", moveCount: 9 },
  ] },
  "EG1-L-5": { alternates: [
    { alg: "F' R2 U2 R F2 R' U2 R2 F", moveCount: 9 },
    { alg: "R2 F R U' R U' F2 U' F2 U2", moveCount: 10 },
    { alg: "U2 F2 U F2 U R' U R' F' R2", moveCount: 10 },
    { alg: "R2 U2 R2 F R' F2 R' U2 R2 F", moveCount: 10 },
  ] },
  "EG1-L-6": { alternates: [
    { alg: "F2 R' U F' R U' R2 U' F2", moveCount: 9 },
    { alg: "F2 U' R2 U' F R' F R' F2", moveCount: 9 },
    { alg: "U' R U2 R' F R U' R2 F' R", moveCount: 10 },
    { alg: "U' R' F R2 U R' F' R U2 R'", moveCount: 10 },
  ] },
  "EG1-Pi-1": { alternates: [
    { alg: "R U R2 F' R2 U R'", moveCount: 7 },
    { alg: "R U' R2 F R2 U' R'", moveCount: 7 },
    { alg: "R' F R2 U' R2 F R", moveCount: 7 },
    { alg: "R' F' R2 U R2 F' R", moveCount: 7 },
  ] },
  "EG1-Pi-2": { alternates: [
    { alg: "F R' F U' F2 R U R", moveCount: 8 },
    { alg: "F' R U' F R2 U' F' R' U2", moveCount: 9 },
    { alg: "R2 U F U F2 U2 R2 F R", moveCount: 9 },
    { alg: "R2 U F U' R2 F2 U2 F' R", moveCount: 9 },
  ] },
  "EG1-Pi-3": { alternates: [
    { alg: "F R' F R U' F U2 F", moveCount: 8 },
    { alg: "F2 U' F R' F' R U' F", moveCount: 8 },
    { alg: "R2 F2 U F' U R U' R F'", moveCount: 9 },
    { alg: "U2 F2 U F' R U R' U F'", moveCount: 9 },
  ] },
  "EG1-Pi-4": { alternates: [
    { alg: "F' R' U2 R' U2 F2 R F", moveCount: 8 },
    { alg: "F' R' F2 U2 R U2 R F", moveCount: 8 },
    { alg: "F R U2 F2 R' F2 R' F'", moveCount: 8 },
    { alg: "F R F2 R F2 U2 R' F'", moveCount: 8 },
  ] },
  "EG1-Pi-5": { alternates: [
    { alg: "R' F2 U2 R' U F2 R U R", moveCount: 9 },
    { alg: "R2 U R2 F U R2 F2 U2 R'", moveCount: 9 },
    { alg: "R2 U R2 F U' R2 F2 U2 R", moveCount: 9 },
    { alg: "R' F2 U R' F' R' U R' F'", moveCount: 9 },
  ] },
  "EG1-Pi-6": { alternates: [
    { alg: "R' U' R' F2 U' R U2 F2 R", moveCount: 9 },
    { alg: "R U2 F2 R2 U' F' R2 U' R2", moveCount: 9 },
    { alg: "R' U2 F2 R2 U F' R2 U' R2", moveCount: 9 },
    { alg: "F R U' R F R U' F2 R", moveCount: 9 },
  ] },
  "EG1-H-1": { alternates: [
    { alg: "R' U' R' F2 U F' R F'", moveCount: 8 },
    { alg: "U2 R F U R2 F' U R' F", moveCount: 9 },
    { alg: "R' F U2 F2 R2 U F' U' R2", moveCount: 9 },
    { alg: "R' F' R2 U2 F2 U' F' U' R2", moveCount: 9 },
  ] },
  "EG1-H-2": { alternates: [
    { alg: "F U2 F U' R U R' F", moveCount: 8 },
    { alg: "F U' R U' R' F U' F2", moveCount: 8 },
    { alg: "F U2 F2 R' F U' R' U R", moveCount: 9 },
    { alg: "F' R F2 U2 F' U' R' U R", moveCount: 9 },
  ] },
  "EG1-H-3": { alternates: [
    { alg: "F' R2 F' R F R' U R'", moveCount: 8 },
    { alg: "F R2 F U' F' R F' R", moveCount: 8 },
    { alg: "R' U' F' U R2 U R2 F' R", moveCount: 9 },
    { alg: "R F R F' R2 F' R2 U R'", moveCount: 9 },
  ] },
  "EG1-H-4": { alternates: [
    { alg: "F' R U2 R2 F' R F' U2 F", moveCount: 9 },
    { alg: "F' R' F R2 U2 R' F' U2 F", moveCount: 9 },
    { alg: "R U' F' U' F2 R U' R F' R2", moveCount: 10 },
    { alg: "R F U F' U2 R U' F' U R2", moveCount: 10 },
  ] },
};

const EG2_LIBRARY = {
  "EG2-Sune-1": { alternates: [
    { alg: "F U R F' U' R2 F R2", moveCount: 8 },
    { alg: "U2 F R U F' U R2 F' R2", moveCount: 9 },
    { alg: "F U R F' U R2 F' R2 U2", moveCount: 9 },
    { alg: "F R' F' R' U F R' F R2", moveCount: 9 },
  ] },
  "EG2-Sune-2": { alternates: [
    { alg: "R2 F' U2 R U' R U F", moveCount: 8 },
    { alg: "U2 R2 F U2 R' U' R U F", moveCount: 9 },
    { alg: "R2 F U2 R' U' F R F U2", moveCount: 9 },
  ] },
  "EG2-Sune-3": { alternates: [
    { alg: "R U' R F' U2 F' R2 F", moveCount: 8 },
    { alg: "F R2 F' R2 F' R U' R U2", moveCount: 9 },
    { alg: "U2 F U2 F' R2 F' R F' R", moveCount: 9 },
  ] },
  "EG2-Sune-4": { alternates: [
    { alg: "R' F R' F R2 U' F U' F'", moveCount: 9 },
    { alg: "R' F R' F2 U' R U R U2 R", moveCount: 10 },
    { alg: "U2 F' R' U R' U2 F R' U R'", moveCount: 10 },
    { alg: "R' U2 R U2 R2 F2 R' U' R' F", moveCount: 10 },
  ] },
  "EG2-Sune-5": { alternates: [
    { alg: "F2 U F U' R2 F2 R' U2 R", moveCount: 9 },
    { alg: "F2 U F' R2 F2 U R U2 R", moveCount: 9 },
    { alg: "F2 R2 F' R F2 R' U2 R F", moveCount: 9 },
    { alg: "R2 F2 R U2 R U R' U R U'", moveCount: 10 },
  ] },
  "EG2-Sune-6": { alternates: [
    { alg: "F R U' R2 U R' U' F U2 R2", moveCount: 10 },
    { alg: "F U' R' U R2 U' R F U2 R2", moveCount: 10 },
    { alg: "F U' R2 F U R' U R F R", moveCount: 10 },
    { alg: "R U2 F' R2 F R' U F2 U R'", moveCount: 10 },
  ] },
  "EG2-Antisune-1": { alternates: [
    { alg: "R2 F' R2 U F R' U' F'", moveCount: 8 },
    { alg: "R2 F R2 U' F U' R' F' U2", moveCount: 9 },
    { alg: "U2 R2 F R2 U' F R' U' F'", moveCount: 9 },
    { alg: "R2 F' R F' U' R F R F'", moveCount: 9 },
  ] },
  "EG2-Antisune-2": { alternates: [
    { alg: "F' U' R' U R' U2 F R2", moveCount: 8 },
    { alg: "F' U' R' U R U2 F' R2 U2", moveCount: 9 },
    { alg: "U2 F' R' F' U R U2 F' R2", moveCount: 9 },
  ] },
  "EG2-Antisune-3": { alternates: [
    { alg: "F' R2 F U2 F R' U R'", moveCount: 8 },
    { alg: "U2 R' U R' F R2 F R2 F'", moveCount: 9 },
    { alg: "R' F R' F R2 F U2 F' U2", moveCount: 9 },
  ] },
  "EG2-Antisune-4": { alternates: [
    { alg: "F U F' U R2 F' R F' R", moveCount: 9 },
    { alg: "R U' R F' U2 R U' R F U2", moveCount: 10 },
    { alg: "R' U2 R' U' R' U F2 R F' R", moveCount: 10 },
    { alg: "R2 U' R' U F2 R2 U2 R' F' R", moveCount: 10 },
  ] },
  "EG2-Antisune-5": { alternates: [
    { alg: "R' F' R2 F U2 F' R F2 R2", moveCount: 9 },
    { alg: "F' R2 F U2 F2 R F' U' R2", moveCount: 9 },
    { alg: "F' R2 F' R' F2 U2 F U' R2", moveCount: 9 },
    { alg: "U R2 F2 R' U2 R' U' R U' R'", moveCount: 10 },
  ] },
  "EG2-Antisune-6": { alternates: [
    { alg: "R2 U2 F' R' U R2 U' R U F'", moveCount: 10 },
    { alg: "R2 U2 F' U R U' R2 U R' F'", moveCount: 10 },
    { alg: "R' F' R' U' R U' F' R2 U F'", moveCount: 10 },
    { alg: "R U' F2 U' R F' R2 F U2 R'", moveCount: 10 },
  ] },
  "EG2-T-1": { alternates: [
    { alg: "F' R2 F' U2 F R2 F", moveCount: 7 },
    { alg: "U2 F U2 F R2 F' R2 F'", moveCount: 8 },
    { alg: "F R2 F R2 F' U2 F' U2", moveCount: 8 },
  ] },
  "EG2-T-2": { alternates: [
    { alg: "F U' R2 U' R' U R2 F'", moveCount: 8 },
    { alg: "F' R U2 R' U' R' F2 R' F2", moveCount: 9 },
    { alg: "F' U' R' U' R2 U F2 R' F2", moveCount: 9 },
  ] },
  "EG2-T-3": { alternates: [
    { alg: "R' U F2 U F U' F2 R", moveCount: 8 },
    { alg: "R U F U F2 U' R2 F R2", moveCount: 9 },
    { alg: "R F' U2 F U F R2 F R2", moveCount: 9 },
  ] },
  "EG2-T-4": { alternates: [
    { alg: "F R' F R' U R' U' F2", moveCount: 8 },
    { alg: "F2 U R U' R F' R F'", moveCount: 8 },
    { alg: "R' U R U2 R2 F' R U' R", moveCount: 9 },
    { alg: "R' U R' F R2 U2 R' U' R", moveCount: 9 },
  ] },
  "EG2-T-5": { alternates: [
    { alg: "F2 R2 F' R U R' U' F'", moveCount: 8 },
    { alg: "F2 R2 F U' R' F R F", moveCount: 8 },
    { alg: "R U' F' U' R U' F2 R F", moveCount: 9 },
    { alg: "R' F U R U' F R2 U' F'", moveCount: 9 },
  ] },
  "EG2-T-6": { alternates: [
    { alg: "F R U2 R2 U R U' R U' F'", moveCount: 10 },
    { alg: "F R' U2 R2 U' R U' R U' F'", moveCount: 10 },
    { alg: "R' U R' F2 R F2 U' F U R", moveCount: 10 },
    { alg: "F R U R' U R' U R U2 R F'", moveCount: 11 },
  ] },
  "EG2-U-1": { alternates: [
    { alg: "R U F R' F' R F2 R2", moveCount: 8 },
    { alg: "R' F' U' F U R' F2 R2", moveCount: 8 },
    { alg: "R' F' U2 R U' F R U F'", moveCount: 9 },
    { alg: "R U2 R2 F U' F U R' F2", moveCount: 9 },
  ] },
  "EG2-U-2": { alternates: [
    { alg: "R' F' U' R U2 R' U F R", moveCount: 9 },
    { alg: "R2 U F R' F2 R F' U' R2", moveCount: 9 },
    { alg: "F' U' F U2 F2 R2 F U F", moveCount: 9 },
    { alg: "F' U' F' R2 F2 U2 F' U F", moveCount: 9 },
  ] },
  "EG2-U-3": { alternates: [
    { alg: "F' U2 R U R F' R F' R'", moveCount: 9 },
    { alg: "R2 U R' F R F R2 U' F U", moveCount: 10 },
    { alg: "R2 F2 R' U R' U' F' U' F U", moveCount: 10 },
    { alg: "U' R2 F2 U' R' U F R F' R", moveCount: 10 },
  ] },
  "EG2-U-4": { alternates: [
    { alg: "R U2 F' U' F' R F' R F", moveCount: 9 },
    { alg: "R2 F U' R U R2 U2 R' F2 R", moveCount: 10 },
    { alg: "R2 F U' R U' R2 U2 R F2 R", moveCount: 10 },
    { alg: "R U F' U' R2 U F2 R' F' R'", moveCount: 10 },
  ] },
  "EG2-U-5": { alternates: [
    { alg: "F U R' U R' U R2 U2 R F'", moveCount: 10 },
    { alg: "F U R' U R' U' R2 U2 R' F'", moveCount: 10 },
    { alg: "R' U' F' U F2 R' F2 R U' R", moveCount: 10 },
    { alg: "F R' U2 R' U' R U' R U' R' F'", moveCount: 11 },
  ] },
  "EG2-U-6": { alternates: [
    { alg: "R2 U2 R U R' U F' R U' R", moveCount: 10 },
    { alg: "R2 U2 R' U' F R' F R' U R'", moveCount: 10 },
    { alg: "F U' F R' U F' U F U2 F2", moveCount: 10 },
    { alg: "F' U F' R F' R U' F' U2 F2", moveCount: 10 },
  ] },
  "EG2-L-1": { alternates: [
    { alg: "F R2 U' R U R2 U F'", moveCount: 8 },
    { alg: "F2 R F2 R U R U2 R' F", moveCount: 9 },
    { alg: "F2 R F2 U' R2 U R U F", moveCount: 9 },
  ] },
  "EG2-L-2": { alternates: [
    { alg: "R' F2 U F' U' F2 U' R", moveCount: 8 },
    { alg: "R2 F' R2 U F2 U' F' U' R'", moveCount: 9 },
    { alg: "R2 F' R2 F' U' F' U2 F R'", moveCount: 9 },
  ] },
  "EG2-L-3": { alternates: [
    { alg: "R F R' F R' U' R' U2 F", moveCount: 9 },
    { alg: "R' U' F' R' U R U F' R2 F2", moveCount: 10 },
    { alg: "R' F R' F' U' R U F2 R2 U", moveCount: 10 },
    { alg: "R' F U2 R' U' F' R U' F2 U", moveCount: 10 },
  ] },
  "EG2-L-4": { alternates: [
    { alg: "F' R' F R' F U F U2 R'", moveCount: 9 },
    { alg: "R' F2 R U2 R2 U' R' U F' R2", moveCount: 10 },
    { alg: "R' F2 R' U2 R2 U R' U F' R2", moveCount: 10 },
    { alg: "R F R F2 U' R2 U F U' R'", moveCount: 10 },
  ] },
  "EG2-L-5": { alternates: [
    { alg: "F' U F U2 R2 F2 R' U2 R'", moveCount: 9 },
    { alg: "F' U F' R2 U2 R' U2 F2 R'", moveCount: 9 },
    { alg: "F' U F' R2 F2 U2 R U2 R'", moveCount: 9 },
    { alg: "F' U' R2 U2 F R U2 F2 R'", moveCount: 9 },
  ] },
  "EG2-L-6": { alternates: [
    { alg: "R U' R F' R' F' U R2 U' R", moveCount: 10 },
    { alg: "R' F R2 F' R U F U' F R'", moveCount: 10 },
    { alg: "F R' F2 R F' U' R' U R' F", moveCount: 10 },
    { alg: "F' U F' R F R U' F2 U F'", moveCount: 10 },
  ] },
  "EG2-Pi-1": { alternates: [
    { alg: "R F2 R2 F U F2 U2 F", moveCount: 8 },
    { alg: "R F2 R2 F U' F2 U2 F'", moveCount: 8 },
    { alg: "R' F2 R2 F' U F2 U2 F", moveCount: 8 },
    { alg: "R' F2 R2 F' U' F2 U2 F'", moveCount: 8 },
  ] },
  "EG2-Pi-2": { alternates: [
    { alg: "F R2 F R2 F2 U' F U' F'", moveCount: 9 },
    { alg: "F R2 F' U F2 R2 F' U' F'", moveCount: 9 },
    { alg: "R U' F2 R U' R2 U R U' F", moveCount: 10 },
    { alg: "R U' F2 R2 U R U2 R' U2 F", moveCount: 10 },
  ] },
  "EG2-Pi-3": { alternates: [
    { alg: "F R' U2 F' R2 F' R F2 R", moveCount: 9 },
    { alg: "R2 U' R' U' F2 R F' R U' F", moveCount: 10 },
    { alg: "U2 F' U R2 F U2 F R' U2 R'", moveCount: 10 },
    { alg: "F R U2 F R2 U2 F' R F2 R", moveCount: 10 },
  ] },
  "EG2-Pi-4": { alternates: [
    { alg: "F U F R2 F2 U' F R2 F'", moveCount: 9 },
    { alg: "F U F' U F2 R2 F' R2 F'", moveCount: 9 },
    { alg: "F' U R' U' R2 U R' F2 U R'", moveCount: 10 },
    { alg: "F' U2 R U2 R' U' R2 F2 U R'", moveCount: 10 },
  ] },
  "EG2-Pi-5": { alternates: [
    { alg: "R' U F' R U R' U2 F2 R", moveCount: 9 },
    { alg: "R F' R F' U' R U2 F2 R'", moveCount: 9 },
    { alg: "R U' R' U R2 F2 U R U' R2", moveCount: 10 },
    { alg: "R U' R' U R F' R U F2 R'", moveCount: 10 },
  ] },
  "EG2-Pi-6": { alternates: [
    { alg: "F R' F2 R' F2 U' R2 U' R", moveCount: 9 },
    { alg: "R2 U R2 F' U2 F' R2 U F2", moveCount: 9 },
    { alg: "R2 U' R2 F R2 F R2 U' F2", moveCount: 9 },
    { alg: "F' U F2 U R2 F U2 F R'", moveCount: 9 },
  ] },
  "EG2-H-1": { alternates: [
    { alg: "F2 R2 U2 F' U2 F2", moveCount: 6 },
    { alg: "F2 U2 F U2 R2 F2", moveCount: 6 },
    { alg: "R2 U2 F2 R2 F U2 F2", moveCount: 7 },
    { alg: "U2 F2 R2 U2 F U2 F2", moveCount: 7 },
  ] },
  "EG2-H-2": { alternates: [
    { alg: "R2 F U2 F2 R2 F' R2", moveCount: 7 },
    { alg: "R2 F' R2 F2 U2 F R2", moveCount: 7 },
    { alg: "R2 F R2 F2 R2 U2 F R2", moveCount: 8 },
    { alg: "R2 F R2 F2 U2 F' R2 U2", moveCount: 8 },
  ] },
  "EG2-H-3": { alternates: [
    { alg: "R' F2 R' F R2 F U2 R F'", moveCount: 9 },
    { alg: "F' U R' F R' F2 U R U R2", moveCount: 10 },
    { alg: "R U2 R F' U2 F' R2 U' F U2", moveCount: 10 },
    { alg: "R' F2 R' F U2 R2 F' U2 R' F'", moveCount: 10 },
  ] },
  "EG2-H-4": { alternates: [
    { alg: "F' U2 R2 F R' U' R U' F", moveCount: 9 },
    { alg: "F U2 R2 F' U F U' R F'", moveCount: 9 },
    { alg: "F' R2 F' R2 U2 R U' R U' F", moveCount: 10 },
    { alg: "F R U2 R U2 R F' R2 U2 F2", moveCount: 10 },
  ] },
};

export const SETS = {
  "222-OLL": {
    id: "222-OLL",
    event: '222',
    n: 2,
    label: "OLL",
    title: t("Orient every corner — the first step of Ortega"),
    cases: OLL_222,
    library: OLL_LIBRARY,
    done: "oriented2",
    picture: 'orientation',

    trainerMode: "222oll",
    source: 'generated',
    caseLabel: (c) => c.name,
    describe: (c) => c.label,
  },
  "222-PBL": {
    id: "222-PBL",
    event: '222',
    n: 2,
    label: "PBL",
    title: t("Permute both layers at once — the last step of Ortega"),
    cases: PBL_222,
    library: PBL_LIBRARY,
    done: "solved",

    trainerMode: "222pbl",
    source: 'generated',
    groups: ["bottom solved","bottom adjacent swap","bottom diagonal swap"],
    groupOf: (c) => c.group,
    defaultGroup: null,
    caseLabel: (c) => c.name,
    describe: (c) => c.label,
  },
  "222-CLL": {
    id: "222-CLL",
    event: '222',
    n: 2,
    label: "CLL",
    title: t("Bottom layer done — finish the top in one algorithm"),
    cases: CLL_222,
    library: CLL_LIBRARY,
    done: "solved",

    trainerMode: "222cll",
    source: 'generated',
    groups: ["Sune","Antisune","T","U","L","Pi","H"],
    groupOf: (c) => c.group,
    defaultGroup: null,
    caseLabel: (c) => c.name,
    describe: (c) => c.label,
  },
  "222-EG1": {
    id: "222-EG1",
    event: '222',
    n: 2,
    label: "EG-1",
    title: t("Bottom layer oriented with one adjacent swap — finish in one algorithm"),
    cases: EG1_222,
    library: EG1_LIBRARY,
    done: "solved",

    trainerMode: "222eg1",
    source: 'generated',
    groups: ["Sune","Antisune","T","U","L","Pi","H"],
    groupOf: (c) => c.group,
    defaultGroup: null,
    caseLabel: (c) => c.name,
    describe: (c) => c.label,
  },
  "222-EG2": {
    id: "222-EG2",
    event: '222',
    n: 2,
    label: "EG-2",
    title: t("Bottom layer oriented with a diagonal swap — finish in one algorithm"),
    cases: EG2_222,
    library: EG2_LIBRARY,
    done: "solved",

    trainerMode: "222eg2",
    source: 'generated',
    groups: ["Sune","Antisune","T","U","L","Pi","H"],
    groupOf: (c) => c.group,
    defaultGroup: null,
    caseLabel: (c) => c.name,
    describe: (c) => c.label,
  },
};
