/* ===========================================================
   Tagda Timer — OLL algorithm library: all 57 cases.

   GENERATED by tools/build-alglibrary.py. Do not hand-edit; corrections
   belong in that script's tables, where they are explained.

   Scraped from SpeedCubeDB, which orders the variants of a case by how
   many of its users actually drill each one, and kept in that order —
   index 0 is the one most people reach for, not the one with the fewest
   moves.

   Two things had to be corrected on the way in, and both were found by
   executing the data rather than by reading it: finger-trick parentheses
   that are not move notation, and 50 rows that were the inverse of an
   algorithm — the moves that create the case, not the ones that solve
   it. ALGLIBRARY.md §3.4 has the detail.

   Nothing here is trusted because a website printed it:
   tools/verify-alglibrary.html executes every entry against its own case.

   `notes` appears only where there is something true to say. The pass did
   not invent a rationale for each algorithm — a plausible-sounding
   fabricated reason on 185 entries is worse than no reason at all.
   =========================================================== */

export const OLL_LIBRARY = {
  OLL1: { alternates: [
    { alg: "R U2 R2 F R F' U2 R' F R F'", moveCount: 11, notes: "this app's own default for the case" },
    { alg: "R U2 R' R' F R F' U2 R' F R F'", moveCount: 12 },
    { alg: "y R U' R2 D' r U' r' D R2 U R'", moveCount: 12 },
    { alg: "f R U R' U' R f' U' r' U' R U M'", moveCount: 13 },
  ] },
  OLL2: { alternates: [
    { alg: "f U R U' R' f' F U R U' R' F'", moveCount: 12 },
    { alg: "F R U R' U' F' f R U R' U' f'", moveCount: 12, notes: "this app's own default for the case" },
    { alg: "y' R U' R2 D' r U r' D R2 U R'", moveCount: 12 },
    { alg: "F R U R' U' S R U R' U' f'", moveCount: 11 },
  ] },
  OLL3: { alternates: [
    { alg: "y' f R U R' U' f' U' F R U R' U' F'", moveCount: 14 },
    { alg: "y R' F2 R2 U2 R' F R U2 R2 F2 R", moveCount: 12 },
    { alg: "r' R2 U R' U r U2 r' U M'", moveCount: 10 },
  ] },
  OLL4: { alternates: [
    { alg: "y' f R U R' U' f' U F R U R' U' F'", moveCount: 14 },
    { alg: "y' R' F2 R2 U2 R' F' R U2 R2 F2 R", moveCount: 12 },
    { alg: "R' F R F' U' S R' U' R U R S'", moveCount: 12 },
  ] },
  OLL5: { alternates: [
    { alg: "r' U2 R U R' U r", moveCount: 7, notes: "this app's own default for the case" },
    { alg: "y2 l' U2 L U L' U l", moveCount: 8 },
    { alg: "y2 R' F2 r U r' F R", moveCount: 8 },
  ] },
  OLL6: { alternates: [
    { alg: "r U2 R' U' R U' r'", moveCount: 7, notes: "this app's own default for the case" },
    { alg: "F U' R2 D R' U' R D' R2 U F'", moveCount: 11 },
    { alg: "y2 l U2 L' U' L U' l'", moveCount: 8 },
  ] },
  OLL7: { alternates: [
    { alg: "r U R' U R U2 r'", moveCount: 7, notes: "this app's own default for the case" },
    { alg: "S' R U R' U R U2 R' U S", moveCount: 10 },
    { alg: "L' U2 L U2 L F' L' F", moveCount: 8 },
  ] },
  OLL8: { alternates: [
    { alg: "y2 r' U' R U' R' U2 r", moveCount: 8 },
    { alg: "l' U' L U' L' U2 l", moveCount: 7 },
    { alg: "R U2 R' U2 R' F R F'", moveCount: 8 },
  ] },
  OLL9: { alternates: [
    { alg: "y R U R' U' R' F R2 U R' U' F'", moveCount: 12 },
    { alg: "y R U R' U' R' F R R U R' U' F'", moveCount: 13 },
    { alg: "R U2 R' U' S' R U' R' S", moveCount: 9 },
    { alg: "y2 F' U' F r U' r' U r U r'", moveCount: 11 },
  ] },
  OLL10: { alternates: [
    { alg: "R U R' U R' F R F' R U2 R'", moveCount: 11, notes: "this app's own default for the case" },
    { alg: "y F U F' R' F R U' R' F' R", moveCount: 11 },
    { alg: "y M' R' U2 R U R' U R U M", moveCount: 11 },
  ] },
  OLL11: { alternates: [
    { alg: "r' R2 U R' U R U2 R' U M'", moveCount: 10 },
    { alg: "M R U R' U R U2 R' U M'", moveCount: 10 },
    { alg: "y2 r U R' U R' F R F' R U2 r'", moveCount: 12 },
    { alg: "S R U R' U R U2 R' U2 S'", moveCount: 10 },
  ] },
  OLL12: { alternates: [
    { alg: "F R U R' U' F' U F R U R' U' F'", moveCount: 13 },
    { alg: "y' M' R' U' R U' R' U2 R U' M", moveCount: 11 },
    { alg: "y' S R' U' R U' R' U2 R U2 S'", moveCount: 11 },
  ] },
  OLL13: { alternates: [
    { alg: "r U' r' U' r U r' F' U F", moveCount: 10 },
    { alg: "F U R U2 R' U' R U R' F'", moveCount: 10 },
    { alg: "F U R U' R2 F' R U R U' R'", moveCount: 11, notes: "this app's own default for the case" },
  ] },
  OLL14: { alternates: [
    { alg: "R' F R U R' F' R F U' F'", moveCount: 10, notes: "this app's own default for the case" },
    { alg: "r U R' U' r' F R2 U R' U' F'", moveCount: 11 },
    { alg: "l' U l U l' U' l F U' F'", moveCount: 10 },
  ] },
  OLL15: { alternates: [
    { alg: "r' U' r R' U' R U r' U r", moveCount: 10 },
    { alg: "y2 l' U' l L' U' L U l' U l", moveCount: 11 },
    { alg: "r' U' M' U' R U r' U r", moveCount: 9 },
  ] },
  OLL16: { alternates: [
    { alg: "r U r' R U R' U' r U' r'", moveCount: 10, notes: "this app's own default for the case" },
    { alg: "r U M U R' U' r U' r'", moveCount: 9 },
    { alg: "y2 R' F R U R' U' F' R U' R' U2 R", moveCount: 13 },
  ] },
  OLL17: { alternates: [
    { alg: "R U R' U R' F R F' U2 R' F R F'", moveCount: 13 },
    { alg: "y2 F R' F' R U S' R U' R' S", moveCount: 11 },
    { alg: "y2 F R' F' R2 r' U R U' R' U' M'", moveCount: 12 },
  ] },
  OLL18: { alternates: [
    { alg: "r U R' U R U2 r2 U' R U' R' U2 r", moveCount: 13, notes: "this app's own default for the case" },
    { alg: "y R U2 R' R' F R F' U2 M' U R U' r'", moveCount: 14 },
    { alg: "y R U2 R2 F R F' U2 M' U R U' r'", moveCount: 13 },
    { alg: "y F S' R U' R' S R U2 R' U' F'", moveCount: 12 },
  ] },
  OLL19: { alternates: [
    { alg: "M U R U R' U' M' R' F R F'", moveCount: 11 },
    { alg: "y S' R U R' S U' R' F R F'", moveCount: 11 },
    { alg: "R' U2 F R U R' U' F2 U2 F R", moveCount: 11 },
  ] },
  OLL20: { alternates: [
    { alg: "r U R' U' M2' U R U' R' U' M'", moveCount: 11 },
    { alg: "r U R' U' M2 U R U' R' U' M'", moveCount: 11, notes: "this app's own default for the case" },
    { alg: "M' U2 M U2 M' U M U2 M' U2 M", moveCount: 11 },
    { alg: "S' R U R' S U' M' U R U' r'", moveCount: 11 },
  ] },
  OLL21: { alternates: [
    { alg: "R U R' U R U' R' U R U2' R' y'", moveCount: 12 },
    { alg: "R U R' U R U' R' U R U2 R'", moveCount: 11 },
    { alg: "y R U2 R' U' R U R' U' R U' R'", moveCount: 12 },
    { alg: "y F R U R' U' R U R' U' R U R' U' F'", moveCount: 15 },
  ] },
  OLL22: { alternates: [
    { alg: "R' U2' R2' U R2' U R2' U2' R'", moveCount: 9 },
    { alg: "R U2 R2' U' R2 U' R2' U' U' R", moveCount: 10 },
    { alg: "R U2 R2 U' R2 U' R2 U2 R", moveCount: 9, notes: "this app's own default for the case" },
    { alg: "R' U2 R2 U R2 U R2 U2 R'", moveCount: 9 },
    { alg: "f R U R' U' S' R U R' U' F'", moveCount: 11 },
  ] },
  OLL23: { alternates: [
    { alg: "R2 D R' U2 R D' R' U2 R'", moveCount: 9 },
    { alg: "y2 R2 D' R U2 R' D R U2 R", moveCount: 10 },
    { alg: "R U R' U R U2 R2 U' R U' R' U2 R", moveCount: 13 },
  ] },
  OLL24: { alternates: [
    { alg: "r U R' U' r' F R F'", moveCount: 8, notes: "this app's own default for the case" },
    { alg: "y2 R' F' r U R U' r' F", moveCount: 9 },
    { alg: "y' x' R U R' D R U' R' D' x", moveCount: 11 },
  ] },
  OLL25: { alternates: [
    { alg: "y F' r U R' U' r' F R", moveCount: 9 },
    { alg: "R U2 R D R' U2 R D' R2", moveCount: 9 },
    { alg: "F R' F' r U R U' r'", moveCount: 8 },
  ] },
  OLL26: { alternates: [
    { alg: "y R U2 R' U' R U' R'", moveCount: 8 },
    { alg: "R' U' R U' R' U2 R", moveCount: 7 },
    { alg: "y2 L' U' L U' L' U2 L", moveCount: 8 },
  ] },
  OLL27: { alternates: [
    { alg: "R U R' U R U2 R'", moveCount: 7, notes: "this app's own default for the case" },
    { alg: "y' R' U2 R U R' U R", moveCount: 8 },
    { alg: "y L' U2 L U L' U L", moveCount: 8 },
  ] },
  OLL28: { alternates: [
    { alg: "r U R' U' M U R U' R'", moveCount: 9 },
    { alg: "r U R' U' r' R U R U' R'", moveCount: 10, notes: "this app's own default for the case" },
    { alg: "R' F R S R' F' R S'", moveCount: 8 },
  ] },
  OLL29: { alternates: [
    { alg: "M U R U R' U' R' F R F' M'", moveCount: 11 },
    { alg: "y R U R' U' R U' R' F' U' F R U R'", moveCount: 14 },
    { alg: "r2 D' r U r' D r2 U' r' U' r", moveCount: 11 },
    { alg: "y S' R U R' U' R' F R F' U S", moveCount: 12 },
  ] },
  OLL30: { alternates: [
    { alg: "y2 F U R U2 R' U' R U2 R' U' F'", moveCount: 12 },
    { alg: "y' r' D' r U' r' D r2 U' r' U r U r'", moveCount: 14 },
    { alg: "y2 F R' F R2 U' R' U' R U R' F2", moveCount: 12 },
  ] },
  OLL31: { alternates: [
    { alg: "R' U' F U R U' R' F' R", moveCount: 9, notes: "this app's own default for the case" },
    { alg: "y2 S' L' U' L U L F' L' f", moveCount: 10 },
    { alg: "y S R U R' U' f' U' F", moveCount: 9 },
  ] },
  OLL32: { alternates: [
    { alg: "S R U R' U' R' F R f'", moveCount: 9 },
    { alg: "y2 L U F' U' L' U L F L'", moveCount: 10 },
    { alg: "R U B' U' R' U R B R'", moveCount: 9 },
  ] },
  OLL33: { alternates: [
    { alg: "R U R' U' R' F R F'", moveCount: 8, notes: "this app's own default for the case" },
    { alg: "y2 L' U' L U L F' L' F", moveCount: 9 },
    { alg: "y2 r' F' r U r U' r' F", moveCount: 9 },
  ] },
  OLL34: { alternates: [
    { alg: "y2 R U R2 U' R' F R U R U' F'", moveCount: 12 },
    { alg: "y f R f' U' r' U' R U M'", moveCount: 10 },
    { alg: "F R U R' U' R' F' r U R U' r'", moveCount: 12 },
  ] },
  OLL35: { alternates: [
    { alg: "R U2 R2 F R F' R U2 R'", moveCount: 9, notes: "this app's own default for the case" },
    { alg: "R U2 R' R' F R F' R U2 R'", moveCount: 10 },
    { alg: "f R U R' U' f' R U R' U R U2 R'", moveCount: 13 },
    { alg: "R U2 R' d' R' F R U' R' F' R", moveCount: 11 },
  ] },
  OLL36: { alternates: [
    { alg: "y2 L' U' L U' L' U L U L F' L' F", moveCount: 13 },
    { alg: "y R U R2 F' U' F U R2 U2 R'", moveCount: 11 },
    { alg: "y2 R U R' F' R U R' U' R' F R U' R' F R F'", moveCount: 17 },
  ] },
  OLL37: { alternates: [
    { alg: "F R U' R' U' R U R' F'", moveCount: 9 },
    { alg: "F R' F' R U R U' R'", moveCount: 8, notes: "this app's own default for the case" },
    { alg: "y F' r U r' U' r' F r", moveCount: 9 },
  ] },
  OLL38: { alternates: [
    { alg: "R U R' U R U' R' U' R' F R F'", moveCount: 12, notes: "this app's own default for the case" },
    { alg: "y F R U' R' S U' R U R' f'", moveCount: 11 },
    { alg: "r U R' U' r' F R U R U' R' F'", moveCount: 12 },
  ] },
  OLL39: { alternates: [
    { alg: "y L F' L' U' L U F U' L'", moveCount: 10 },
    { alg: "y' f' r U r' U' r' F r S", moveCount: 10 },
    { alg: "y' R U R' F' U' F U R U2 R'", moveCount: 11 },
  ] },
  OLL40: { alternates: [
    { alg: "y R' F R U R' U' F' U R", moveCount: 10 },
    { alg: "y' f R' F' R U R U' R' S'", moveCount: 10 },
    { alg: "R r D r' U r D' r' U' R'", moveCount: 10 },
  ] },
  OLL41: { alternates: [
    { alg: "y2 R U R' U R U2 R' F R U R' U' F'", moveCount: 14 },
    { alg: "y2 F U R2 D R' U' R D' R2 F'", moveCount: 11 },
    { alg: "y' S U' R' F' U' F U R S'", moveCount: 10 },
  ] },
  OLL42: { alternates: [
    { alg: "R' U' R U' R' U2 R F R U R' U' F'", moveCount: 13, notes: "this app's own default for the case" },
    { alg: "y F S' R U R' U' F' U S", moveCount: 10 },
    { alg: "y R' F R F' R' F R F' R U R' U' R U R'", moveCount: 16 },
  ] },
  OLL43: { alternates: [
    { alg: "f' L' U' L U f", moveCount: 6 },
    { alg: "y R' U' F' U F R", moveCount: 7 },
    { alg: "y2 F' U' L' U L F", moveCount: 7 },
  ] },
  OLL44: { alternates: [
    { alg: "f R U R' U' f'", moveCount: 6 },
    { alg: "y2 F U R U' R' F'", moveCount: 7 },
    { alg: "y R U B U' B' R'", moveCount: 7 },
  ] },
  OLL45: { alternates: [
    { alg: "F R U R' U' F'", moveCount: 6, notes: "this app's own default for the case" },
    { alg: "y R' F' U' F U R", moveCount: 7 },
    { alg: "y2 f U R U' R' f'", moveCount: 7 },
  ] },
  OLL46: { alternates: [
    { alg: "R' U' R' F R F' U R", moveCount: 8, notes: "this app's own default for the case" },
    { alg: "R' F' U' F R U' R' U2 R", moveCount: 9 },
    { alg: "y F R U R' U' F' U' R U R' U R U2 R'", moveCount: 15 },
  ] },
  OLL47: { alternates: [
    { alg: "F' L' U' L U L' U' L U F", moveCount: 10, notes: "this app's own default for the case" },
    { alg: "y' F R' F' R U2 R U' R' U R U2 R'", moveCount: 13 },
    { alg: "R' U' R' F R F' R' F R F' U R", moveCount: 12 },
  ] },
  OLL48: { alternates: [
    { alg: "F R U R' U' R U R' U' F'", moveCount: 10, notes: "this app's own default for the case" },
    { alg: "y2 f U R U' R' U R U' R' f'", moveCount: 11 },
    { alg: "R U2 R' U' R U R' U2 R' F R F'", moveCount: 12 },
  ] },
  OLL49: { alternates: [
    { alg: "y2 r U' r2 U r2 U r2 U' r", moveCount: 10 },
    { alg: "l U' l2 U l2 U l2 U' l", moveCount: 9 },
    { alg: "R B' R2 F R2 B R2 F' R", moveCount: 9 },
  ] },
  OLL50: { alternates: [
    { alg: "r' U r2 U' r2 U' r2 U r'", moveCount: 9, notes: "this app's own default for the case" },
    { alg: "y2 R' F R2 B' R2 F' R2 B R'", moveCount: 10 },
    { alg: "y' R U2 R' U' R U' R' F R U R' U' F'", moveCount: 14 },
  ] },
  OLL51: { alternates: [
    { alg: "f R U R' U' R U R' U' f'", moveCount: 10 },
    { alg: "y2 F U R U' R' U R U' R' F'", moveCount: 11 },
    { alg: "y' R' U' R' F R F' R U' R' U2 R", moveCount: 12 },
  ] },
  OLL52: { alternates: [
    { alg: "F R U R' d R' U' R U' R'", moveCount: 10 },
    { alg: "y2 R' F' U' F U' R U R' U R", moveCount: 11 },
    { alg: "R U R' U R U' B U' B' R'", moveCount: 10, notes: "this app's own default for the case" },
    { alg: "R U R' U R d' R U' R' F'", moveCount: 10 },
  ] },
  OLL53: { alternates: [
    { alg: "r' U2' R U R' U' R U R' U r", moveCount: 11 },
    { alg: "r' U' R U' R' U R U' R' U2 r", moveCount: 11 },
    { alg: "y2 l' U' L U' L' U L U' L' U2 l", moveCount: 12 },
    { alg: "y r' U2 R U R' U' R U R' U r", moveCount: 12 },
  ] },
  OLL54: { alternates: [
    { alg: "r U2' R' U' R U R' U' R U' r'", moveCount: 11 },
    { alg: "r U R' U R U' R' U R U2 r'", moveCount: 11 },
    { alg: "y' r U2 R' U' R U R' U' R U' r'", moveCount: 12 },
    { alg: "y' r U r' R U R' U' R U R' U' r U' r'", moveCount: 15 },
  ] },
  OLL55: { alternates: [
    { alg: "R U2 R2 U' R U' R' U2 F R F'", moveCount: 11, notes: "this app's own default for the case" },
    { alg: "y R' F U R U' R2 F' R2 U R' U' R", moveCount: 13 },
    { alg: "y R' F R U R U' R2 F' R2 U' R' U R U R'", moveCount: 16 },
  ] },
  OLL56: { alternates: [
    { alg: "r U r' U R U' R' U R U' R' r U' r'", moveCount: 14, notes: "this app's own default for the case" },
    { alg: "r U r' U R U' R' M' U R U2 r'", moveCount: 12 },
    { alg: "F R U R' U' R F' r U R' U' r'", moveCount: 12 },
  ] },
  OLL57: { alternates: [
    { alg: "R U R' U' M' U R U' r'", moveCount: 9, notes: "this app's own default for the case" },
    { alg: "y R U' R' S' R U R' S", moveCount: 9 },
    { alg: "y R U R' S' R U' R' S", moveCount: 9 },
  ] },
};
