/* ===========================================================
   Tagda Timer — algorithm library core (no DOM in this file).

   Three layers, deliberately kept apart so none of them can clobber
   another:

     algs.js              one canonical alg per case, unchanged by this
                          feature — still the fallback everywhere.
     alglibrary-*.js,     community alternates, read-only, ship with the
     algsets/*.js         app. algsets/ is generated by
                          tools/import-cubingapp.mjs.
     IndexedDB `kv`       your drag order and your own algs, per device.

   Nothing here trusts an algorithm it has not executed. `verify()` runs
   the candidate against the case's own scrambled state on a simulated
   puzzle — cubenet.js for every cube size, puzzles.js for pyraminx, skewb
   and square-1 — and both the shipped files and the "add your own" box go
   through it. A wrong alg in a cubing app teaches someone the wrong thing,
   which is worse than a missing feature.
   =========================================================== */

import { PLL, OLL } from './algs.js';
import { PLL_LIBRARY } from './alglibrary-pll.js';
import { OLL_LIBRARY } from './alglibrary-oll.js';
import { faceletsFor, parseAlg } from './cubenet.js';
import { KV } from './db.js';
import { invert } from './util.js';

/* ---------------------------------------------------------
   Sets
   --------------------------------------------------------- */

/* Plain-English descriptors. §2: a card labelled only "T" means nothing to
   anyone who has not memorised PLL letters, and recognition is by shape. The
   letter stays for people who did learn it; this is what the card says next
   to the picture. OLL takes its descriptor from the shape name algs.js
   already carries. */
const PLL_DESC = {
  Aa: 'three corners cycle one way, all four edges solved',
  Ab: 'three corners cycle the other way, all four edges solved',
  E:  'both corner pairs swap, edges stay',
  F:  'two adjacent corners and two edges swap',
  Ga: 'three corners and three edges cycle',
  Gb: 'three corners and three edges cycle',
  Gc: 'three corners and three edges cycle',
  Gd: 'three corners and three edges cycle',
  H:  'both edge pairs swap across the middle',
  Ja: 'one adjacent corner and edge pair swaps',
  Jb: 'one adjacent corner and edge pair swaps',
  Na: 'two opposite corner and edge pairs swap',
  Nb: 'two opposite corner and edge pairs swap',
  Ra: 'two corners and two edges swap, one bar',
  Rb: 'two corners and two edges swap, one bar',
  T:  'adjacent corner swap plus opposite edge swap',
  Ua: 'three edges cycle anticlockwise, corners solved',
  Ub: 'three edges cycle clockwise, corners solved',
  V:  'two adjacent corners and two edges swap',
  Y:  'two adjacent corners and two opposite edges swap',
  Z:  'both edge pairs swap side to side',
};

export const SETS = {
  PLL: {
    id: 'PLL',
    event: '333',
    label: 'PLL',
    title: 'Permutation of the last layer',
    cases: PLL,
    library: PLL_LIBRARY,
    trained: true,
    trainerMode: 'pll',
    /* A permutation case has no fixed angle — see caseFacelets. */
    angle: 'auf',
    caseLabel: (c) => `${c.name} perm`,
    describe: (c) => PLL_DESC[c.id] || c.group,
  },
  OLL: {
    id: 'OLL',
    event: '333',
    label: 'OLL',
    title: 'Orientation of the last layer',
    cases: OLL,
    library: OLL_LIBRARY,
    trained: true,
    trainerMode: 'oll',
    done: 'oriented',
    /* An OLL diagram is about which stickers face up, not which colours they
       are — see drawCase in alglibrary-ui.js. */
    picture: 'orientation',
    caseLabel: (c) => `OLL ${c.name}`,
    describe: (c) => (c.label ? c.label.toLowerCase() : c.group),
  },
};

/* ---------------------------------------------------------
   The catalogue: which events have which sets, and where each one comes from
   --------------------------------------------------------- */

/**
 * Nothing but PLL and OLL is statically imported, and that is not tidiness.
 *
 * js/main.js imports this module on the timer's boot path, for
 * `loadLibraryPrefs()` and `preferredAlg()`. ZBLL alone is 472 cases, OLLCP
 * another 342 and the Square-1 sets over 500 between them. Importing any of it
 * here would put all of it in front of the first scramble of every session, to
 * serve a page most sessions never open. Every other set is one dynamic import,
 * fetched the first time something asks for it.
 */
const MODULES = {
  ZBLL: () => import('./alglibrary-zbll.js'),
  F2L: () => import('./alglibrary-f2l.js'),
  '2LOLL': () => import('./alglibrary-333.js'),
  '2LPLL': () => import('./alglibrary-333.js'),
  '222-OLL': () => import('./alglibrary-222.js'),
  '222-PBL': () => import('./alglibrary-222.js'),
  '222-CLL': () => import('./alglibrary-222.js'),
  '222-EG1': () => import('./alglibrary-222.js'),
  '222-EG2': () => import('./alglibrary-222.js'),
};

/* Sets that live entirely in js/algsets/<id>.js. */
const GENERATED = new Set([
  'WV', 'COLL', 'OLLCP', 'CMLL2L', 'CMLL', 'LSEEO', 'LSEEOLR', 'OHCMLL', '444-PLLP',
  'PYRA-LL', 'PYRA-L4E', 'SKEWB-SI', 'SKEWB-SA',
  'SQ1-SHAPE', 'SQ1-CSP', 'SQ1-OBL', 'SQ1-CP', 'SQ1-EO', 'SQ1-EP',
]);

/* Sets the timer already had, with more algorithms for their cases in
   js/algsets/more-<id>.js. */
const MERGED = new Set(['F2L', '2LOLL', 'OLL', '2LPLL', 'PLL', 'ZBLL', '222-PBL', '222-CLL', '222-EG1', '222-EG2']);

/**
 * Every event the library has algorithms for, in the timer's own event
 * order, with its sets in the order they are learned.
 *
 * Only events with something in them are listed. Blindfolded events are left
 * out on purpose, and so is FMC: its algorithms are 3x3 algorithms, and a
 * second copy of the 3x3 tabs under another name is not a set of its own.
 */
export const ALG_EVENTS = [
  { id: '333', label: '3x3', groups: [
    { label: 'CFOP', sets: ['PLL', '2LPLL', 'OLL', '2LOLL', 'F2L'] },
    { label: 'Advanced', sets: ['WV', 'COLL', 'OLLCP', 'ZBLL'] },
    { label: 'Roux', sets: ['CMLL2L', 'CMLL', 'LSEEO', 'LSEEOLR'] },
  ] },
  { id: '222', label: '2x2', groups: [
    { label: 'Ortega', sets: ['222-OLL', '222-PBL'] },
    { label: 'CLL & EG', sets: ['222-CLL', '222-EG1', '222-EG2'] },
  ] },
  { id: '444', label: '4x4', groups: [{ sets: ['444-PLLP'] }] },
  { id: '333oh', label: 'OH', groups: [{ sets: ['OHCMLL'] }] },
  { id: 'pyram', label: 'Pyraminx', groups: [{ sets: ['PYRA-LL', 'PYRA-L4E'] }] },
  { id: 'skewb', label: 'Skewb', groups: [{ sets: ['SKEWB-SI', 'SKEWB-SA'] }] },
  { id: 'sq1', label: 'Square-1', groups: [{ sets: ['SQ1-SHAPE', 'SQ1-CSP', 'SQ1-OBL', 'SQ1-EO', 'SQ1-CP', 'SQ1-EP'] }] },
].map(e => ({ ...e, sets: e.groups.flatMap(g => g.sets) }));

/** Every set id the catalogue mentions, deduplicated. */
export const SET_IDS = [...new Set(ALG_EVENTS.flatMap(e => e.sets))];

/**
 * What a set's tab says before its module has arrived.
 *
 * The tab row has to be complete the moment the page opens — a row that fills
 * in as imports land is a row you cannot click — and a set's own `label`
 * lives inside the module that has not loaded yet.
 */
export const SET_LABELS = {
  F2L: 'F2L', '2LOLL': '2-Look OLL', OLL: 'OLL', '2LPLL': '2-Look PLL', PLL: 'PLL',
  WV: 'WV', COLL: 'COLL', OLLCP: 'OLLCP', ZBLL: 'ZBLL',
  CMLL2L: '2-Look CMLL', CMLL: 'CMLL', LSEEO: 'LSE EO', LSEEOLR: 'EOLR', OHCMLL: 'OH CMLL',
  '222-OLL': 'OLL', '222-PBL': 'PBL', '222-CLL': 'CLL', '222-EG1': 'EG-1', '222-EG2': 'EG-2',
  '444-PLLP': 'PLL Parity',
  'PYRA-LL': 'Last Layer', 'PYRA-L4E': 'L4E',
  'SKEWB-SI': "Sarah's Intermediate", 'SKEWB-SA': "Sarah's Advanced",
  'SQ1-SHAPE': 'Cube Shape', 'SQ1-CSP': 'CSP', 'SQ1-OBL': 'OBL', 'SQ1-EO': 'EO', 'SQ1-CP': 'CP', 'SQ1-EP': 'EP',
};

export const eventEntry = (eventId) => ALG_EVENTS.find(e => e.id === eventId) || null;

/* puzzles.js, once a pyraminx, skewb or square-1 set has needed it. */
let PUZ = null;
const puzzleOf = (set) => set?.puzzle || 'cube';

/**
 * Put a generated set in the registry, with the behaviour a data file cannot
 * carry. Exported for tools/import-cubingapp.mjs, which verifies a set by
 * registering it exactly the way the page will.
 */
export async function registerSet(data) {
  const puzzle = data.puzzle || 'cube';
  if (puzzle !== 'cube' && !PUZ) PUZ = await import('./puzzles.js');
  SETS[data.id] = {
    ...data,
    puzzle,
    adjust: data.adjust || { pre: [''], post: [''] },
    greySet: puzzle === 'cube' && data.gray ? new Set(data.gray) : null,
    groupOf: (c) => c.group,
    caseLabel: (c) => c.name,
    describe: (c) => c.group || '',
  };
  return SETS[data.id];
}

/**
 * Get a set, fetching its module the first time it is asked for, and its
 * extra algorithms if it has any. Already-loaded sets resolve without a
 * network round trip.
 */
export async function loadSet(id) {
  if (!SETS[id]) {
    if (GENERATED.has(id)) {
      const { SET } = await import(`./algsets/${id}.js`);
      if (!SETS[id]) await registerSet(SET);
    } else if (MODULES[id]) {
      const mod = await MODULES[id]();
      /* Folded in only where absent, so a set that has already had its extra
         algorithms attached is never replaced by a bare copy of itself. */
      for (const [k, v] of Object.entries(mod.SETS || { [mod.SET.id]: mod.SET })) {
        if (!SETS[k]) SETS[k] = v;
      }
    }
  }
  const set = SETS[id];
  if (set && MERGED.has(id) && !set.extra) {
    try {
      set.extra = (await import(`./algsets/more-${id}.js`)).EXTRA;
    } catch (err) {
      /* The set is still whole without them — this only costs alternates. */
      console.warn('[alglibrary] extra algorithms unavailable for', id, err.message);
      set.extra = {};
    }
  }
  return set || null;
}

/** Load every set the catalogue lists. Only the verification harness wants this. */
export async function loadAllSets() {
  for (const id of SET_IDS) await loadSet(id);
  return SETS;
}

/** Which set a case id belongs to. Case ids are unique across every set. */
export function setOf(caseId) {
  for (const set of Object.values(SETS)) {
    if (set.cases.some(c => c.id === caseId)) return set;
  }
  return null;
}

export const caseOf = (setId, caseId) =>
  (SETS[setId]?.cases || []).find(c => c.id === caseId) || null;

/**
 * The scrambled state that defines a case: its setup, if it has one, then the
 * case's own alg run backwards. That is exactly how the trainer builds a case
 * scramble (see the header of algs.js), so "solves this case" here means the
 * same thing it means on the timer screen.
 */
export const casePattern = (setId, caseId) => {
  const set = SETS[setId];
  const c = caseOf(setId, caseId);
  if (!c) return null;
  const back = puzzleOf(set) === 'cube' ? invert(c.alg) : PUZ.invertMoves(set.puzzle, c.alg);
  return [c.setup, back].filter(Boolean).join(' ');
};

/* ---------------------------------------------------------
   Verification (§7)
   --------------------------------------------------------- */

const AUFS = ['', 'U', 'U2', "U'"];
const uniform = (grid) => grid.every(row => row.every(s => s === grid[0][0]));

/** Whole cube solved, ignoring which way round it ended up facing. */
function isSolved(f) {
  return ['U', 'R', 'F', 'D', 'L', 'B'].every(face => uniform(f[face]));
}

/**
 * Last layer oriented: the U face is one colour and the two layers below it
 * are untouched. A `y` inside the alg rotates all four side faces together,
 * so each staying uniform below the top row is still the right test.
 */
function isOriented(f) {
  if (!uniform(f.U) || !uniform(f.D)) return false;
  return ['R', 'F', 'L', 'B'].every(face => uniform(f[face].slice(1)));
}

/**
 * First two layers built, last layer ignored.
 *
 * An F2L alg pairs a corner with its edge and puts them in a slot; what it
 * does to the last layer on the way is incidental, and two correct algs for
 * the same case routinely leave the U layer permuted differently. Demanding a
 * solved cube would only ever accept the single alg the case state was built
 * from.
 */
function isFirstTwoLayers(f) {
  if (!uniform(f.D)) return false;
  return ['R', 'F', 'L', 'B'].every(face => uniform(f[face].slice(1)));
}

/**
 * Last layer edges oriented — the first half of two-look OLL. Only the four
 * edge stickers of the U face are asked about.
 */
function isEdgesOriented(f) {
  if (!uniform(f.D)) return false;
  if (!['R', 'F', 'L', 'B'].every(face => uniform(f[face].slice(1)))) return false;
  return [[0, 1], [1, 0], [1, 2], [2, 1]].every(([r, c]) => f.U[r][c] === 'U');
}

/**
 * Last layer corners permuted — the first half of two-look PLL: both corner
 * stickers in the top row of every side face match that face.
 */
function isCornersPermuted(f) {
  if (!uniform(f.D)) return false;
  if (!['R', 'F', 'L', 'B'].every(face => uniform(f[face].slice(1)))) return false;
  if (!uniform(f.U)) return false;
  return ['R', 'F', 'L', 'B'].every(face => f[face][0][0] === face && f[face][0][2] === face);
}

/** Every corner facing the right way, wherever it sits — 2x2 orientation. */
const isAllOriented = (f) => uniform(f.U) && uniform(f.D);

/* What counts as having solved a case. A set names one of these; a single case
   inside a mixed set (two-look OLL holds both edge-orientation and
   corner-orientation cases) may name its own. */
const DONE = {
  solved:   isSolved,
  oriented: isOriented,
  ftl:      isFirstTwoLayers,
  eo:       isEdgesOriented,
  cp:       isCornersPermuted,
  oriented2: isAllOriented,
};

const doneFor = (setId, caseId) => {
  const c = caseId ? caseOf(setId, caseId) : null;
  return DONE[c?.done] || DONE[SETS[setId]?.done] || isSolved;
};

/** Cube size this set's algorithms are executed on. */
const sizeOf = (setId) => SETS[setId]?.n || 3;

/** Facelets of a sequence, with the set's grey stickers tracked. */
export const caseStateFacelets = (setId, seq) =>
  faceletsFor(seq, sizeOf(setId), SETS[setId]?.greySet || null);

/**
 * The grey-sticker standard of "the same case" — the rule for every imported
 * cube set.
 *
 * A diagram greys out the stickers the case does not care about, and that is
 * also the precise statement of what an algorithm for it has to achieve:
 * every sticker that is not grey must end where the target has it, and grey
 * ones can be anywhere grey ones are allowed. For OLL-shaped sets that is
 * "oriented"; for COLL, corners solved and edges merely oriented; for CMLL,
 * the M slice left free — one rule, read off the set's own picture instead of
 * a special case per set. `mergeUD` is LSE edge orientation, where a U or D
 * sticker on the U or D face is equally good.
 */
function sameUnderGrey(f, target, mergeUD) {
  const col = (s) => (mergeUD && s === 'D' ? 'U' : s);
  for (const face of Object.keys(target)) {
    const t = target[face], g = f[face];
    for (let r = 0; r < t.length; r++) {
      for (let c = 0; c < t.length; c++) {
        if (t[r][c] !== 'X' && col(g[r][c]) !== col(t[r][c])) return false;
      }
    }
  }
  return true;
}

/* ---- pyraminx, skewb, square-1 ---- */

function puzzleState(set, seq) {
  const p = PUZ.newPuzzle(set.puzzle);
  if (set.puzzle === 'skewb' && set.gray) p.grey(set.gray);
  return p.apply(seq) ? p : null;
}

const sq1Width = (p) => (p % 2 === 0 ? 2 : 1);
const sq1Square = (face) => face.length === 8 && face.every((p, i) => sq1Width(p) !== sq1Width(face[(i + 1) % 8]));
const sq1Home = (s, which) => s.top.filter(which).every(p => p < 8) && s.bottom.filter(which).every(p => p >= 8);
/* A layer is in order when its pieces run round it in solved order from any
   starting point — the difference is only a turn of that layer. */
const sq1Cyclic = (face, want) => want.some((_, k) => want.every((x, i) => face[(i + k) % face.length] === x));
const isCorner = (p) => p % 2 === 0;

/* Square-1 steps finish at a milestone, not at one exact state: two correct
   cube shape algorithms leave the pieces in different places, and both are
   right. Each set names the milestone it reaches. */
const SQ1_DONE = {
  shape: (s) => sq1Square(s.top) && sq1Square(s.bottom),
  'corner-layers': (s) => SQ1_DONE.shape(s) && sq1Home(s, isCorner),
  layers: (s) => SQ1_DONE.shape(s) && sq1Home(s, () => true),
  corners: (s) => SQ1_DONE.layers(s)
    && sq1Cyclic(s.top.filter(isCorner), [0, 2, 4, 6]) && sq1Cyclic(s.bottom.filter(isCorner), [8, 10, 12, 14]),
  solved: (s) => SQ1_DONE.layers(s)
    && sq1Cyclic(s.top, [0, 1, 2, 3, 4, 5, 6, 7]) && sq1Cyclic(s.bottom, [8, 9, 10, 11, 12, 13, 14, 15]),
};

/** Is a square-1 state at `milestone`? For the importer's step-before checks. */
export const sq1At = (milestone, state) => SQ1_DONE[milestone](state);

function puzzleFinished(set, s, target) {
  if (set.puzzle === 'sq1') return SQ1_DONE[set.done || 'solved'](s);
  /* Pyraminx tips are one flick each and no algorithm is written for them. */
  if (set.puzzle === 'pyram') return s.state.every((v, i) => [0, 4, 8].includes(i % 9) || v === target.state[i]);
  return Object.keys(target.stickers).every(k => target.stickers[k] === 'X' || s.stickers[k] === target.stickers[k]);
}

function verifyOnPuzzle(set, c, alg, from) {
  if (!PUZ || !PUZ.parseMoves(set.puzzle, alg)) return false;
  const target = puzzleState(set, c.setup || '');
  if (!target) return false;
  for (const pre of set.adjust.pre) {
    for (const post of set.adjust.post) {
      const s = puzzleState(set, [from, pre, alg, post].filter(Boolean).join(' '));
      if (s && puzzleFinished(set, s, target)) return true;
    }
  }
  return false;
}

/* F2L is the one set where the slot the alg is written for may not be the slot
   the case is drawn in — the same pair state occurs in all four, and alg lists
   give algs for each. A cube rotation is free there in a way it is not for a
   last-layer case: you turn the cube to put the slot in front. Rotations that
   would move the cross off the bottom are not free and are not tried. */
const F2L_ROTS = ['', 'y', "y'", 'y2'];

/* The 24 ways to hold a cube, and the moves that can change which one you are
   holding: rotations, slices and wide turns all move the centres. */
const ORIENTATIONS = ['', 'x', "x'", 'x2', 'z', "z'"].flatMap(a => ['', 'y', 'y2', "y'"].map(b => [a, b].filter(Boolean).join(' ')));
const TURNS_CUBE = /[xyzMESudfblr]|w/;

/* Turns of two opposite layers together, per axis — the free end-of-alg
   adjustments of a 2x2. */
const quarter = (f) => ['', f, `${f}2`, `${f}'`];
const LAYER_PAIRS = [['U', 'D'], ['F', 'B'], ['R', 'L']]
  .map(([a, b]) => quarter(a).flatMap(x => quarter(b).map(y => [x, y].filter(Boolean).join(' '))));
const ANY_PAIR = [...new Set(LAYER_PAIRS.flat())];

/**
 * Does `alg` solve `caseId`?
 *
 * The AUF search is not leniency — a U turn before or after is free on a real
 * cube, and every published alg sheet assumes you will make it. Imported sets
 * say which freedoms they have in `adjust` (a CMLL can also leave the M slice
 * turned, a square-1 step a layer half-turned).
 *
 * `from`, when given, replaces the case's own scrambled state — how the setup
 * audit asks "does this algorithm finish the cube *that* setup builds".
 */
export function verifyAlgForCase(setId, caseId, alg, from = null) {
  const set = SETS[setId];
  const c = caseOf(setId, caseId);
  if (!set || !c) return false;
  const start = from ?? casePattern(setId, caseId);
  if (start == null) return false;
  if (puzzleOf(set) !== 'cube') return verifyOnPuzzle(set, c, alg, start);
  if (!parseAlg(alg)) return false;

  const n = sizeOf(setId);
  if (set.greySet) {
    const target = faceletsFor(c.setup || '', n, set.greySet);
    /* An algorithm with a `y` or a `d` in it can finish with the whole cube
       held differently. Holding it differently is free, so the end state is
       compared from every orientation — but only when something in play can
       actually turn the cube, because it is 24 times the work. */
    const holds = TURNS_CUBE.test(start) || TURNS_CUBE.test(alg) ? ORIENTATIONS : [''];
    /* The hold goes before the post-adjustment: after an algorithm that ends
       in a `z`, the layer an AUF has to turn is the one that was on top. */
    for (const pre of set.adjust.pre) {
      for (const post of set.adjust.post) {
        for (const hold of holds) {
          const f = faceletsFor([start, pre, alg, hold, post].filter(Boolean).join(' '), n, set.greySet);
          if (sameUnderGrey(f, target, set.mergeUD)) return true;
        }
      }
    }
    return false;
  }

  const done = doneFor(setId, caseId);
  const rots = setId === 'F2L' ? F2L_ROTS : [''];
  /* A 2x2 has no centres to say which way up it is. Its bottom layer is lined
     up before or after an EG or PBL algorithm as a matter of course, and an
     algorithm with an x, a B or a d in it finishes with those two layers on a
     different axis — so both layers of any axis may take the final turns. */
  const pres = n === 2 ? LAYER_PAIRS[0] : AUFS;
  const posts = n === 2 ? ANY_PAIR : AUFS;
  for (const rot of rots) {
    for (const pre of pres) {
      for (const post of posts) {
        const seq = [start, pre, rot, alg, post].filter(Boolean).join(' ');
        if (done(faceletsFor(seq, n))) return true;
      }
    }
  }
  return false;
}

/**
 * Facelets of the case, at the angle it should be drawn — cubes only.
 *
 * PLL is turned to the angle every printed sheet uses — the one where the
 * corners look solved. `invert(alg)` on its own lands wherever the alg's U
 * turns leave it. A U turn is free on a permutation case, so pick the one that
 * leaves the most side stickers already home.
 *
 * Everything else is left exactly where the case's own algorithm expects it.
 * There is no free AUF for an OLL — an OLL alg only works from the angle it was
 * written for — so turning the picture to look tidier would be drawing a case
 * the listed algorithm does not solve.
 */
export const caseFacelets = (setId, caseId) => {
  const set = SETS[setId];
  if (puzzleOf(set) !== 'cube') return null;
  const pattern = casePattern(setId, caseId);
  if (pattern == null) return null;
  const n = sizeOf(setId);
  if (set.greySet) return faceletsFor(pattern, n, set.greySet);
  if (set.angle !== 'auf') return faceletsFor(pattern, n);

  let best = null, bestScore = -1;
  for (const auf of AUFS) {
    const f = faceletsFor([pattern, auf].filter(Boolean).join(' '), n);
    let score = 0;
    for (const face of ['R', 'F', 'L', 'B']) {
      for (const s of f[face][0]) if (s === face) score++;
    }
    if (score > bestScore) { bestScore = score; best = f; }
  }
  return best;
};

/** SVG markup of a pyraminx, skewb or square-1 case; null for cubes. */
export function caseSvg(setId, caseId) {
  const set = SETS[setId];
  if (puzzleOf(set) === 'cube') return null;
  const pattern = casePattern(setId, caseId);
  const s = pattern == null ? null : puzzleState(set, pattern);
  return s ? s.svg(set.mirrorBottom) : null;
}

/** Move count in ETM, counting rotations and slices as one move each. */
export const moveCount = (alg) => (parseAlg(alg) || []).length;

/** Move count on whichever puzzle the set is for. */
export const countFor = (setId, alg) => {
  const set = SETS[setId];
  return puzzleOf(set) === 'cube' ? moveCount(alg) : PUZ.countMoves(set.puzzle, alg);
};

/* ---------------------------------------------------------
   Per-user layer — kv keys, cached in memory
   --------------------------------------------------------- */

const orderKey  = (caseId) => 'alglib:order:' + caseId;
const customKey = (caseId) => 'alglib:custom:' + caseId;

/* The trainer needs the user's first-choice alg synchronously, mid-scramble
   generation, so the whole per-user layer is read once at startup and kept in
   memory. It is a few dozen short strings. */
const _order  = new Map();   // caseId -> array of alg strings
const _custom = new Map();   // caseId -> array of { alg, moveCount, notes }
let _loaded = false;

/** Read every stored order/custom entry. Safe to call more than once. */
export async function loadLibraryPrefs() {
  if (_loaded) return;
  _loaded = true;
  /* One scan of the `alglib:` namespace rather than hundreds of point reads —
     this is awaited on the timer's boot path, before the first scramble. */
  const rows = await KV.prefixed('alglib:');
  for (const [key, value] of rows) {
    if (!Array.isArray(value) || !value.length) continue;
    if (key.startsWith('alglib:order:'))  _order.set(key.slice(13), value);
    if (key.startsWith('alglib:custom:')) _custom.set(key.slice(14), value);
  }
}

/**
 * The list the detail view renders: the imported list for the case first, in
 * its own order, then alternates it does not already have, then anything you
 * added — all put into your saved order.
 *
 * Entries you have never seen — a future import adding a fifth alg to a case —
 * land at the end rather than reshuffling a list you already personalised.
 */
export function displayOrder(setId, caseId) {
  const set = SETS[setId];
  const c = caseOf(setId, caseId);
  if (!set || !c) return [];

  const extra = set.extra?.[caseId] || [];
  const base = [
    ...extra,
    ...(set.library[caseId]?.alternates || []).filter(a => !extra.some(e => e.alg === a.alg)),
  ].map(a => ({ ...a, source: 'community' }));
  if (!base.some(a => a.alg === c.alg)) {
    base.push({ alg: c.alg, moveCount: countFor(setId, c.alg), source: 'community' });
  }
  const custom = (_custom.get(caseId) || []).map(a => ({ ...a, source: 'custom' }));

  const all = [...base, ...custom];
  const saved = _order.get(caseId);
  if (!saved) return all;

  const known = new Set(saved);
  return saved.map(alg => all.find(a => a.alg === alg)).filter(Boolean)
    .concat(all.filter(a => !known.has(a.alg)));
}

/**
 * §6.1 — position 1 is not decoration. This is what the trainer inverts to
 * build a scramble for the case, so reordering is how you tell the app which
 * alg you actually drill. Untouched cases fall through to algs.js.
 *
 * On the timer page a set's extra algorithms are not loaded, so the alg you
 * put first may not be in the list this can see. It was verified when it was
 * listed; it is verified again here rather than silently replaced by a
 * different one.
 */
export function preferredAlg(caseId) {
  const saved = _order.get(caseId);
  if (!saved || !saved.length) return null;
  const set = setOf(caseId);
  if (!set) return null;
  const first = displayOrder(set.id, caseId)[0];
  if (first && first.alg !== saved[0] && verifyAlgForCase(set.id, caseId, saved[0])) return saved[0];
  return first ? first.alg : null;
}

/** Persist a drag order. Order is stored as alg strings, not indices. */
export async function saveOrder(caseId, algs) {
  _order.set(caseId, algs.slice());
  await KV.set(orderKey(caseId), algs.slice());
}

/** Drop a personal order, so the case reads in its listed order again. */
export async function resetOrder(caseId) {
  _order.delete(caseId);
  await KV.del(orderKey(caseId));
}

export const hasCustomOrder = (caseId) => _order.has(caseId);

/**
 * Add one of your own algs to a case.
 * Rejects — rather than saving as unverified — anything that does not
 * actually solve the case (§5, §7).
 */
export async function addCustom(setId, caseId, alg) {
  const set = SETS[setId];
  const moves = puzzleOf(set) === 'cube' ? parseAlg(alg) : PUZ.parseMoves(set.puzzle, alg);
  const clean = (moves || []).join(' ');
  if (!clean) return { ok: false, error: 'That is not move notation for this puzzle.' };
  if (displayOrder(setId, caseId).some(a => a.alg === clean)) {
    return { ok: false, error: 'That algorithm is already listed for this case.' };
  }
  if (!verifyAlgForCase(setId, caseId, clean)) {
    return { ok: false, error: 'That does not solve this case — checked on a simulated puzzle.' };
  }
  const list = (_custom.get(caseId) || []).concat({ alg: clean, moveCount: countFor(setId, clean) });
  _custom.set(caseId, list);
  await KV.set(customKey(caseId), list);
  return { ok: true, alg: clean };
}

/** Remove one of your own algs, and forget it in the saved order too. */
export async function removeCustom(caseId, alg) {
  const list = (_custom.get(caseId) || []).filter(a => a.alg !== alg);
  list.length ? _custom.set(caseId, list) : _custom.delete(caseId);
  await (list.length ? KV.set(customKey(caseId), list) : KV.del(customKey(caseId)));

  const ord = _order.get(caseId);
  if (ord && ord.includes(alg)) await saveOrder(caseId, ord.filter(a => a !== alg));
}

/* ---------------------------------------------------------
   Static-file audit (§7.1, §8 step 1)
   --------------------------------------------------------- */

/**
 * Run every shipped algorithm against its case. Returns the failures.
 * `tools/verify-alglibrary.mjs` and `.html` call it.
 */
export function auditLibrary() {
  const bad = [];
  for (const set of Object.values(SETS)) {
    for (const c of set.cases) {
      const listed = [...(set.extra?.[c.id] || []), ...(set.library[c.id]?.alternates || [])];
      for (const a of listed) {
        if (!verifyAlgForCase(set.id, c.id, a.alg)) bad.push({ set: set.id, caseId: c.id, alg: a.alg });
      }
    }
  }
  return bad;
}
