import { t } from './i18n.js';
/* ===========================================================
   Tagda Timer — 2x2 algorithm sets, for the trainer and the library.

   GENERATED by tools/gen-222.mjs. Do not hand-edit.

   Not scraped and not remembered: every case below is an equivalence
   class of real cube states, and every algorithm is a shortest solution
   of that state found by exhaustive search over the whole 3,674,160-state
   group. The generator cross-checks its cube model against js/cubenet.js
   before it will emit anything, and tools/verify-alglibrary.html re-runs
   every algorithm here against its own case in the browser.

   A case is the family of states one algorithm covers, since a U turn
   before the algorithm and a U turn after it are both free. That is why
   CLL is 40 cases here rather than the 42 most sheets print: in the H
   family a half turn of U leaves the twist pattern alone, so two of its
   six pictures are two of the others turned round. The same 624 states
   are covered either way.
   =========================================================== */

export const OLL_222 = [
  { id: "222OLL-Sune", name: "Sune", group: "Orientation", label: t("Sune twist — orient all four corners, wherever they end up"), alg: "F' R F2 U2 R F'" },
  { id: "222OLL-Antisune", name: "Antisune", group: "Orientation", label: t("Antisune twist — orient all four corners, wherever they end up"), alg: "R F' R2 U2 F' R" },
  { id: "222OLL-T", name: "T", group: "Orientation", label: t("T twist — orient all four corners, wherever they end up"), alg: "R U R' U' F' U' F" },
  { id: "222OLL-U", name: "U", group: "Orientation", label: t("U twist — orient all four corners, wherever they end up"), alg: "R U F R' F' R'" },
  { id: "222OLL-L", name: "L", group: "Orientation", label: t("L twist — orient all four corners, wherever they end up"), alg: "F R' F' U' R' U R" },
  { id: "222OLL-Pi", name: "Pi", group: "Orientation", label: t("Pi twist — orient all four corners, wherever they end up"), alg: "F R F2 U' F2 R F'" },
  { id: "222OLL-H", name: "H", group: "Orientation", label: t("H twist — orient all four corners, wherever they end up"), alg: "F2 U2 F U2 F2" },
];

export const PBL_222 = [
  { id: "222PBL-solved-adjacent-swap-1", name: t("solved / adjacent swap"), group: t("bottom solved"), label: t("bottom solved · top adjacent swap"), alg: "R2 F2 R' U' R F2 R' U R'" },
  { id: "222PBL-solved-diagonal-swap-2", name: t("solved / diagonal swap"), group: t("bottom solved"), label: t("bottom solved · top diagonal swap"), alg: "R2 U' R U F R2 F U' R' U F'" },
  { id: "222PBL-adjacent-swap-solved-3", name: t("adjacent swap / solved"), group: t("bottom adjacent swap"), label: t("bottom adjacent swap · top solved"), alg: "R' U F' R2 F R' F' R2 F2" },
  { id: "222PBL-adjacent-swap-adjacent-swap-4", name: t("adjacent swap / adjacent swap"), group: t("bottom adjacent swap"), label: t("bottom adjacent swap · top adjacent swap"), alg: "R2 U F2 U2 R2 U R2" },
  { id: "222PBL-adjacent-swap-diagonal-swap-5", name: t("adjacent swap / diagonal swap"), group: t("bottom adjacent swap"), label: t("bottom adjacent swap · top diagonal swap"), alg: "R' F U' R2 U F' R" },
  { id: "222PBL-diagonal-swap-solved-6", name: t("diagonal swap / solved"), group: t("bottom diagonal swap"), label: t("bottom diagonal swap · top solved"), alg: "R U' R U R' F2 R' U' R' U F2" },
  { id: "222PBL-diagonal-swap-adjacent-swap-7", name: t("diagonal swap / adjacent swap"), group: t("bottom diagonal swap"), label: t("bottom diagonal swap · top adjacent swap"), alg: "R U' R F2 R' U R'" },
  { id: "222PBL-diagonal-swap-diagonal-swap-8", name: t("diagonal swap / diagonal swap"), group: t("bottom diagonal swap"), label: t("bottom diagonal swap · top diagonal swap"), alg: "R2 F2 R2" },
];

export const CLL_222 = [
  { id: "CLL-Sune-1", name: t("Sune 1"), group: "Sune", label: t("Sune twist · top corners solved"), alg: "F R F2 R' U2 R F" },
  { id: "CLL-Sune-2", name: t("Sune 2"), group: "Sune", label: t("Sune twist · top corners adjacent swap"), alg: "R F' U' F R' U' R" },
  { id: "CLL-Sune-3", name: t("Sune 3"), group: "Sune", label: t("Sune twist · top corners adjacent swap"), alg: "R U' R' F U2 F U2 F'" },
  { id: "CLL-Sune-4", name: t("Sune 4"), group: "Sune", label: t("Sune twist · top corners adjacent swap"), alg: "R' U2 R U2 R F' U' F" },
  { id: "CLL-Sune-5", name: t("Sune 5"), group: "Sune", label: t("Sune twist · top corners diagonal swap"), alg: "R2 U' F' U2 F U' R2 U R'" },
  { id: "CLL-Sune-6", name: t("Sune 6"), group: "Sune", label: t("Sune twist · top corners adjacent swap"), alg: "F2 R U R2 F R2 U' R' F2" },
  { id: "CLL-Antisune-1", name: t("Antisune 1"), group: "Antisune", label: t("Antisune twist · top corners adjacent swap"), alg: "R' F R F' R U R'" },
  { id: "CLL-Antisune-2", name: t("Antisune 2"), group: "Antisune", label: t("Antisune twist · top corners solved"), alg: "R' F' R U' R' F2 R" },
  { id: "CLL-Antisune-3", name: t("Antisune 3"), group: "Antisune", label: t("Antisune twist · top corners adjacent swap"), alg: "F U2 F' U2 F' R U R'" },
  { id: "CLL-Antisune-4", name: t("Antisune 4"), group: "Antisune", label: t("Antisune twist · top corners adjacent swap"), alg: "F' U F R' U2 R' U2 R" },
  { id: "CLL-Antisune-5", name: t("Antisune 5"), group: "Antisune", label: t("Antisune twist · top corners diagonal swap"), alg: "R U' R2 U F' U2 F U R2" },
  { id: "CLL-Antisune-6", name: t("Antisune 6"), group: "Antisune", label: t("Antisune twist · top corners adjacent swap"), alg: "F2 R U F2 R' F2 U' R' F2" },
  { id: "CLL-T-1", name: "T 1", group: "T", label: t("T twist · top corners adjacent swap"), alg: "F R F' U' R' U' R" },
  { id: "CLL-T-2", name: "T 2", group: "T", label: t("T twist · top corners adjacent swap"), alg: "F' R' U R U F R'" },
  { id: "CLL-T-3", name: "T 3", group: "T", label: t("T twist · top corners adjacent swap"), alg: "R F2 R U2 R' F2 R F2 R2" },
  { id: "CLL-T-4", name: "T 4", group: "T", label: t("T twist · top corners solved"), alg: "F' R U' R U' F U R2 F2" },
  { id: "CLL-T-5", name: "T 5", group: "T", label: t("T twist · top corners adjacent swap"), alg: "R' U' R U' F2 U R' U' F2" },
  { id: "CLL-T-6", name: "T 6", group: "T", label: t("T twist · top corners diagonal swap"), alg: "R F R F' U' R U2 R' U2 R2" },
  { id: "CLL-U-1", name: "U 1", group: "U", label: t("U twist · top corners diagonal swap"), alg: "F R U R' U' F'" },
  { id: "CLL-U-2", name: "U 2", group: "U", label: t("U twist · top corners adjacent swap"), alg: "R2 U R' F2 R F' R' F2 R'" },
  { id: "CLL-U-3", name: "U 3", group: "U", label: t("U twist · top corners adjacent swap"), alg: "F2 R2 F R2 F' U2 F R2 F" },
  { id: "CLL-U-4", name: "U 4", group: "U", label: t("U twist · top corners adjacent swap"), alg: "F2 U' R F R2 F R F2 R'" },
  { id: "CLL-U-5", name: "U 5", group: "U", label: t("U twist · top corners solved"), alg: "R U' F U' F R F2 U2 R'" },
  { id: "CLL-U-6", name: "U 6", group: "U", label: t("U twist · top corners adjacent swap"), alg: "R2 U2 R' F' R' U2 R' U2 R' F'" },
  { id: "CLL-L-1", name: "L 1", group: "L", label: t("L twist · top corners adjacent swap"), alg: "R' U R U F R' F'" },
  { id: "CLL-L-2", name: "L 2", group: "L", label: t("L twist · top corners adjacent swap"), alg: "R F' U' R' U' R F" },
  { id: "CLL-L-3", name: "L 3", group: "L", label: t("L twist · top corners adjacent swap"), alg: "R F2 R' F' R2 F' R' U F2" },
  { id: "CLL-L-4", name: "L 4", group: "L", label: t("L twist · top corners adjacent swap"), alg: "R F2 R F R' F2 R U' R2" },
  { id: "CLL-L-5", name: "L 5", group: "L", label: t("L twist · top corners diagonal swap"), alg: "F U2 F' R U F2 U2 R F" },
  { id: "CLL-L-6", name: "L 6", group: "L", label: t("L twist · top corners solved"), alg: "R2 U F' R2 F U2 F' U R2" },
  { id: "CLL-Pi-1", name: "Pi 1", group: "Pi", label: t("Pi twist · top corners adjacent swap"), alg: "R2 U2 F' U' R2 U' R2 U' F'" },
  { id: "CLL-Pi-2", name: "Pi 2", group: "Pi", label: t("Pi twist · top corners diagonal swap"), alg: "F2 U R2 F' R2 F R2 U' F2" },
  { id: "CLL-Pi-3", name: "Pi 3", group: "Pi", label: t("Pi twist · top corners solved"), alg: "R F' U2 F U2 F R2 F' R" },
  { id: "CLL-Pi-4", name: "Pi 4", group: "Pi", label: t("Pi twist · top corners adjacent swap"), alg: "R U2 R' F2 U R' F2 R U F'" },
  { id: "CLL-Pi-5", name: "Pi 5", group: "Pi", label: t("Pi twist · top corners adjacent swap"), alg: "F' U F R' U2 F2 U R' U' F2" },
  { id: "CLL-Pi-6", name: "Pi 6", group: "Pi", label: t("Pi twist · top corners adjacent swap"), alg: "R' F2 R F2 U' R U2 R' U' F" },
  { id: "CLL-H-1", name: "H 1", group: "H", label: t("H twist · top corners solved"), alg: "F2 U2 F' U2 F2" },
  { id: "CLL-H-2", name: "H 2", group: "H", label: t("H twist · top corners diagonal swap"), alg: "R2 F R2 F2 U2 F R2" },
  { id: "CLL-H-3", name: "H 3", group: "H", label: t("H twist · top corners adjacent swap"), alg: "F U R2 U R2 U F U2 R2" },
  { id: "CLL-H-4", name: "H 4", group: "H", label: t("H twist · top corners adjacent swap"), alg: "F2 U R U R' F2 U2 F U' F" },
];

export const EG1_222 = [
  { id: "EG1-Sune-1", name: t("Sune 1"), group: "Sune", label: t("Sune twist · top corners solved"), alg: "F' R F2 U2 R F'" },
  { id: "EG1-Sune-2", name: t("Sune 2"), group: "Sune", label: t("Sune twist · top corners adjacent swap"), alg: "F2 U' R F' U R' F R2" },
  { id: "EG1-Sune-3", name: t("Sune 3"), group: "Sune", label: t("Sune twist · top corners diagonal swap"), alg: "F' U R2 F2 U R F2 R2" },
  { id: "EG1-Sune-4", name: t("Sune 4"), group: "Sune", label: t("Sune twist · top corners adjacent swap"), alg: "R U F2 U2 R F' U' F2" },
  { id: "EG1-Sune-5", name: t("Sune 5"), group: "Sune", label: t("Sune twist · top corners adjacent swap"), alg: "F U2 F U' F2 R U2 R'" },
  { id: "EG1-Sune-6", name: t("Sune 6"), group: "Sune", label: t("Sune twist · top corners adjacent swap"), alg: "F R2 F2 U' R' F2 R' U R'" },
  { id: "EG1-Antisune-1", name: t("Antisune 1"), group: "Antisune", label: t("Antisune twist · top corners solved"), alg: "F R' U2 F2 R' F" },
  { id: "EG1-Antisune-2", name: t("Antisune 2"), group: "Antisune", label: t("Antisune twist · top corners adjacent swap"), alg: "R2 F' R U' F R' U F2" },
  { id: "EG1-Antisune-3", name: t("Antisune 3"), group: "Antisune", label: t("Antisune twist · top corners diagonal swap"), alg: "F U' R F2 R U2 F' R" },
  { id: "EG1-Antisune-4", name: t("Antisune 4"), group: "Antisune", label: t("Antisune twist · top corners adjacent swap"), alg: "F2 U F' U R' F R F2" },
  { id: "EG1-Antisune-5", name: t("Antisune 5"), group: "Antisune", label: t("Antisune twist · top corners adjacent swap"), alg: "F2 R U R' U F' U F2" },
  { id: "EG1-Antisune-6", name: t("Antisune 6"), group: "Antisune", label: t("Antisune twist · top corners adjacent swap"), alg: "R U' R F2 R U F2 R2 F'" },
  { id: "EG1-T-1", name: "T 1", group: "T", label: t("T twist · top corners adjacent swap"), alg: "F' R F R2 F R U2 R" },
  { id: "EG1-T-2", name: "T 2", group: "T", label: t("T twist · top corners adjacent swap"), alg: "F R' U' F2 U' R' F2 R'" },
  { id: "EG1-T-3", name: "T 3", group: "T", label: t("T twist · top corners diagonal swap"), alg: "R F U2 F' U R2 F' R" },
  { id: "EG1-T-4", name: "T 4", group: "T", label: t("T twist · top corners solved"), alg: "R2 F2 U' F' U2 F' R2 F'" },
  { id: "EG1-T-5", name: "T 5", group: "T", label: t("T twist · top corners adjacent swap"), alg: "R2 F' R F R' U' R' U2 F2" },
  { id: "EG1-T-6", name: "T 6", group: "T", label: t("T twist · top corners adjacent swap"), alg: "F R' F2 R F U2 R' F' R" },
  { id: "EG1-U-1", name: "U 1", group: "U", label: t("U twist · top corners adjacent swap"), alg: "F' U2 R U2 R' U2 F" },
  { id: "EG1-U-2", name: "U 2", group: "U", label: t("U twist · top corners diagonal swap"), alg: "F2 U F U2 F U2 F" },
  { id: "EG1-U-3", name: "U 3", group: "U", label: t("U twist · top corners solved"), alg: "F' R2 F' R2 F' U' F2 R2" },
  { id: "EG1-U-4", name: "U 4", group: "U", label: t("U twist · top corners adjacent swap"), alg: "F' U R U2 R' F U2 F" },
  { id: "EG1-U-5", name: "U 5", group: "U", label: t("U twist · top corners adjacent swap"), alg: "R U2 F' R U R2 U' F" },
  { id: "EG1-U-6", name: "U 6", group: "U", label: t("U twist · top corners adjacent swap"), alg: "F2 U2 R U R F' R' F R2" },
  { id: "EG1-L-1", name: "L 1", group: "L", label: t("L twist · top corners adjacent swap"), alg: "R' U2 R' F' R2 F' R' F" },
  { id: "EG1-L-2", name: "L 2", group: "L", label: t("L twist · top corners adjacent swap"), alg: "R F2 R U F2 U R F'" },
  { id: "EG1-L-3", name: "L 3", group: "L", label: t("L twist · top corners adjacent swap"), alg: "F U2 F2 U R U2 R' F2" },
  { id: "EG1-L-4", name: "L 4", group: "L", label: t("L twist · top corners adjacent swap"), alg: "F2 U R U2 F2 R U2 R" },
  { id: "EG1-L-5", name: "L 5", group: "L", label: t("L twist · top corners diagonal swap"), alg: "F' R2 U2 R F2 R' U2 R2 F" },
  { id: "EG1-L-6", name: "L 6", group: "L", label: t("L twist · top corners solved"), alg: "F2 R' U F' R U' R2 U' F2" },
  { id: "EG1-Pi-1", name: "Pi 1", group: "Pi", label: t("Pi twist · top corners diagonal swap"), alg: "R U R2 F' R2 U R'" },
  { id: "EG1-Pi-2", name: "Pi 2", group: "Pi", label: t("Pi twist · top corners adjacent swap"), alg: "F R' F U' F2 R U R" },
  { id: "EG1-Pi-3", name: "Pi 3", group: "Pi", label: t("Pi twist · top corners adjacent swap"), alg: "F R' F R U' F U2 F" },
  { id: "EG1-Pi-4", name: "Pi 4", group: "Pi", label: t("Pi twist · top corners solved"), alg: "F' R' U2 R' U2 F2 R F" },
  { id: "EG1-Pi-5", name: "Pi 5", group: "Pi", label: t("Pi twist · top corners adjacent swap"), alg: "R' F2 U2 R' U F2 R U R" },
  { id: "EG1-Pi-6", name: "Pi 6", group: "Pi", label: t("Pi twist · top corners adjacent swap"), alg: "R' U' R' F2 U' R U2 F2 R" },
  { id: "EG1-H-1", name: "H 1", group: "H", label: t("H twist · top corners adjacent swap"), alg: "R' U' R' F2 U F' R F'" },
  { id: "EG1-H-2", name: "H 2", group: "H", label: t("H twist · top corners adjacent swap"), alg: "F U2 F U' R U R' F" },
  { id: "EG1-H-3", name: "H 3", group: "H", label: t("H twist · top corners solved"), alg: "F' R2 F' R F R' U R'" },
  { id: "EG1-H-4", name: "H 4", group: "H", label: t("H twist · top corners diagonal swap"), alg: "F' R U2 R2 F' R F' U2 F" },
];

export const EG2_222 = [
  { id: "EG2-Sune-1", name: t("Sune 1"), group: "Sune", label: t("Sune twist · top corners adjacent swap"), alg: "F U R F' U' R2 F R2" },
  { id: "EG2-Sune-2", name: t("Sune 2"), group: "Sune", label: t("Sune twist · top corners adjacent swap"), alg: "R2 F' U2 R U' R U F" },
  { id: "EG2-Sune-3", name: t("Sune 3"), group: "Sune", label: t("Sune twist · top corners adjacent swap"), alg: "R U' R F' U2 F' R2 F" },
  { id: "EG2-Sune-4", name: t("Sune 4"), group: "Sune", label: t("Sune twist · top corners adjacent swap"), alg: "R' F R' F R2 U' F U' F'" },
  { id: "EG2-Sune-5", name: t("Sune 5"), group: "Sune", label: t("Sune twist · top corners diagonal swap"), alg: "F2 U F U' R2 F2 R' U2 R" },
  { id: "EG2-Sune-6", name: t("Sune 6"), group: "Sune", label: t("Sune twist · top corners solved"), alg: "F R U' R2 U R' U' F U2 R2" },
  { id: "EG2-Antisune-1", name: t("Antisune 1"), group: "Antisune", label: t("Antisune twist · top corners adjacent swap"), alg: "R2 F' R2 U F R' U' F'" },
  { id: "EG2-Antisune-2", name: t("Antisune 2"), group: "Antisune", label: t("Antisune twist · top corners adjacent swap"), alg: "F' U' R' U R' U2 F R2" },
  { id: "EG2-Antisune-3", name: t("Antisune 3"), group: "Antisune", label: t("Antisune twist · top corners adjacent swap"), alg: "F' R2 F U2 F R' U R'" },
  { id: "EG2-Antisune-4", name: t("Antisune 4"), group: "Antisune", label: t("Antisune twist · top corners adjacent swap"), alg: "F U F' U R2 F' R F' R" },
  { id: "EG2-Antisune-5", name: t("Antisune 5"), group: "Antisune", label: t("Antisune twist · top corners diagonal swap"), alg: "R' F' R2 F U2 F' R F2 R2" },
  { id: "EG2-Antisune-6", name: t("Antisune 6"), group: "Antisune", label: t("Antisune twist · top corners solved"), alg: "R2 U2 F' R' U R2 U' R U F'" },
  { id: "EG2-T-1", name: "T 1", group: "T", label: t("T twist · top corners adjacent swap"), alg: "F' R2 F' U2 F R2 F" },
  { id: "EG2-T-2", name: "T 2", group: "T", label: t("T twist · top corners adjacent swap"), alg: "F U' R2 U' R' U R2 F'" },
  { id: "EG2-T-3", name: "T 3", group: "T", label: t("T twist · top corners adjacent swap"), alg: "R' U F2 U F U' F2 R" },
  { id: "EG2-T-4", name: "T 4", group: "T", label: t("T twist · top corners diagonal swap"), alg: "F R' F R' U R' U' F2" },
  { id: "EG2-T-5", name: "T 5", group: "T", label: t("T twist · top corners solved"), alg: "F2 R2 F' R U R' U' F'" },
  { id: "EG2-T-6", name: "T 6", group: "T", label: t("T twist · top corners adjacent swap"), alg: "F R U2 R2 U R U' R U' F'" },
  { id: "EG2-U-1", name: "U 1", group: "U", label: t("U twist · top corners solved"), alg: "R U F R' F' R F2 R2" },
  { id: "EG2-U-2", name: "U 2", group: "U", label: t("U twist · top corners adjacent swap"), alg: "R' F' U' R U2 R' U F R" },
  { id: "EG2-U-3", name: "U 3", group: "U", label: t("U twist · top corners adjacent swap"), alg: "F' U2 R U R F' R F' R'" },
  { id: "EG2-U-4", name: "U 4", group: "U", label: t("U twist · top corners adjacent swap"), alg: "R U2 F' U' F' R F' R F" },
  { id: "EG2-U-5", name: "U 5", group: "U", label: t("U twist · top corners adjacent swap"), alg: "F U R' U R' U R2 U2 R F'" },
  { id: "EG2-U-6", name: "U 6", group: "U", label: t("U twist · top corners diagonal swap"), alg: "R2 U2 R U R' U F' R U' R" },
  { id: "EG2-L-1", name: "L 1", group: "L", label: t("L twist · top corners adjacent swap"), alg: "F R2 U' R U R2 U F'" },
  { id: "EG2-L-2", name: "L 2", group: "L", label: t("L twist · top corners adjacent swap"), alg: "R' F2 U F' U' F2 U' R" },
  { id: "EG2-L-3", name: "L 3", group: "L", label: t("L twist · top corners adjacent swap"), alg: "R F R' F R' U' R' U2 F" },
  { id: "EG2-L-4", name: "L 4", group: "L", label: t("L twist · top corners adjacent swap"), alg: "F' R' F R' F U F U2 R'" },
  { id: "EG2-L-5", name: "L 5", group: "L", label: t("L twist · top corners diagonal swap"), alg: "F' U F U2 R2 F2 R' U2 R'" },
  { id: "EG2-L-6", name: "L 6", group: "L", label: t("L twist · top corners solved"), alg: "R U' R F' R' F' U R2 U' R" },
  { id: "EG2-Pi-1", name: "Pi 1", group: "Pi", label: t("Pi twist · top corners diagonal swap"), alg: "R F2 R2 F U F2 U2 F" },
  { id: "EG2-Pi-2", name: "Pi 2", group: "Pi", label: t("Pi twist · top corners adjacent swap"), alg: "F R2 F R2 F2 U' F U' F'" },
  { id: "EG2-Pi-3", name: "Pi 3", group: "Pi", label: t("Pi twist · top corners adjacent swap"), alg: "F R' U2 F' R2 F' R F2 R" },
  { id: "EG2-Pi-4", name: "Pi 4", group: "Pi", label: t("Pi twist · top corners adjacent swap"), alg: "F U F R2 F2 U' F R2 F'" },
  { id: "EG2-Pi-5", name: "Pi 5", group: "Pi", label: t("Pi twist · top corners adjacent swap"), alg: "R' U F' R U R' U2 F2 R" },
  { id: "EG2-Pi-6", name: "Pi 6", group: "Pi", label: t("Pi twist · top corners solved"), alg: "F R' F2 R' F2 U' R2 U' R" },
  { id: "EG2-H-1", name: "H 1", group: "H", label: t("H twist · top corners diagonal swap"), alg: "F2 R2 U2 F' U2 F2" },
  { id: "EG2-H-2", name: "H 2", group: "H", label: t("H twist · top corners solved"), alg: "R2 F U2 F2 R2 F' R2" },
  { id: "EG2-H-3", name: "H 3", group: "H", label: t("H twist · top corners adjacent swap"), alg: "R' F2 R' F R2 F U2 R F'" },
  { id: "EG2-H-4", name: "H 4", group: "H", label: t("H twist · top corners adjacent swap"), alg: "F' U2 R2 F R' U' R U' F" },
];

