/* ===========================================================
   Tagda Timer — the 472 ZBLL cases, as a trainer set.

   js/algsets.js already carries the whole ZBLL library — every
   spelling of every case — but that is 100kB the reconstruction panel
   loads on demand and the timer should never pay for at startup. A
   trainer needs one alg per case and nothing else, so this is that:
   the shortest verified spelling of each of the 472, rewritten into
   plain outer-face turns so that inverting it into a scramble is
   exact (a reversed token list is not an inverse if a rotation in it
   changes what the letters after it mean).

   Checked against js/cube3.js, all 472: the alg solves the position
   it is filed under, F2L is untouched, and every edge is already
   oriented — which is what makes a case ZBLL rather than plain PLL.

   Families are the usual seven, by what the corners are doing:
   T, U, L, H, Pi, S (Sune) and AS (Antisune).
   =========================================================== */

const zb = (family, cases) => cases.map(([n, alg]) =>
  ({ id: `ZBLL-${family}-${n}`, name: `${family} ${n}`, label: ZBLL_FAMILIES[family], group: family, alg }));

export const ZBLL_FAMILIES = {
  T: 'T set', U: 'U set', L: 'L set', H: 'H set', Pi: 'Pi set', S: 'Sune set', AS: 'Antisune set',
};

export const ZBLL_SET = [
  ...zb('T', [
    ["1", "B' U' B U' B' U' B U2 F' B' U B U' F"],
    ["2", "R2 U2 R' U R U' R U2 R U L' U R U' L"],
    ["3", "L' U' L' D' L U' L' R B2 R' D L2"],
    ["4", "B L2 D L' U' L D' L2 U' L U2 L' U' B'"],
    ["5", "R B U B' U' B U B' U' R' B U B' U' B' R B R'"],
    ["6", "L F L' B L F' L' B'"],
    ["7", "R' U2 R F U' R' U R U F' R' U R"],
    ["8", "F' U' F U F' U F B' U F' U' F B"],
    ["9", "R U B U2 B' U B U B' R'"],
    ["10", "B U B' U' B' R' B U2 B U2 B' R"],
    ["11", "L U F' U' F L' F' U' F U F' U F"],
    ["12", "F' U F U F' U' F' D' F U2 F' D F U F"],
    ["13", "R U R D R' U R L' B2 L D' R2"],
    ["14", "L' U' L U L U F' L' B D L' D' B' F"],
    ["15", "B U B' U B U B' U2 F B U' B' U F'"],
    ["16", "B L U L' U' L' B' U2 L U L U' L2 U2 L"],
    ["17", "B L F' L' B' L F L'"],
    ["18", "R' U' R U' R2 F' R U R U' R' F U R U' R' U2 R"],
    ["19", "U2 R U R D R' U2 R D' R' U' R' U R U' R' U' R U' R'"],
    ["20", "B L F' L' F L' F' B L' F L B2"],
    ["21", "F U2 F' U2 F' L F U F U' F' L'"],
    ["22", "L' U' B' U2 B U L F U' F'"],
    ["23", "F U' F' U' F U F D F' U2 F D' F' U' F'"],
    ["24", "L R' U L' U' R U L U L' U' L U' L'"],
    ["25", "R' U R U2 L' R' U R U' L"],
    ["26", "B U B2 R B R' B U' B' R' U R"],
    ["27", "L U' L' U2 R L U' L' U R'"],
    ["28", "F' U' F' D' F U F' D F U2 F U F' U F"],
    ["29", "L' B' R' U2 R U' R' U2 R2 B' R' B2 L"],
    ["30", "L' B2 R B R2 U2 R U R' U2 R B L"],
    ["31", "R B' R D2 L' F L D2 R2 B"],
    ["32", "B L U' L' B' F R' U R F' U L2 B L B' L"],
    ["33", "L' U' L U' L' U L B U' L' U2 L U B'"],
    ["34", "R U R' U R U' R' U' L' U2 R U2 R' U2 L"],
    ["35", "F U' R' U2 R U F' R' U' R U R' U R"],
    ["36", "B' U' R' U2 R U B L U L' U' L U' L'"],
    ["37", "R' D' R U R' D R2 U R' U2 R U' R' U' R U' R'"],
    ["38", "F U F2 D' F U2 F' D F U2 F U F' U' F U' F'"],
    ["39", "B' U' B U' R U' B' U B U R' B' U B"],
    ["40", "R' U2 R' D' R U2 R' D R2 U' R' U2 R U R' U R"],
    ["41", "F' L2 F' R2 F L2 F' R2 F2"],
    ["42", "F R2 F L2 F' R2 F L2 F2"],
    ["43", "B L U L' U' L U' L' U' L U L' B'"],
    ["44", "F' U' F U R' F R2 U R' U' R' F' R2 U R'"],
    ["45", "B' U' B' D' B U B' D B U' B U' B' U2 B"],
    ["46", "B U B' U B' D' B U' B' D B U B U2 B'"],
    ["47", "L F R' F' L' F R F' R' U2 R U R' U R"],
    ["48", "R' L U L U' R U L' U L' U' L U' L'"],
    ["49", "B' U' B U B' U' B2 D B' U B D' B' U2 B' U B"],
    ["50", "R U' R' U R U R' U' R U R' U R' D' R U R' D R"],
    ["51", "B U' B2 D' F R2 F' D B2 U' B' U' B U' B'"],
    ["52", "B U2 R U' L U R' U L' U' B' R' U R"],
    ["53", "R2 D L' D' R' D L D' B L' B' R' B L B'"],
    ["54", "L2 B L U L' U' L' B' L' U' L2 U2 L U2 L"],
    ["55", "L U' L2 D' R B2 R' D L2 U L'"],
    ["56", "R' U R2 D L' B2 L D' R2 U' R"],
    ["57", "R' U' R U2 R D R' U' R D' R2 U R U' R' U R"],
    ["58", "B' D' B U' B' D B U' B U' B' U B U' B' U' B U B'"],
    ["59", "B U B' U' B U B2 D' B U' B' D B U2 B U' B'"],
    ["60", "B U B' U B U B2 D' F R2 F' D B2 U B'"],
    ["61", "L U' L' U2 L U L' U2 L U L' U L U' L'"],
    ["62", "F U F' U F U2 F' U' F U2 F' U' F U' F'"],
    ["63", "F U F' U F U' F' U F' U' F2 U' F2 U2 F"],
    ["64", "R U2 R' U' R U' R' U R U R' U R U2 R'"],
    ["65", "F' U' F U' F' U F U' F U F2 U F2 U2 F'"],
    ["66", "L' U2 L U L' U L U' L' U' L U' L' U2 L"],
    ["67", "F' U' F2 U F2 U F2 U2 F' U F' U F"],
    ["68", "F U F2 U' F2 U' F2 U2 F U' F U' F'"],
    ["69", "R U2 R' U' R U' R2 U2 R U R' U R"],
    ["70", "L' U2 L U L' U L2 U2 L' U' L U' L'"],
    ["71", "R' U R U2 R' U' R U' R U R' U' R' U' R U R U' R'"],
    ["72", "F U F' U F U2 F' U2 F' U' F U' F' U2 F"],
  ]),
  ...zb('U', [
    ["1", "R U' R' U' R U2 R' U' R' D' R U2 R' D R"],
    ["2", "F U2 F D F' U2 F D' F' U2 F' U' F U' F'"],
    ["3", "L2 D R' F2 R D' L' U2 L'"],
    ["4", "B U B2 D' B U B' D B2 U2 B'"],
    ["5", "F U2 F2 D' F U2 F' D F2 U' F' U2 F U2 F'"],
    ["6", "L2 D L' U2 L D' L' U2 L'"],
    ["7", "L' D' R B2 R' D L U2 L U' L' U' L U' L'"],
    ["8", "L' U L D' L U L' D L2 U' L U L U2 L"],
    ["9", "B U L2 U2 L2 B2 D' B U' B2 D B2"],
    ["10", "F2 D' F U' F' D F2 U F' U F U2 F' U F U2 F' U' F"],
    ["11", "B' R B R' U B' D' F R' F' D U' R' U R B"],
    ["12", "F U' F' U F U F' U2 F' D' F U F' D F2 U F'"],
    ["13", "R2 D' L F2 L' D R U2 R"],
    ["14", "B2 D' B U' B' D B2 U' B' U2 B"],
    ["15", "L' U L U L' U2 L U L D L' U2 L D' L'"],
    ["16", "F' U2 F' D' F U2 F' D F U2 F U F' U F"],
    ["17", "R2 D' R U2 R' D R U2 R"],
    ["18", "F' U2 F2 D F' U2 F D' F2 U F U2 F' U2 F"],
    ["19", "F' U F U F' U2 F U2 R U' R' U2 R U' R'"],
    ["20", "R U' R2 U' R2 F' R U R' U' R' F U2 R'"],
    ["21", "R2 D' R U2 R' U' D R' U' R2 U R U R2"],
    ["22", "L' D L U' L2 D R F2 R D R2 D L2"],
    ["23", "F' U F U' F' U' F U2 F D F' U' F D' F2 U' F"],
    ["24", "F U R U' R D R' U' R D' R2 U R U R' F'"],
    ["25", "R U' R2 U' R2 U R' F' R U R2 U' R' F R2"],
    ["26", "L2 B2 L B2 L U' L' U R' U R U' L"],
    ["27", "L2 F U B L2 F2 D F D' F L2 B' F' L2"],
    ["28", "R2 B2 R' B2 R' U R U' L U' L' U R'"],
    ["29", "L U F2 D' F U' F' D F2 L' F' U F"],
    ["30", "F' U' F L F2 D' F U F' D F2 U' L'"],
    ["31", "F U R U' R' F' B L B' R' B U L' U' B' R"],
    ["32", "F2 L' F U F' U' F' L F2 U' F' U2 F2 U F' U F"],
    ["33", "R U B U2 B' U B U B2 R' F R B R' F'"],
    ["34", "B U B' U B U2 B' U B U2 B D B' U2 B D' B2"],
    ["35", "B L F' L' B' L F2 U' F' U' F U2 F' U' L'"],
    ["36", "R2 F R U R U' R' F' R U' R2 D' R U R' D R2"],
    ["37", "L U L' U L U L' U2 L U' L2 D' L U' L' D L"],
    ["38", "R U R' U R U' R' U2 R' D' R U2 R' D R2 U' R'"],
    ["39", "R' U' R F U' R' U' R U F' U R' U R"],
    ["40", "B2 D' B U2 B' D B U2 B U B' U' B U' B' U2 B"],
    ["41", "R2 F2 R' B2 R F2 R' B2 R'"],
    ["42", "L2 F2 L B2 L' F2 L B2 L"],
    ["43", "F R U' R' U R U R' U R U' R' F'"],
    ["44", "B U2 R B U B U' B U B2 U' R' U2 B'"],
    ["45", "R U R' U R' D' R U2 R' D R2 U' R' U2 R U2 R'"],
    ["46", "F U' F' U' F U' F' U F' D' F U F' D F2 U F'"],
    ["47", "R' U2 R U R' U R' D' R U' R' D R U R"],
    ["48", "L U2 L' U' L U' L D L' U L D' L' U' L'"],
    ["49", "R' D R2 U' R' U' R U2 R2 D' R"],
    ["50", "L F U F' U' F U F' U' L' U' F' L' U' L U F"],
    ["51", "R U R' L' U2 R U' R' U' R U' R' L"],
    ["52", "R2 D' R U R' D R U R U' R' U' R"],
    ["53", "F U R U2 R' U R U R' U R U2 R' U R U R' F'"],
    ["54", "B L F' L' B' F U F U' F' L F U F' U' L'"],
    ["55", "B L2 F2 D F D' L2 B' F U F U' F'"],
    ["56", "B' D B2 U' B' U B U2 B' U' B U B2 D' B"],
    ["57", "L U2 L' F' U L U L' U' F"],
    ["58", "L' R L' R L' R F R' F' D' F D R2 F R' F R F2 L'"],
    ["59", "L' U L U L' U' L' D' L U' L' D L2"],
    ["60", "R' L U L' U L U L' U2 L R U' L'"],
    ["61", "F' U' F U F' U F U2 F' U F U2 F' U' F"],
    ["62", "F U F' U' F U' F' U2 F U' F' U2 F U F'"],
    ["63", "B U2 B' U' B U' B' U' B U B' U B U2 B'"],
    ["64", "B' U2 B2 U B2 U B U' B U B' U' B U' B'"],
    ["65", "B' U2 B U B' U B U B' U' B U' B' U2 B"],
    ["66", "B U2 B2 U' B2 U' B' U B' U' B U B' U B"],
    ["67", "L U L' U L' U2 L2 U L2 U L2 U' L'"],
    ["68", "R' U' R U' R U2 R2 U' R2 U' R2 U R"],
    ["69", "R' U' R U' R' U2 R2 U R' U R U2 R'"],
    ["70", "L U L' U L U2 L2 U' L U' L' U2 L"],
    ["71", "R U R' U' R U' R U2 R2 U' R U R' U' R2 U' R2"],
    ["72", "B U2 B' U' B U' B' F' U2 F U F' U F"],
  ]),
  ...zb('L', [
    ["1", "F' U' F U' F' U2 F' D' F U2 F' D F U2 F"],
    ["2", "R' U' R U' R' U2 R U' R U' L' U R' U' L"],
    ["3", "F' U2 F U F2 D' F U F' D F2"],
    ["4", "R' U2 R' D' L F2 L' D R2"],
    ["5", "R' U2 R U2 R' U' R2 D R' U2 R D' R2 U2 R"],
    ["6", "R' U2 R' D' R U2 R' D R2"],
    ["7", "F' U' F U' F' U' F U2 F D B' R2 B D' F'"],
    ["8", "B U2 B U B U' B2 D B' U B D' B U B'"],
    ["9", "F' U' F2 D B' R2 B D' F2 U F U F' U2 F"],
    ["10", "R' U R U' R' U F' R U2 R' U2 R' F R2"],
    ["11", "F R' U2 R' U' B U' B' R' U R' U' R' F'"],
    ["12", "L F U' F' U' F2 D F' U F D' F' U F' U' L'"],
    ["13", "R2 D' R U2 R' D R2 U R2 F' R U R U' R' F R"],
    ["14", "B U' B' U B U' B' U' B U B2 D' B U' B' D B"],
    ["15", "L U' R U R' L' U2 R U' R' U' R U' R'"],
    ["16", "L U' R U L' U R U2 R U' R U R' U2 R2"],
    ["17", "R' U2 R U R' U' F' R U R' U' R' F R2 U R' U R"],
    ["18", "R B' R' F R B R' F'"],
    ["19", "R U R' B' U R U R' U' B R U2 R'"],
    ["20", "L R U' R' U L' R U R' U R U' R'"],
    ["21", "B U B D B' U2 B D' B' U' B' U B U B'"],
    ["22", "R U R' U R U' R' U' L' U R U' R' L"],
    ["23", "R B U B' U' B' R' B U2 B U2 B'"],
    ["24", "F' L' U L U L' U2 L U F"],
    ["25", "F2 D' B L2 B' F U F' D F U F"],
    ["26", "F' U F U2 F' B' U F U B U B' U B"],
    ["27", "R' D R' U R D' R' U R2 U' R2 U' R2"],
    ["28", "B' L U2 L' U2 L' B U2 L U L U' L2 U2 L"],
    ["29", "B' R B L' B' R' B L"],
    ["30", "F R' F' R U R U' R' F U R U' R' U R U' R' F'"],
    ["31", "F' L F U F U' F' L' U F U F' U F U' F'"],
    ["32", "B' U' B R U' B' U' B U R' B' U2 B"],
    ["33", "B' L U2 L' U2 L' B L U L U' L'"],
    ["34", "B U B' U B' D' B U2 B' D B2 U' B' U B U' B'"],
    ["35", "R' U' R' D' R U2 R' D R U R U' R' U' R"],
    ["36", "L F U' F' U' F U2 F' U' L'"],
    ["37", "L U L' U L U2 L D L' U2 L D' L' U2 L'"],
    ["38", "L U2 L' U' L2 D L' U' L D' L2"],
    ["39", "R' D' R U2 R' D R U R U2 R' U R U R'"],
    ["40", "R' F' R U R' U' R' F R2 U' R' U2 R"],
    ["41", "B U2 B D B' U2 B D' B2"],
    ["42", "B U2 B' U2 B U B2 D' B U2 B' D B2 U2 B'"],
    ["43", "L U L' U2 L U L2 D' R B2 R' D L2 U' L'"],
    ["44", "L U L' U L U L' U2 L' D' R B2 R' D L"],
    ["45", "B U' B2 D' B U' B' D B U2 B U' B' U' B U B'"],
    ["46", "R2 D' R2 U R' D R2 U' D L2 U2 L2 D' R'"],
    ["47", "B' U B U2 B' U' B U2 B' U' B U' B2 D' B U B' D B2"],
    ["48", "L U' F U F' U F' U2 F U F' U F2 U' F' U L'"],
    ["49", "F R2 F2 U B U' F2 B' R2 F'"],
    ["50", "B U' B' U B U' B' U' B U B' U2 B' D' B U B' D B"],
    ["51", "R' U R U' R' U R U R' U' R U2 R D R' U' R D' R'"],
    ["52", "L F2 R L2 U R' U' L2 F2 L'"],
    ["53", "B' R B L' B L' F L B' L' F' L B' R' B L"],
    ["54", "L F R2 B' R F2 R' B R F L' F R F'"],
    ["55", "R2 B' R D2 L' F L D2 R2 B R'"],
    ["56", "B' R' F2 D2 B' L' B D2 F' R F' B"],
    ["57", "R U2 L' U R' U' L R U2 R'"],
    ["58", "R B U B2 R B R' B U' B' R'"],
    ["59", "B' U2 F U' F' U2 B F U' F'"],
    ["60", "R U' B' U B D B' U B U D' R' B' U B"],
    ["61", "F2 U F' U F' U' F U' F' U' F U F U' F2"],
    ["62", "B U2 B' U' B U' B' U B' U2 B U B' U B"],
    ["63", "B U B' U B U2 B' U B' U' B U' B' U2 B"],
    ["64", "B2 U' B U B U' B' U' B U' B' U B' U B2"],
    ["65", "R' U2 R U R' U R U' R U2 R' U' R U' R'"],
    ["66", "L2 U' L U' L U L' U L U L' U' L' U L2"],
    ["67", "R' U' R U' R' U2 R U' R U R' U R U2 R'"],
    ["68", "R2 U R' U' R' U R U R' U R U' R U' R2"],
    ["69", "B U2 B' U' B U' B' U2 B U B' U B U2 B'"],
    ["70", "B U B' U B U2 B' U2 B U2 B' U' B U' B'"],
    ["71", "F U F' U F U' F' U F U' F' U F U2 F'"],
    ["72", "R U' R' L' U2 L U L' U L R U2 R'"],
  ]),
  ...zb('H', [
    ["1", "R' F R B' R' F' R B2 U2 B' U' B U' B'"],
    ["2", "L F' L' B L F L' B2 U2 B U B' U B"],
    ["3", "F U2 F' U' F U F' U2 F' L F2 U' F' U' F U F' L'"],
    ["4", "R' B U2 B' U2 B' R U' B U B U' B' U' B' U B"],
    ["5", "B U2 B' U F' U2 B U2 B' U2 F B U' B'"],
    ["6", "F U2 F' U' F U F' U' L' F U F' U' F' L F2 U' F'"],
    ["7", "R U R' U R U' R2 F' R U2 R U2 R' F R U' R'"],
    ["8", "B L U' L' U L U2 L' U' L U L' U' B'"],
    ["9", "R F R2 U' R2 U' R2 U2 R2 U' F' R'"],
    ["10", "F' B L2 B' L2 U L2 U L2 U' L2 F"],
    ["11", "U L U2 L' U2 L2 F L' U' L' U L F' U' L'"],
    ["12", "L' F' L2 U L2 U L2 U2 L2 U F L"],
    ["13", "F' U2 F U F' U' L' F U F' U' F' L F U2 F"],
    ["14", "F U2 F' U' F2 D F' U F D' F2 U' F U' F'"],
    ["15", "L2 D' L U' L' D L2 U' L2 D' L U2 L' D L2"],
    ["16", "L2 D' L U2 L' D L' U L2 U L2 U2 L'"],
    ["17", "F R' F' R U2 R U2 R' U' R' F2 L F L' F R"],
    ["18", "L' U' L U' L' U B' L U L' U' L' B L2 U' L' U L"],
    ["19", "B U B' U' B' U2 B2 D B' U B D' B2 U B2 U2 B'"],
    ["20", "B U B' U B U2 B' R B U' B' U' B U2 B' U' R'"],
    ["21", "R' F' R U2 R U2 R' F U' R U' R'"],
    ["22", "R U R' U R U L' U R' U' L"],
    ["23", "B' R B' R' B2 U' F' L F U' F' L' F"],
    ["24", "F U F2 L F L' B L' B' U B L B'"],
    ["25", "F' U' F U' R U' R' U R2 B' R' B R'"],
    ["26", "B U' B2 U' R2 U' B2 U B2 U R2 B2 U B'"],
    ["27", "R B U B' U' B U B' U' B U B' U' R'"],
    ["28", "B' R B' R' B R' U2 R B' R B R' B"],
    ["29", "R' U2 R U R' U R U' L F2 R2 D R D' R F2 L'"],
    ["30", "R' U' R U' R' U2 R2 U2 L' U R' U' L U' R U' R'"],
    ["31", "B' U2 B R' F' U F U R U' B' U2 R B R'"],
    ["32", "F U F' U L' U L U' L2 B L B' L"],
    ["33", "R U R' U R U' R' U R U2 R'"],
    ["34", "R' U' R U' R' U R U' R' U2 R"],
    ["35", "F' U2 F U F' U' F U F' U F"],
    ["36", "F U2 F' U' F U F' U' F U' F'"],
    ["37", "F U2 F2 U2 F' U2 F U2 F' U2 F2 U2 F"],
    ["38", "B U2 B' U' B U' B' U' B' U' B U' B' U2 B"],
    ["39", "R U R' U R U2 R' U' R' U2 R U R' U R"],
    ["40", "R U R' U R U' R' U R U' R' U R' U' R2 U' R' U R' U R"],
  ]),
  ...zb('Pi', [
    ["1", "F U F' U F U2 F2 L' B L F L' B' L"],
    ["2", "B' U' B U' B' U2 B2 L F' L' B' L F L'"],
    ["3", "L' U' L' D' L U L' D L' U L' U L U2 L'"],
    ["4", "F' U' L U' F2 U F2 U L' F2 U2 F'"],
    ["5", "F R' F' R U2 R U2 R' U' L F R' F R F2 L'"],
    ["6", "B2 R2 F R F' R B2 U2 L' B L B'"],
    ["7", "B U2 B2 U' B U' B' U2 R B U B U' B' R'"],
    ["8", "R U B U' B' U B U2 B' U' B U B' R'"],
    ["9", "F U F' U F U' F' U' F' L' F U2 F U2 F' L"],
    ["10", "B' L' U' B2 U2 B2 U' B2 U' B2 L B"],
    ["11", "F L U F2 U2 F2 U F2 U F2 L' F'"],
    ["12", "R' U' F' R U R' U' R' F R2 U2 R' U2 R"],
    ["13", "B2 D' B U2 B' D B2 U B2 D' B U B' D B2"],
    ["14", "F2 D F' U2 F D' F2 U' F2 D F' U' F D' F2"],
    ["15", "R' U2 R' D R' U R D' R U R2 U2 R' U2"],
    ["16", "R U R' U R2 D R' U' R D' R2 U R U2 R'"],
    ["17", "R' U' R U R2 F' R U R U' R' F U' R U R' U R"],
    ["18", "R' U2 R2 U R2 U R U' R U2 L' U R' U' L"],
    ["19", "L U F U2 F' U F U F' L' F U2 F' U' F U' F'"],
    ["20", "L' U2 L U L' U' R U2 R' U2 L U R U' R'"],
    ["21", "R' U L U' R U' L' U' L U' L'"],
    ["22", "L' B L U L' B' L U R2 F R F' R"],
    ["23", "L F' L' U' L F L' U' R2 B' R' B R' U"],
    ["24", "F U F' U L' F U2 F' U2 F' L F"],
    ["25", "R' U2 R U R' U' R U2 L U' R' U R L'"],
    ["26", "F U2 F' U B U' F' U' F2 U' F2 U2 F B'"],
    ["27", "F' B U B' U' F U2 B U' B' U B U2 B'"],
    ["28", "L' U2 L U L' U' L U L2 B L U L U' L' B' L"],
    ["29", "L U' R U R' L' U2 R U2 R' U R U2 R'"],
    ["30", "R U B U' B' U B U' B2 R' B U B U' B'"],
    ["31", "F U R U' R2 F' R2 U R' F' U' F U2 R U' R'"],
    ["32", "F U F' U F U' F2 L F L' F U' F' L' U L"],
    ["33", "B' U' B U' L2 B' U2 B U2 B L2 B'"],
    ["34", "F' U' F U' F' U F U' F' U F' D' F U F' D F2"],
    ["35", "L2 D L' U L D' L' U L' U' L U L' U' L U' L'"],
    ["36", "R' U' R U' R' U2 R U' L' U R U' L U R'"],
    ["37", "R' F R U R' U' R' F' R2 U' R' U R U' R' U2 R"],
    ["38", "R U R D R' U R D' R2 U' R U R' U' R U' R'"],
    ["39", "R U2 R2 U' R2 U' R' U2 R' F R U R' U' R' F' R2"],
    ["40", "F' U' F U' F' U F U' F2 D' F U F' D F U F"],
    ["41", "R U R' U' R' F R2 U R' U' R U R' U' F'"],
    ["42", "L U2 L' U2 L' B L2 U' L' U2 L U2 L' U' B'"],
    ["43", "B U2 B' U' B U B' U' B' D' B U' B' D B2 U' B' U B U' B'"],
    ["44", "L' U' L U L F2 L' F2 U' R U R' U' R U' R'"],
    ["45", "R B2 R' U2 R' U2 R B2 U R' U R"],
    ["46", "F' U2 F U F' U F2 U' B' U F' U' B"],
    ["47", "B U B' U B U' B' U B U' B D B' U' B D' B2"],
    ["48", "F U F' U L2 F U2 F' U2 F' L2 F"],
    ["49", "R U D' R U R' D R2 U' R' U' R2 U2 R"],
    ["50", "F U F' L' F U F' U F U2 F' L U F U2 F'"],
    ["51", "L B U' L2 U2 L U L' U L2 U B' L'"],
    ["52", "F U2 F2 U' F' U' F2 D F' U F U D' F"],
    ["53", "F U R' U' R2 U' R2 U2 R U2 R U R' F'"],
    ["54", "R U2 R2 F R F' R' F R F' R' F R F' R U2 R'"],
    ["55", "L U L' U L U L' U' L U L D L' U L D' L2"],
    ["56", "L U L' U R' U L U R U R' U L' R"],
    ["57", "F' U2 F U2 F U R' U' F2 U F U' F' U F R"],
    ["58", "R F U' R2 U' R U' R' U2 R2 U F' R'"],
    ["59", "R F' U' R2 F U' F' U R2 U F R'"],
    ["60", "L F R' F R F' R' F R F' R U' R' U F' L'"],
    ["61", "R U2 R2 U' R2 U' R2 U2 R"],
    ["62", "B U B' U B U2 B2 U2 B U B' U B"],
    ["63", "F U2 F' U2 F U' F' U2 F U' F' U2 F U F'"],
    ["64", "B' U2 B U2 B' U B U2 B' U B U2 B' U' B"],
    ["65", "L' U L U' L2 U2 L U L' U L2 U' L' U L"],
    ["66", "L2 U2 L U L U' L' U L' U L2 U' L' U L"],
    ["67", "B U2 B' U' B U' B2 U' B U' B' U2 B"],
    ["68", "R' U2 R2 U R2 U R2 U2 R'"],
    ["69", "R U R' U R U2 R' U' R U R' U R U2 R'"],
    ["70", "R' U' R U' R' U2 R U R' U' R U' R' U2 R"],
    ["71", "B U B' U B U2 B' U B U B' U B U2 B'"],
    ["72", "F R U R' U' R U R' U' F' R U R' U' L' R L' R L' R F R F' L'"],
  ]),
  ...zb('S', [
    ["1", "L' U2 L U B L' U L U' B'"],
    ["2", "R U R' U R U L U2 R' U R U2 R' L'"],
    ["3", "R' U R U2 R' U R2 D R' U R D' R'"],
    ["4", "F' U2 F U R F' U' F U F R' F2 U F"],
    ["5", "B' R B U B' U' B' R' D' B U B' D B2"],
    ["6", "F' R U R' U R U2 R' F U R U' R' U2 R U' R'"],
    ["7", "F' U' F U F2 U' F' U' F U D' F U F' D F'"],
    ["8", "L U L' U L2 D R' F2 R D' L2"],
    ["9", "B U B' U' B U B2 D' B U B' D B U B U2 B'"],
    ["10", "L U L' U L2 D L' U2 L D' L2"],
    ["11", "F R' U' R2 U' R2 U2 R2 U' R' F'"],
    ["12", "R U2 R D R' U2 R D' R' U R' U R U2 R'"],
    ["13", "R U R' U' R2 U' L' U R2 U' L U' R U2 R'"],
    ["14", "B U2 B' U R2 D' F U' F2 U F' D R2"],
    ["15", "B' U' R2 U' B2 U B2 U R2 B2 U2 B'"],
    ["16", "L U2 L D L2 U' L U L2 D' L U' L U' L'"],
    ["17", "L F' U F U L' F' U L U L' F"],
    ["18", "L F' U2 F L' F' L U2 L' F"],
    ["19", "F U F' U F U' F D F' U F B' R2 B D' F2"],
    ["20", "L F U F' U' F' L' U2 F U F U' F' U F' U F"],
    ["21", "L U L' R' U2 L U2 L' U2 R U2 L U' L'"],
    ["22", "L U L' U L U' L D L' U L D' L' U2 L'"],
    ["23", "F U F' U F U' F D F' U' F D' F2"],
    ["24", "L2 D' L U' L' D L U' L U L' U L"],
    ["25", "R2 D R' U2 R D' R' U' R' U R U2 R'"],
    ["26", "F' U2 L' F U F' U' F' L F U2 F"],
    ["27", "B' U2 B U B' U' B' D' B U2 B' D B2"],
    ["28", "B U B' U B U' B2 D' B U B' D B2 U2 B'"],
    ["29", "R U' L' U R' U' L"],
    ["30", "F' U2 F2 U F D' F U F' D F2 U' F U' F'"],
    ["31", "F U F' U F U2 F2 U F U2 B' F' U F U' B"],
    ["32", "D' F2 U F U' F2 U' F U F' D F' U F"],
    ["33", "B' U' B' U B2 D' U2 B U B' U' D B'"],
    ["34", "R U' L' U R' L' U' L' U' L' U L U L2"],
    ["35", "R2 D L' B2 L D' R' U' R' U R U2 R'"],
    ["36", "F' U' D F' U F D' U2 F2 U F' U' F'"],
    ["37", "L' R U R' U' L U2 R U2 R'"],
    ["38", "B' D' B U B' D B2 U B' U2 B U B'"],
    ["39", "B' U2 B U B2 D' B U' B' D B U2 B"],
    ["40", "B U B2 R' B U B U' B' R U B U2 B'"],
    ["41", "B U' F' U B' U2 F U B U' F' U B' F"],
    ["42", "R' F' R U R U R' U' R U' R' F R U R' U R U' R'"],
    ["43", "L2 D' R B2 R' D L2 U L' U L"],
    ["44", "F U R U' R' F' B U' F' U L U L' U' F' B F' B F' B"],
    ["45", "F R U R' U' R' F' R U2 R U' R' U R U2 R'"],
    ["46", "R' U2 R U R' U R' D' R U2 R' D R U2 R"],
    ["47", "R2 F R U R U' R' F' R U' R' U R"],
    ["48", "L2 D' L U2 L' D L2 U L' U L"],
    ["49", "L U' L D L2 U' L U' L' U2 L2 D' L' U L'"],
    ["50", "R U B' R B R' B U' B' U B U' B' R'"],
    ["51", "F U' F2 U2 D' F U F' U D F2 U F'"],
    ["52", "R' B U B' D B U B' U' D' B U' B' R"],
    ["53", "F U' B' U F' U' F U' B U F' U' B' U B"],
    ["54", "F R U R' U R U2 R U2 R2 U' R2 U' R2 F'"],
    ["55", "R' U2 R U R' U' R F U' R' U' R U F'"],
    ["56", "R D' B2 D R' U2 L' U' L' U L' U L2"],
    ["57", "L U L' U R' U L U' R U2 L'"],
    ["58", "F U' R' U R U F' R U R2 U R2 U2 R'"],
    ["59", "R' U2 L U' R U L' U R' U R"],
    ["60", "R' F R F' U R U R' U2 F R' F' R"],
    ["61", "F' B D L2 D' B2 U B U' F"],
    ["62", "R U R' U R U' R' U R' U' R2 U' R' U R' U R"],
    ["63", "R U R2 U' R2 U' R2 U2 R2 U2 R'"],
    ["64", "F' U2 F U F' U F"],
    ["65", "R U R' U R U R U R U R U' R' U' R2"],
    ["66", "R U R2 F' R U2 R U' R' U' R' F R2 U' R'"],
    ["67", "R U R' U R U2 R'"],
    ["68", "R' U2 R2 U2 R2 U' R2 U' R2 U R"],
    ["69", "R U R' U R2 U R U R2 U' R' U' R2"],
    ["70", "F' U' F U F U F' U' F' U F U F U' F'"],
    ["71", "F' U2 F2 U F2 U F U' F U' F'"],
    ["72", "R U R' U' R U R' U R U R U2 R' U' R U' R' U R'"],
  ]),
  ...zb('AS', [
    ["1", "F U F' U F' D F2 U' F' U F2 D' F' U2 F'"],
    ["2", "L' U2 B' L U L' U' L' B L2 U L' U L"],
    ["3", "R' U' R U' R D' R U2 R' D R U2 R U2 R"],
    ["4", "F U2 F U2 F' U' F' U F L' F U2 F' U2 F' L"],
    ["5", "L' B U2 B' L B L' U2 L B'"],
    ["6", "L' B U' B' U' L B U' L' U' L B'"],
    ["7", "L2 D R' F2 R L' U' L D' L' U L' U' L U' L'"],
    ["8", "F2 L' F2 U F2 D' L' U' D L' U L2 F2"],
    ["9", "B U B' U2 F' U2 B U2 F U F' B' U2 F"],
    ["10", "B U2 B D B' U' B D' B' U B' U' B U' B'"],
    ["11", "L2 D L' U L D' L' U L' U' L U' L'"],
    ["12", "B' U' B U' B' U B' D' B U B' D B2"],
    ["13", "R U' R' U2 R U' R2 D' R U' R' D R"],
    ["14", "F' B L2 U L2 U' L2 U' F U B'"],
    ["15", "L U2 L' U2 R' U L U' L' R"],
    ["16", "F' U2 F' D' F U F' D F2 U' F' U2 F"],
    ["17", "B U B' U' B U' B' R' B U B' U B U' B' U' B' R B"],
    ["18", "B2 D B' U B D' B2 U' F' U B U' B' F"],
    ["19", "F R' F' U2 R U F' R' U R U F R U' R'"],
    ["20", "L' U' L U' L2 D' R B2 R' D L2"],
    ["21", "L' U' L U' L2 D' L U2 L' D L2"],
    ["22", "F U F' U F U2 F2 B U B' U' F U2 B U2 B'"],
    ["23", "R' U2 R' D' R U2 R' D R U' R U' R' U2 R"],
    ["24", "R' U' R U R' F R U R' U' R' F' R2"],
    ["25", "F U2 F' U' F U F D F' U2 F D' F2"],
    ["26", "L' U2 L' B' L U L U' L' B U2 L"],
    ["27", "R2 D' R U2 R' D R U R U' R' U2 R"],
    ["28", "B U2 B D B2 U' B U' B' U2 B2 D' B2"],
    ["29", "R U B U' B' U B U' B' U B2 D B' U' B D' B2 R'"],
    ["30", "R' U L U' R U L'"],
    ["31", "L' U L U L' U' L' D' L U L' D L U L U' L' U2 L"],
    ["32", "D L' U' L D' L U' L' U L2 U L' U' L2"],
    ["33", "F U2 F' U' F U F D B' R2 B D' F2"],
    ["34", "F U F U' F2 D U2 F' U' F U D' F"],
    ["35", "B D' U B U' B' U2 D B2 U' B U B"],
    ["36", "R2 D' L F2 L' D R U R U' R' U2 R"],
    ["37", "L R U2 R' U' R U2 L' U' R' U' R U' R'"],
    ["38", "F' U B U' L2 U' L2 U L2 B' F"],
    ["39", "L U F' U' F L' U' F' U2 F"],
    ["40", "F U' F' U2 B' U F U' B2 U' F' U B'"],
    ["41", "B U B' U2 B U B' U' R' B U2 B' U' B U' B' R"],
    ["42", "R2 D' R U' R' D F R U R U' R' F' R"],
    ["43", "L2 D R' F2 R D' L2 U' L U' L'"],
    ["44", "R' U' R U' R' U2 L' U2 L U L' U2 R U' L"],
    ["45", "R U2 R' U R U L U' R' U L' U R U' R'"],
    ["46", "F' U' F U F U' F' U2 F B U' F2 U B' U2 F"],
    ["47", "L2 D L' U2 L D' L2 U' L U' L'"],
    ["48", "R B U B2 U2 B2 U B2 U B R'"],
    ["49", "R U' R' U2 R U' R' U2 R' D' R U R' D R"],
    ["50", "F U2 F2 U' F2 U' F' L U' F' U' F U L'"],
    ["51", "L' B L B' U2 L U' L' U' B L' B' L"],
    ["52", "L' U' L U' R U' L' U R' U2 L"],
    ["53", "B' U F U' B U B' U F' U' B U F U' F'"],
    ["54", "B L2 U L2 U L2 U2 L' U2 L' U' L U' L' B'"],
    ["55", "L U' F' U F U L' F' U F U' F' U2 F"],
    ["56", "L F U' F' U F U2 F' U' L' F U F' U' F' L F L'"],
    ["57", "R U' R D R2 U2 R U R' U R2 D' R' U R'"],
    ["58", "L F U F' U' F U F' L F' L' F U' L'"],
    ["59", "L' U L' D' L2 U L' U L U2 L2 D L U' L"],
    ["60", "F U' F2 D' U' F U' F' U2 D F2 U F'"],
    ["61", "B2 U B2 U B' U2 B' U B U B' U' B2"],
    ["62", "B' U' B U B U2 B' U' B U' B' U B' U B"],
    ["63", "L U L' U L' U' L U' L' U2 L U L U' L'"],
    ["64", "F' U' F U' F U F2 U F U' F U F' U' F U' F'"],
    ["65", "R' U' R2 U R2 U R2 U2 R2 U2 R"],
    ["66", "B U2 B' U' B U' B'"],
    ["67", "R U2 R2 U2 R2 U R2 U R2 U' R'"],
    ["68", "R' U' R U' R' U2 R"],
    ["69", "B U B' U' B' U' B U B U' B' U' B' U B"],
    ["70", "B2 U B U B2 U' B' U' B2 U' B U' B'"],
    ["71", "L U L' U L' U' L2 U' L2 U2 L"],
    ["72", "R' F2 R D R' D' F2 U' R2 U R' U' R2"],
  ]),
];
