/* GENERATED by tools/import-cubingapp.mjs from 2-Look-PLL.json — do not hand-edit.
   More algorithms for the 2LPLL cases, in the order that list gives them.
   Every one was executed against the case it is filed under. */
export const EXTRA = {
  "CP-adj": [{"alg":"U R' F R' B2 R F' R' B2 R2","moveCount":10}],
  "CP-diag": [{"alg":"F R U' R' U' R U R' F' R U R' U' R' F R F'","moveCount":17}],
  "EP-Ua": [{"alg":"M2 U M U2 M' U M2","moveCount":7,"notes":"Inverse of Ub perm"},{"alg":"R U' R U R U R U' R' U' R2","moveCount":11},{"alg":"U2 R U R' U R' U' R2 U' R' U R' U R","moveCount":14,"notes":"no M turns needed, close second in votes"}],
  "EP-Ub": [{"alg":"M2 U' M U2 M' U' M2","moveCount":7,"notes":"Inverse of Ua perm"},{"alg":"R2 U R U R' U' R' U' R' U R'","moveCount":11},{"alg":"U2 R' U R' U' R' U' R' U R U R2","moveCount":12,"notes":"no-M-slice alternative, fewer moves than this app's existing default"}],
  "EP-H": [{"alg":"M2 U' M2 U2 M2 U' M2","moveCount":7,"notes":"mirrored AUF direction, essentially equally popular"}],
  "EP-Z": [{"alg":"U M2 U' M2 U' M' U2 M2 U2 M' U2","moveCount":11}],
};
