/* GENERATED by tools/import-cubingapp.mjs from PLL.json — do not hand-edit.
   More algorithms for the PLL cases, in the order that list gives them.
   Every one was executed against the case it is filed under. */
export const EXTRA = {
  "Aa": [{"alg":"x R' U R' D2 R U' R' D2 R2 x'","moveCount":11,"notes":"Inverse of Ab perm"}],
  "Ab": [{"alg":"U' x R2 D2 R U R' D2 R U' R x'","moveCount":12,"notes":"Inverse of Aa perm"}],
  "E": [{"alg":"x' R U' R' D R U R' D' R U R' D R U' R' D' x","moveCount":18,"notes":"4 groups of R U R D"},{"alg":"R' U' R' D' R U' R' D R U R' D' R U R' D R2","moveCount":17}],
  "F": [{"alg":"R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R","moveCount":18,"notes":"R' U' F' (T perm) F U R"}],
  "Ga": [{"alg":"R2 U R' U R' U' R U' R2 D U' R' U R D'","moveCount":15,"notes":"Inverse of Gb"}],
  "Gb": [{"alg":"R' U' R U D' R2 U R' U R U' R U' R2 D","moveCount":15,"notes":"Inverse of Ga"}],
  "Gc": [{"alg":"U2 R2 F2 R U2 R U2 R' F R U R' U' R' F R2","moveCount":16},{"alg":"R2 U' R U' R U R' U R2 D' U R U' R' D","moveCount":15,"notes":"top-voted Gc; this app's default written with the commuting D' and U swapped"}],
  "Gd": [{"alg":"R U R' U' D R2 U' R U' R' U R' U R2 D'","moveCount":15,"notes":"Mirror of Gb"}],
  "H": [{"alg":"M2 U' M2 U2 M2 U' M2","moveCount":7,"notes":"mirrored AUF direction, essentially equally popular"}],
  "Ja": [{"alg":"x R2 F R F' R U2 r' U r U2 x'","moveCount":12},{"alg":"U2 L' U' L F L' U' L U L F' L2 U L","moveCount":14,"notes":"no-AUF alternative but noticeably more moves"},{"alg":"U' R' U L' U2 R U' R' U2 R L","moveCount":11},{"alg":"R' U2 R U R' U2 L U' R U L'","moveCount":11}],
  "Jb": [{"alg":"R U R' F' R U R' U' R' F R2 U' R' U'","moveCount":14,"notes":"T perm with last 4 moves shifted to beginning"}],
  "Na": [{"alg":"R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'","moveCount":21,"notes":"R U R' U (J perm) U' R U' R'"},{"alg":"F' R U R' U' R' F R2 F U' R' U' R U F' R'","moveCount":16,"notes":"notably shorter, second most common choice"},{"alg":"R F U' R' U R U F' R2 F' R U R U' R' F","moveCount":16,"notes":"similar length alternative with different trigger framing"},{"alg":"r' D r U2 r' D r U2 r' D r U2 r' D r U2 r' D r","moveCount":19,"notes":"repeated-trigger algorithm, easy to learn but slower in practice"}],
  "Nb": [{"alg":"r' D' F r U' r' F' D r2 U r' U' r' F r F'","moveCount":16,"notes":"Ends with wide sexy sledge"},{"alg":"R' U R U' R' F' U' F R U R' F R' F' R U' R","moveCount":17,"notes":"most popular Nb, matches this app's existing default alg"},{"alg":"R' U L' U2 R U' L R' U L' U2 R U' L","moveCount":14,"notes":"shortest common Nb, but less finger-trick-friendly"}],
  "Ra": [{"alg":"R U' R' U' R U R D R' U' R D' R' U2 R' U'","moveCount":16},{"alg":"R U R' F' R U2 R' U2 R' F R U R U2 R'","moveCount":15}],
  "Rb": [{"alg":"R' U2 R U2 R' F R U R' U' R' F' R2","moveCount":13,"notes":"most popular Rb, R' U2 opener, easier recognition than the F-trigger version"}],
  "T": [{"alg":"R U R' U' R' F R2 U' R' U' R U R' F'","moveCount":14,"notes":"J perm with first 4 moves shifted to end"}],
  "Ua": [{"alg":"M2 U M U2 M' U M2","moveCount":7,"notes":"Inverse of Ub perm"},{"alg":"R U' R U R U R U' R' U' R2","moveCount":11},{"alg":"U2 R U R' U R' U' R2 U' R' U R' U R","moveCount":14,"notes":"no M turns needed, close second in votes"}],
  "Ub": [{"alg":"M2 U' M U2 M' U' M2","moveCount":7,"notes":"Inverse of Ua perm"},{"alg":"R2 U R U R' U' R' U' R' U R'","moveCount":11},{"alg":"U2 R' U R' U' R' U' R' U R U R2","moveCount":12,"notes":"no-M-slice alternative, fewer moves than this app's existing default"}],
  "V": [{"alg":"R' U R' U' R D' R' D R' U D' R2 U' R2 D R2","moveCount":16,"notes":"most popular V-perm variant"},{"alg":"R' U R' U' y R' F' R2 U' R' U R' F R F","moveCount":15,"notes":"matches this app's existing default alg style, one move shorter"}],
  "Y": [{"alg":"F R U' R' U' R U R' F' R U R' U' R' F R F'","moveCount":17,"notes":"2 OLLs"},{"alg":"F R' F R2 U' R' U' R U R' F' R U R' U' F'","moveCount":16,"notes":"distant second in popularity, one move shorter"}],
  "Z": [{"alg":"U M2 U' M2 U' M' U2 M2 U2 M' U2","moveCount":11},{"alg":"M' U' M2 U' M2 U' M' U2 M2","moveCount":9,"notes":"most popular Z-perm variant"}],
};
