/* GENERATED by tools/import-cubingapp.mjs from Pyraminx-Last-Layer.json — do not hand-edit.
   Every case below sits where its set says it should, and every algorithm
   was executed against the case it is filed under. */
export const SET = {
  "id": "PYRA-LL",
  "event": "pyram",
  "puzzle": "pyram",
  "label": "Last Layer",
  "title": "The last three edges of layer-by-layer",
  "adjust": {"pre":["","U","U'"],"post":["","U","U'"]},
  "scramble": {"pre":[""],"post":["","U","U'"]},
  "trainerMode": "pyrall",
  "cases": [
    {"id":"PYRA-LL-sune","name":"Sune","alg":"R U R' U R U R'"},
    {"id":"PYRA-LL-antisune","name":"Antisune","alg":"R U' R' U' R U' R'"},
    {"id":"PYRA-LL-2-flip","name":"2-flip","alg":"L R' L' R U' R U R'"},
    {"id":"PYRA-LL-r-unsexy-r","name":"R' unsexy R","alg":"R' U' L' U L R"},
    {"id":"PYRA-LL-l-unsexy-l","name":"L unsexy L'","alg":"L U R U' R' L'"},
  ],
  "library": {
    "PYRA-LL-sune": {"alternates":[{"alg":"R U R' U R U R'","moveCount":7}]},
    "PYRA-LL-antisune": {"alternates":[{"alg":"R U' R' U' R U' R'","moveCount":7}]},
    "PYRA-LL-2-flip": {"alternates":[{"alg":"L R' L' R U' R U R'","moveCount":8}]},
    "PYRA-LL-r-unsexy-r": {"alternates":[{"alg":"R' U' L' U L R","moveCount":6}]},
    "PYRA-LL-l-unsexy-l": {"alternates":[{"alg":"L U R U' R' L'","moveCount":6}]},
  },
};
