/* GENERATED by tools/import-cubingapp.mjs from SQ1-EO.json — do not hand-edit.
   Every case below sits where its set says it should, and every algorithm
   was executed against the case it is filed under. */
export const SET = {
  "id": "SQ1-EO",
  "event": "sq1",
  "puzzle": "sq1",
  "label": "EO",
  "title": "Edges onto their layers, once the corners are",
  "done": "layers",
  "adjust": {"pre":["","6,0","0,6","6,6"],"post":["","6,0","0,6","6,6"]},
  "scramble": {"pre":["/ 3,-3 / -3,3 /","/ -3,3 / 3,-3 /","/ 0,-3 / 3,3 / -3,0 /","/ -3,0 / 3,3 / 0,-3 /"],"post":["0,0","6,0","0,6","6,6"]},
  "groups": ["EO Algs"],
  "defaultGroup": null,
  "trainerMode": "sq1eo",
  "cases": [
    {"id":"SQ1-EO-1-1","name":"1 / 1","group":"EO Algs","alg":"1,0 / 3,0 / 3,0 / -1,-1 / -2,1 / -3,0 / -1,0"},
    {"id":"SQ1-EO-opp-opp","name":"Opp / Opp","group":"EO Algs","alg":"1,0 / -1,-1 / 0,1"},
    {"id":"SQ1-EO-4-4","name":"4 / 4","group":"EO Algs","alg":"1,0 / -1,-1 / -2,4 / -1,-1 / 0,1"},
    {"id":"SQ1-EO-adj-adj","name":"Adj / Adj","group":"EO Algs","alg":"1,0 / 3,0 / -1,-1 / -3,0 / 0,1"},
    {"id":"SQ1-EO-3-3","name":"3 / 3","group":"EO Algs","alg":"1,0 / 3,0 / 3,0 / -1,-1 / -3,0 / -3,0 / 0,1"},
    {"id":"SQ1-EO-adj-opp","name":"Adj / Opp","group":"EO Algs","alg":"1,0 / 0,-3 / 0,3 / 2,-1 / -3,0 / 0,1"},
    {"id":"SQ1-EO-opp-adj","name":"Opp / Adj","group":"EO Algs","alg":"0,-1 / 3,0 / -3,0 / 1,-2 / 0,3 / -1,0"},
  ],
  "library": {
    "SQ1-EO-1-1": {"alternates":[{"alg":"1,0 / 3,0 / 3,0 / -1,-1 / -2,1 / -3,0 / -1,0","moveCount":6}]},
    "SQ1-EO-opp-opp": {"alternates":[{"alg":"1,0 / -1,-1 / 0,1","moveCount":2,"notes":"Basically just an M2"}]},
    "SQ1-EO-4-4": {"alternates":[{"alg":"1,0 / -1,-1 / -2,4 / -1,-1 / 0,1","moveCount":4,"notes":"M2 U' D M2"}]},
    "SQ1-EO-adj-adj": {"alternates":[{"alg":"1,0 / 3,0 / -1,-1 / -3,0 / 0,1","moveCount":4}]},
    "SQ1-EO-3-3": {"alternates":[{"alg":"1,0 / 3,0 / 3,0 / -1,-1 / -3,0 / -3,0 / 0,1","moveCount":6}]},
    "SQ1-EO-adj-opp": {"alternates":[{"alg":"1,0 / 0,-3 / 0,3 / 2,-1 / -3,0 / 0,1","moveCount":5,"notes":"Fastest alg"},{"alg":"-5,0 / 3,0 / 3,0 / -1,-1 / -2,1 / -4,-1 / 1,0","moveCount":6,"notes":"Preserves CP"}]},
    "SQ1-EO-opp-adj": {"alternates":[{"alg":"0,-1 / 3,0 / -3,0 / 1,-2 / 0,3 / -1,0","moveCount":5,"notes":"Fastest alg"},{"alg":"0,5 / 0,-3 / 0,-3 / 1,1 / -1,2 / 1,4 / -1,0","moveCount":6,"notes":"Preserves CP"}]},
  },
};
