/* GENERATED by tools/import-cubingapp.mjs from SQ1-CP.json — do not hand-edit.
   Every case below sits where its set says it should, and every algorithm
   was executed against the case it is filed under. */
export const SET = {
  "id": "SQ1-CP",
  "event": "sq1",
  "puzzle": "sq1",
  "label": "CP",
  "title": "Permute the corners",
  "done": "corners",
  "adjust": {"pre":["","6,0","0,6","6,6"],"post":["","6,0","0,6","6,6"]},
  "scramble": {"pre":["","6,0","0,6","6,6"],"post":["0,0","6,0","0,6","6,6"]},
  "groups": ["Top Adj","Top Opp","Top Solved"],
  "defaultGroup": null,
  "trainerMode": "sq1cp",
  "cases": [
    {"id":"SQ1-CP-adj-adj","name":"Adj / Adj","group":"Top Adj","alg":"/ -3,0 / 3,3 / 0,-3 /"},
    {"id":"SQ1-CP-adj-opp","name":"Adj / Opp","group":"Top Adj","alg":"/ 0,-3 / 0,3 / 0,-3 / 0,3 /"},
    {"id":"SQ1-CP-adj-solved","name":"Adj / Solved","group":"Top Adj","alg":"/ 3,-3 / -3,0 / 0,3 / 0,-3 / 0,3 /"},
    {"id":"SQ1-CP-opp-opp","name":"Opp / Opp","group":"Top Opp","alg":"/ 3,-3 / -3,3 /"},
    {"id":"SQ1-CP-opp-adj","name":"Opp / Adj","group":"Top Opp","alg":"/ -3,0 / 3,0 / -3,0 / 3,0 /"},
    {"id":"SQ1-CP-opp-solved","name":"Opp / Solved","group":"Top Opp","alg":"/ -3,-3 / -3,0 / -3,-3 / -3,0 / -3,-3 /"},
    {"id":"SQ1-CP-solved-adj","name":"Solved / Adj","group":"Top Solved","alg":"/ 3,-3 / 0,3 / -3,0 / 3,0 / -3,0 /"},
    {"id":"SQ1-CP-solved-opp","name":"Solved / Opp","group":"Top Solved","alg":"/ 3,3 / 0,3 / 3,3 / 0,3 / 3,3 /"},
  ],
  "library": {
    "SQ1-CP-adj-adj": {"alternates":[{"alg":"/ -3,0 / 3,3 / 0,-3 /","moveCount":4}]},
    "SQ1-CP-adj-opp": {"alternates":[{"alg":"/ 0,-3 / 0,3 / 0,-3 / 0,3 /","moveCount":5}]},
    "SQ1-CP-adj-solved": {"alternates":[{"alg":"/ 3,-3 / -3,0 / 0,3 / 0,-3 / 0,3 /","moveCount":6}]},
    "SQ1-CP-opp-opp": {"alternates":[{"alg":"/ 3,-3 / -3,3 /","moveCount":3}]},
    "SQ1-CP-opp-adj": {"alternates":[{"alg":"/ -3,0 / 3,0 / -3,0 / 3,0 /","moveCount":5}]},
    "SQ1-CP-opp-solved": {"alternates":[{"alg":"/ -3,-3 / -3,0 / -3,-3 / -3,0 / -3,-3 /","moveCount":6}]},
    "SQ1-CP-solved-adj": {"alternates":[{"alg":"/ 3,-3 / 0,3 / -3,0 / 3,0 / -3,0 /","moveCount":6}]},
    "SQ1-CP-solved-opp": {"alternates":[{"alg":"/ 3,3 / 0,3 / 3,3 / 0,3 / 3,3 /","moveCount":6}]},
  },
};
