/* GENERATED by tools/import-lastslot.mjs — do not hand-edit. See LASTSLOT.md.
   Vandenbergh-Harris last slot: the 32 ZBLS cases of F2L 1-4. Algorithms by Chad Batten.

   Algorithms from Alg-Trainer (github.com/tao-yu/Alg-Trainer), MIT License:

   Copyright (c) 2017-2021 Tao Yu

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in all
   copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE.

   Further ZBLS alternatives from @moishy/algsets (github.com/moishy-r/moishy-cubing),
   MIT License:

   Copyright (c) 2026 Moshe Rosenberg

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in all
   copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE.
   Every case below disturbs only the front-right slot and the top layer,
   and every algorithm was executed against the case it is filed under. */
export const SET = {
  "id": "VHLS",
  "event": "333",
  "puzzle": "cube",
  "n": 3,
  "label": "VHLS",
  "title": "Orient the last-layer edges while inserting a pair that is already made",
  "picture": "3d",
  "gray": ["F00","F01","F02","B02","B01","B00","L00","L01","L02","R00","R01","R02","U00","U02","U20","U22"],
  "adjust": {"pre":["","U","U2","U'"],"post":["","U","U2","U'"]},
  "scramble": {"pre":["","R U2 R' U' R U' R'","R U R' U R U2 R'","R U2 R' U' R U R' U' R U' R'","R' U2 R2 U R2 U R2 U2 R'","R U2 R D R' U2 R D' R2","F R' F' r U R U' r'","R' F' r U R U' r' F","U","U R U2 R' U' R U' R'","U R U R' U R U2 R'","U R U2 R' U' R U R' U' R U' R'","U R' U2 R2 U R2 U R2 U2 R'","U R U2 R D R' U2 R D' R2","U F R' F' r U R U' r'","U R' F' r U R U' r' F","U2","U2 R U2 R' U' R U' R'","U2 R U R' U R U2 R'","U2 R U2 R' U' R U R' U' R U' R'","U2 R' U2 R2 U R2 U R2 U2 R'","U2 R U2 R D R' U2 R D' R2","U2 F R' F' r U R U' r'","U2 R' F' r U R U' r' F","U'","U' R U2 R' U' R U' R'","U' R U R' U R U2 R'","U' R U2 R' U' R U R' U' R U' R'","U' R' U2 R2 U R2 U R2 U2 R'","U' R U2 R D R' U2 R D' R2","U' F R' F' r U R U' r'","U' R' F' r U R U' r' F"],"post":["","U","U2","U'"]},
  "groups": ["F2L 1","F2L 2","F2L 3","F2L 4"],
  "defaultGroup": null,
  "trainerMode": "vhls",
  "cases": [
    {"id":"VHLS-vhls-1-1","name":"VHLS 1-1","group":"F2L 1","alg":"U R U' R'"},
    {"id":"VHLS-vhls-1-2","name":"VHLS 1-2","group":"F2L 1","alg":"U R U R' U2 M' U R U' r'"},
    {"id":"VHLS-vhls-1-3","name":"VHLS 1-3","group":"F2L 1","alg":"M' U R U' r'"},
    {"id":"VHLS-vhls-1-4","name":"VHLS 1-4","group":"F2L 1","alg":"M U R U' R' U' M'"},
    {"id":"VHLS-vhls-1-5","name":"VHLS 1-5","group":"F2L 1","alg":"U2 F2 r U r' F"},
    {"id":"VHLS-vhls-1-6","name":"VHLS 1-6","group":"F2L 1","alg":"R' F R2 U R' U' F'"},
    {"id":"VHLS-vhls-1-7","name":"VHLS 1-7","group":"F2L 1","alg":"R' U' F U R U' F'"},
    {"id":"VHLS-vhls-1-8","name":"VHLS 1-8","group":"F2L 1","alg":"M' U R U' r2 U2 R U R' U r"},
    {"id":"VHLS-vhls-2-1","name":"VHLS 2-1","group":"F2L 2","alg":"y U' L' U L"},
    {"id":"VHLS-vhls-2-2","name":"VHLS 2-2","group":"F2L 2","alg":"U' R2 D r' U r D' R2"},
    {"id":"VHLS-vhls-2-3","name":"VHLS 2-3","group":"F2L 2","alg":"r U R' U' M"},
    {"id":"VHLS-vhls-2-4","name":"VHLS 2-4","group":"F2L 2","alg":"U' F2 r U r' U F"},
    {"id":"VHLS-vhls-2-5","name":"VHLS 2-5","group":"F2L 2","alg":"U2 R2 B' R' B R'"},
    {"id":"VHLS-vhls-2-6","name":"VHLS 2-6","group":"F2L 2","alg":"R U2 R D r' U' r D' R2"},
    {"id":"VHLS-vhls-2-7","name":"VHLS 2-7","group":"F2L 2","alg":"d' F R U R' F'"},
    {"id":"VHLS-vhls-2-8","name":"VHLS 2-8","group":"F2L 2","alg":"r U r' U2 M' U M"},
    {"id":"VHLS-vhls-3-1","name":"VHLS 3-1","group":"F2L 3","alg":"y L' U' L"},
    {"id":"VHLS-vhls-3-2","name":"VHLS 3-2","group":"F2L 3","alg":"y' S' R' U' R S"},
    {"id":"VHLS-vhls-3-3","name":"VHLS 3-3","group":"F2L 3","alg":"R U' R' F' r U' r' F2"},
    {"id":"VHLS-vhls-3-4","name":"VHLS 3-4","group":"F2L 3","alg":"U R2 D r' U' r D' R2"},
    {"id":"VHLS-vhls-3-5","name":"VHLS 3-5","group":"F2L 3","alg":"F' r U' r' F2 R U' R'"},
    {"id":"VHLS-vhls-3-6","name":"VHLS 3-6","group":"F2L 3","alg":"U2 R' D' r U' r' D R2 U' R'"},
    {"id":"VHLS-vhls-3-7","name":"VHLS 3-7","group":"F2L 3","alg":"U' R' F R U R U' R2 F' R"},
    {"id":"VHLS-vhls-3-8","name":"VHLS 3-8","group":"F2L 3","alg":"R' F R2 U' M' U2 r' U' F'"},
    {"id":"VHLS-vhls-4-1","name":"VHLS 4-1","group":"F2L 4","alg":"R U R'"},
    {"id":"VHLS-vhls-4-2","name":"VHLS 4-2","group":"F2L 4","alg":"R U R' U' F R U R' U' F'"},
    {"id":"VHLS-vhls-4-3","name":"VHLS 4-3","group":"F2L 4","alg":"R U R' F R U R' U' F'"},
    {"id":"VHLS-vhls-4-4","name":"VHLS 4-4","group":"F2L 4","alg":"R U R' U' r' U2 R U R' U r"},
    {"id":"VHLS-vhls-4-5","name":"VHLS 4-5","group":"F2L 4","alg":"R U R' F U R U' R' F'"},
    {"id":"VHLS-vhls-4-6","name":"VHLS 4-6","group":"F2L 4","alg":"R U' R' F2 r U r' F"},
    {"id":"VHLS-vhls-4-7","name":"VHLS 4-7","group":"F2L 4","alg":"R U' R' U2 R' F R F'"},
    {"id":"VHLS-vhls-4-8","name":"VHLS 4-8","group":"F2L 4","alg":"R' D' r U' r' D R2 U R'"},
  ],
  "library": {
    "VHLS-vhls-1-1": {"alternates":[{"alg":"U R U' R'","moveCount":4}]},
    "VHLS-vhls-1-2": {"alternates":[{"alg":"U R U R' U2 M' U R U' r'","moveCount":10},{"alg":"U R U R' U2 R' F R F'","moveCount":9},{"alg":"R' U' F U R2 U' R' F'","moveCount":8}]},
    "VHLS-vhls-1-3": {"alternates":[{"alg":"M' U R U' r'","moveCount":5},{"alg":"R' F R F'","moveCount":4}]},
    "VHLS-vhls-1-4": {"alternates":[{"alg":"M U R U' R' U' M'","moveCount":7},{"alg":"U S' R U' R' S","moveCount":6},{"alg":"U2 R U' B U' B' R'","moveCount":7}]},
    "VHLS-vhls-1-5": {"alternates":[{"alg":"U2 F2 r U r' F","moveCount":6},{"alg":"U2 R' F R F' R U2 R'","moveCount":8},{"alg":"U R B U' B' R'","moveCount":6},{"alg":"U R' F R F2 U F","moveCount":7}]},
    "VHLS-vhls-1-6": {"alternates":[{"alg":"R' F R2 U R' U' F'","moveCount":7},{"alg":"U2 R U' R' U' R' F R F'","moveCount":9}]},
    "VHLS-vhls-1-7": {"alternates":[{"alg":"R' U' F U R U' F'","moveCount":7},{"alg":"U F' L' U' L F","moveCount":6},{"alg":"U2 R U2 B U B' U' R'","moveCount":8}]},
    "VHLS-vhls-1-8": {"alternates":[{"alg":"M' U R U' r2 U2 R U R' U r","moveCount":11},{"alg":"y R' F' R U2 M' U' M","moveCount":8},{"alg":"U2 R' F R F' U2 R' F R F'","moveCount":10}]},
    "VHLS-vhls-2-1": {"alternates":[{"alg":"y U' L' U L","moveCount":5}]},
    "VHLS-vhls-2-2": {"alternates":[{"alg":"U' R2 D r' U r D' R2","moveCount":8},{"alg":"U R' D' r U' r' D R","moveCount":8}]},
    "VHLS-vhls-2-3": {"alternates":[{"alg":"r U R' U' M","moveCount":5},{"alg":"F R' F' R","moveCount":4}]},
    "VHLS-vhls-2-4": {"alternates":[{"alg":"U' F2 r U r' U F","moveCount":7},{"alg":"U' R' D' r U r' D R","moveCount":8}]},
    "VHLS-vhls-2-5": {"alternates":[{"alg":"U2 R2 B' R' B R'","moveCount":6},{"alg":"U' r U' r' U r U r'","moveCount":8}]},
    "VHLS-vhls-2-6": {"alternates":[{"alg":"R U2 R D r' U' r D' R2","moveCount":9}]},
    "VHLS-vhls-2-7": {"alternates":[{"alg":"d' F R U R' F'","moveCount":6},{"alg":"U2 R U R' U' R' F R F' R U' R'","moveCount":12}]},
    "VHLS-vhls-2-8": {"alternates":[{"alg":"r U r' U2 M' U M","moveCount":7},{"alg":"U' R U' R2 D' r U r' D R","moveCount":10}]},
    "VHLS-vhls-3-1": {"alternates":[{"alg":"y L' U' L","moveCount":4}]},
    "VHLS-vhls-3-2": {"alternates":[{"alg":"y' S' R' U' R S","moveCount":6}]},
    "VHLS-vhls-3-3": {"alternates":[{"alg":"R U' R' F' r U' r' F2","moveCount":8},{"alg":"S U R U' R' S'","moveCount":6},{"alg":"M y' R' U' R U S'","moveCount":7}]},
    "VHLS-vhls-3-4": {"alternates":[{"alg":"U R2 D r' U' r D' R2","moveCount":8}]},
    "VHLS-vhls-3-5": {"alternates":[{"alg":"F' r U' r' F2 R U' R'","moveCount":8}]},
    "VHLS-vhls-3-6": {"alternates":[{"alg":"U2 R' D' r U' r' D R2 U' R'","moveCount":10}]},
    "VHLS-vhls-3-7": {"alternates":[{"alg":"U' R' F R U R U' R2 F' R","moveCount":10}]},
    "VHLS-vhls-3-8": {"alternates":[{"alg":"R' F R2 U' M' U2 r' U' F'","moveCount":9}]},
    "VHLS-vhls-4-1": {"alternates":[{"alg":"R U R'","moveCount":3}]},
    "VHLS-vhls-4-2": {"alternates":[{"alg":"R U R' U' F R U R' U' F'","moveCount":10},{"alg":"R U y R U R' U' F'","moveCount":8},{"alg":"S' R U R' S","moveCount":5}]},
    "VHLS-vhls-4-3": {"alternates":[{"alg":"R U R' F R U R' U' F'","moveCount":9},{"alg":"U M U' R U R' M'","moveCount":7},{"alg":"R U2 R' U' R' F R F'","moveCount":8}]},
    "VHLS-vhls-4-4": {"alternates":[{"alg":"R U R' U' r' U2 R U R' U r","moveCount":11},{"alg":"U F U R U' R2 F' R","moveCount":8},{"alg":"R U2 B U' B' R'","moveCount":6}]},
    "VHLS-vhls-4-5": {"alternates":[{"alg":"R U R' F U R U' R' F'","moveCount":9},{"alg":"U' F' U2 F U R U' R'","moveCount":8}]},
    "VHLS-vhls-4-6": {"alternates":[{"alg":"R U' R' F2 r U r' F","moveCount":8},{"alg":"R U' R2 F R F' R U2 R'","moveCount":9}]},
    "VHLS-vhls-4-7": {"alternates":[{"alg":"R U' R' U2 R' F R F'","moveCount":8},{"alg":"U2 r U' r' U' r U r'","moveCount":8}]},
    "VHLS-vhls-4-8": {"alternates":[{"alg":"R' D' r U' r' D R2 U R'","moveCount":9},{"alg":"R U' r' U r U2 r' U' r U2 R'","moveCount":11},{"alg":"R U' R2 F R F' U2 R' F R F'","moveCount":11}]},
  },
};
