/* ===========================================================
   Generate the 2x2 algorithm sets that ship in js/alglibrary-222.js
   and js/algs2.js.

       node tools/gen-222.mjs

   Nothing here is transcribed from a website or from memory. Every case
   is an equivalence class of real cube states, every algorithm is an
   exhaustive-search solution of that state, and every (case, algorithm)
   pair is re-checked at the end against js/cubenet.js — the same
   simulator the app itself verifies algorithms with. If the corner model
   below were wrong, that final check would fail rather than ship.

   The 2x2 group generated by <R, U, F> with the DBL corner pinned has
   3,674,160 states, which is small enough to hold a complete
   breadth-first distance table in memory, so every algorithm printed is
   optimal for its case in that move set.
   =========================================================== */

import { faceletsFor, stickerAt } from '../js/cubenet.js';

/* ---------------------------------------------------------
   Corner model.  URF UFL ULB UBR DFR DLF DBL DRB, DBL pinned.
   --------------------------------------------------------- */
const URF=0, UFL=1, ULB=2, UBR=3, DFR=4, DLF=5, DBL=6, DRB=7;
const NAMES = ['URF','UFL','ULB','UBR','DFR','DLF','DBL','DRB'];

const BASE = {
  U: { cp: [UBR, URF, UFL, ULB, DFR, DLF, DBL, DRB], co: [0,0,0,0,0,0,0,0] },
  R: { cp: [DFR, UFL, ULB, URF, DRB, DLF, DBL, UBR], co: [2,0,0,1,1,0,0,2] },
  F: { cp: [UFL, DLF, ULB, UBR, URF, DFR, DBL, DRB], co: [1,2,0,0,2,1,0,0] },
};

const SOLVED = { cp: [0,1,2,3,4,5,6,7], co: [0,0,0,0,0,0,0,0] };

/** a then b. */
function compose(a, b) {
  const cp = new Array(8), co = new Array(8);
  for (let i = 0; i < 8; i++) {
    cp[i] = a.cp[b.cp[i]];
    co[i] = (a.co[b.cp[i]] + b.co[i]) % 3;
  }
  return { cp, co };
}

/* The nine <R,U,F> moves, in the order the search tries them. */
const MOVES = [];
for (const face of ['R', 'U', 'F']) {
  let s = SOLVED;
  for (let i = 1; i <= 3; i++) {
    s = compose(s, BASE[face]);
    MOVES.push({ name: face + (i === 1 ? '' : i === 2 ? '2' : "'"), face, state: s });
  }
}

/* ---------------------------------------------------------
   Indexing.  7 moving corners: permutation (7!) x orientation (3^6).
   --------------------------------------------------------- */
const SLOT = [0, 1, 2, 3, 4, 5, -1, 6];       // cubie/position id -> 0..6, DBL dropped
const POS  = [0, 1, 2, 3, 4, 5, 7];           // 0..6 -> position id

const FACT = [1, 1, 2, 6, 24, 120, 720, 5040];
const N_PERM = 5040, N_ORI = 729, N_STATES = N_PERM * N_ORI;

function indexOf(s) {
  const p = POS.map(i => SLOT[s.cp[i]]);
  // Lehmer code
  let pi = 0;
  for (let i = 0; i < 7; i++) {
    let smaller = 0;
    for (let j = i + 1; j < 7; j++) if (p[j] < p[i]) smaller++;
    pi += smaller * FACT[6 - i];
  }
  let oi = 0;
  for (let i = 0; i < 6; i++) oi = oi * 3 + s.co[POS[i]];
  return pi * N_ORI + oi;
}

/* ---------------------------------------------------------
   Cross-check the model against the app's own simulator.
   --------------------------------------------------------- */

/* Which three facelets make up each corner position, and which of them is the
   U/D one — read straight out of cubenet's geometry rather than hand-written,
   so there is nothing here to get subtly backwards. */
const CORNER_FACELETS = (() => {
  const byCubie = new Map();
  for (const face of ['U', 'R', 'F', 'D', 'L', 'B']) {
    for (let r = 0; r < 2; r++) {
      for (let c = 0; c < 2; c++) {
        const { cubie } = stickerAt(face, r, c, 2);
        if (!byCubie.has(cubie)) byCubie.set(cubie, []);
        byCubie.get(cubie).push({ face, r, c });
      }
    }
  }
  /* Each corner's three facelets, ordered the way every cubie model orders
     them: the U/D one first, then the other two going clockwise as seen from
     outside the corner. "Clockwise" is not eyeballed — it is the sign of the
     determinant of the three outward normals, which is -1 for exactly the
     orderings a right-handed corner reads in. Orientation is then simply how
     far round this list the U/D-coloured sticker has ended up, and that is the
     definition the move tables above are written against. */
  const N = { U: [0,1,0], D: [0,-1,0], R: [1,0,0], L: [-1,0,0], F: [0,0,1], B: [0,0,-1] };
  const det = (a, b, c) =>
      a[0]*(b[1]*c[2] - b[2]*c[1])
    - a[1]*(b[0]*c[2] - b[2]*c[0])
    + a[2]*(b[0]*c[1] - b[1]*c[0]);

  const out = {};
  for (const [, fs] of byCubie) {
    const key = fs.map(f => f.face).sort().join('');
    const ud = fs.find(f => f.face === 'U' || f.face === 'D');
    const rest = fs.filter(f => f !== ud);
    const ordered = det(N[ud.face], N[rest[0].face], N[rest[1].face]) < 0
      ? [ud, rest[0], rest[1]]
      : [ud, rest[1], rest[0]];
    out[key] = ordered;
  }
  return out;
})();

const HOME_KEY = NAMES.map(n => n.split('').sort().join(''));

/** Read (cp, co) out of a cubenet facelet grid. */
function fromFacelets(f) {
  const cp = new Array(8), co = new Array(8);
  for (let p = 0; p < 8; p++) {
    const fs = CORNER_FACELETS[HOME_KEY[p]];
    const cols = fs.map(x => f[x.face][x.r][x.c]);
    const cubie = cols.slice().sort().join('');
    cp[p] = HOME_KEY.indexOf(cubie);
    /* Orientation measured the same way for every corner: how far round the
       U/D sticker sits from the U/D facelet of the slot it is in. The two
       tables only ever have to agree with each other, and the check below is
       what proves they do. */
    const udSlot = fs.findIndex(x => x.face === 'U' || x.face === 'D');
    const udSticker = cols.findIndex(c => c === 'U' || c === 'D');
    co[p] = ((udSticker - udSlot) % 3 + 3) % 3;
  }
  return { cp, co };
}

function modelOf(seq) {
  let s = SOLVED;
  for (const tok of seq) s = compose(s, MOVES.find(m => m.name === tok).state);
  return s;
}

function crossCheck(trials = 4000) {
  let mismatches = 0;
  for (let t = 0; t < trials; t++) {
    const n = 1 + Math.floor(Math.random() * 14);
    const seq = [];
    for (let i = 0; i < n; i++) seq.push(MOVES[Math.floor(Math.random() * 9)].name);
    const mine = modelOf(seq);
    const theirs = fromFacelets(faceletsFor(seq.join(' '), 2));
    if (indexOf(mine) !== indexOf(theirs)) mismatches++;
  }
  return mismatches;
}

/* ---------------------------------------------------------
   Full breadth-first distance table
   --------------------------------------------------------- */
function buildTable(goals) {
  const dist = new Uint8Array(N_STATES).fill(255);
  // states are kept as index -> we need the cubie form to expand, so keep a
  // frontier of {idx, state} rather than decoding an index back.
  let frontier = [];
  let seen = 0;
  for (const g of goals) {
    const i = indexOf(g.state);
    if (dist[i] !== 255) continue;
    dist[i] = 0;
    seen++;
    frontier.push({ idx: i, state: g.state });
  }
  let depth = 0;
  while (frontier.length) {
    const next = [];
    for (const { state } of frontier) {
      for (const m of MOVES) {
        const s2 = compose(state, m.state);
        const i2 = indexOf(s2);
        if (dist[i2] !== 255) continue;
        dist[i2] = depth + 1;
        seen++;
        next.push({ idx: i2, state: s2 });
      }
    }
    frontier = next;
    depth++;
  }
  return { dist, seen, depth: depth - 1 };
}

/* ---------------------------------------------------------
   Solutions
   --------------------------------------------------------- */

/** Every solution of `state` of length exactly `len`, capped. */
function solutionsOfLength(dist, state, len, cap = 400) {
  const out = [];
  const path = [];
  const walk = (s, left, lastFace) => {
    if (out.length >= cap) return;
    if (left === 0) { if (dist[indexOf(s)] === 0) out.push(path.join(' ')); return; }
    if (dist[indexOf(s)] > left) return;                 // cannot get there
    for (const m of MOVES) {
      if (m.face === lastFace) continue;                 // never two of a face in a row
      path.push(m.name);
      walk(compose(s, m.state), left - 1, m.face);
      path.pop();
    }
  };
  walk(state, len, '');
  return out;
}

/* Which solutions to print. Fewer moves first; among equals, the ones that
   stay in <R,U> longest, because those are the ones a 2x2 solver can actually
   execute at speed — an F turn mid-alg is a regrip. */
const score = (alg) => {
  const toks = alg.split(' ');
  return toks.filter(t => t[0] === 'F').length * 10
       + toks.filter(t => t.includes('2')).length * 2
       + toks.length;
};

/* Two solutions that agree on everything but their last move are the same
   algorithm, not an alternative to it — the final turn of a 2x2 algorithm
   often has a free choice of direction because nothing after it looks at that
   layer. Listing both would pad every case with four near-identical lines and
   hide the genuinely different approach further down. */
const stem = (alg) => alg.split(' ').slice(0, -1).join(' ');

function algsFor(dist, state, want = 4) {
  const d = dist[indexOf(state)];
  const out = [];
  const stems = new Set();
  for (let len = d; len <= d + 1 && out.length < want; len++) {
    const found = solutionsOfLength(dist, state, len).sort((a, b) => score(a) - score(b));
    for (const a of found) {
      if (out.length >= want) break;
      if (stems.has(stem(a))) continue;
      stems.add(stem(a));
      out.push(a);
    }
  }
  return out;
}

/* ---------------------------------------------------------
   Orientation-class names, taken from the app's own OCLL algorithms
   --------------------------------------------------------- */

/* The seven corner-orientation cases already have names in js/algs.js
   (OLL 21-27). Rather than re-deciding which twist pattern is called "T" and
   which is called "U" — a decision nobody can check by reading it — each
   name is attached to whatever pattern that case's own algorithm actually
   produces on a 3x3. */
const OCLL_ALGS = [
  ['H',        "R U2 R' U' R U R' U' R U' R'"],
  ['Pi',       "R U2 R2 U' R2 U' R2 U2 R"],
  ['U',        "R2 D' R U2 R' D R U2 R"],
  ['T',        "r U R' U' r' F R F'"],
  ['L',        "F' r U R' U' r' F R"],
  ['Antisune', "R U2 R' U' R U' R'"],
  ['Sune',     "R U R' U R U2 R'"],
];

/* Positions of the four U corners on a 3x3, in the same cyclic order the 2x2
   model uses (URF, UFL, ULB, UBR), as (face, row, col) triples whose first
   entry is the U facelet. */
const LL_CORNERS_3 = [
  [['U',2,2], ['R',0,0], ['F',0,2]],   // URF
  [['U',2,0], ['F',0,0], ['L',0,2]],   // UFL
  [['U',0,0], ['L',0,0], ['B',0,2]],   // ULB
  [['U',0,2], ['B',0,0], ['R',0,2]],   // UBR
];

function invert(alg) {
  return alg.trim().split(/\s+/).reverse()
    .map(t => t.endsWith('2') ? t : t.endsWith("'") ? t.slice(0, -1) : t + "'")
    .join(' ');
}

/** Orientation vector of the four U corners after running `alg` backwards. */
function oriVector3(alg) {
  const f = faceletsFor(invert(alg), 3);
  return LL_CORNERS_3.map(([a, b, c]) => {
    const cols = [f[a[0]][a[1]][a[2]], f[b[0]][b[1]][b[2]], f[c[0]][c[1]][c[2]]];
    const at = cols.findIndex(x => x === 'U' || x === 'D');
    return at;                       // 0 = already facing up
  });
}

const rotations = (v) => [0,1,2,3].map(k => v.map((_, i) => v[(i + k) % 4]));
const canonOri = (v) => rotations(v).map(r => r.join('')).sort()[0];

const ORI_NAME = new Map();
for (const [name, alg] of OCLL_ALGS) ORI_NAME.set(canonOri(oriVector3(alg)), name);
ORI_NAME.set('0000', 'Oriented');

const oriOf = (s) => canonOri([URF, UFL, ULB, UBR].map(p => s.co[p]));


/* ---------------------------------------------------------
   Cases
   ---------------------------------------------------------

   A case is the family of states one algorithm covers. You may turn the top
   layer once before the algorithm and once after it, both free, so the states
   `pre · s · post` for the four U turns at each end are all the same case —
   that is the orbit computed below.

   This is why the CLL set here has 40 cases and not the 42 printed on most
   sheets. Six of the seven corner-orientation families give six cases each;
   the H family's twist pattern is unchanged by a half turn of U, so two of
   its pictures are two other pictures turned round and take the same
   algorithm. 6x6 + 4 = 40. Nothing is missing — the same 624 cube states are
   covered either way, and the count is a consequence of the orbit, not a
   choice.
   --------------------------------------------------------- */
const U1 = BASE.U;
const U_POW = [SOLVED, U1, compose(U1, U1), compose(compose(U1, U1), U1)];

function orbit(s) {
  const seen = new Map();
  for (const pre of U_POW) {
    for (const post of U_POW) {
      const t = compose(compose(pre, s), post);
      const i = indexOf(t);
      if (!seen.has(i)) seen.set(i, t);
    }
  }
  return [...seen.entries()].map(([idx, state]) => ({ idx, state }));
}
const orbitKey = (s) => Math.min(...orbit(s).map(o => o.idx));

function permutations(arr) {
  if (arr.length <= 1) return [arr];
  const out = [];
  for (let i = 0; i < arr.length; i++) {
    const rest = arr.slice(0, i).concat(arr.slice(i + 1));
    for (const p of permutations(rest)) out.push([arr[i], ...p]);
  }
  return out;
}

const UP = [URF, UFL, ULB, UBR];

/** Every state whose four D corners sit as `bottom` says, oriented. */
function statesWithBottom(bottom) {
  const out = [];
  for (const p of permutations(UP)) {
    for (let o = 0; o < 81; o++) {
      const ori = [o % 3, (o / 3 | 0) % 3, (o / 9 | 0) % 3, (o / 27 | 0) % 3];
      if ((ori[0] + ori[1] + ori[2] + ori[3]) % 3 !== 0) continue;
      const cp = [0,1,2,3,4,5,6,7], co = [0,0,0,0,0,0,0,0];
      for (let i = 0; i < 4; i++) { cp[UP[i]] = p[i]; co[UP[i]] = ori[i]; }
      for (const [pos, cub] of Object.entries(bottom)) cp[+pos] = cub;
      out.push({ cp, co });
    }
  }
  return out;
}

/** How the four top corners are permuted, said the way you would say it aloud. */
function topPerm(s) {
  for (let k = 0; k < 4; k++) {
    const wrong = UP.filter((p, i) => s.cp[p] !== UP[(i + k) % 4]);
    if (!wrong.length) return 'solved';
    if (wrong.length === 2) {
      const idx = UP.map((p, i) => [i, s.cp[p] !== UP[(i + k) % 4]]).filter(x => x[1]).map(x => x[0]);
      return (idx[1] - idx[0]) === 2 ? 'diagonal swap' : 'adjacent swap';
    }
  }
  return 'cycle';
}

/* ---------------------------------------------------------
   Build
   --------------------------------------------------------- */
console.log('cross-checking the corner model against js/cubenet.js …');
const bad = crossCheck();
if (bad) { console.error(`  ${bad} mismatches — the model is wrong, refusing to generate.`); process.exit(1); }
console.log('  4000/4000 random sequences agree.');

console.log('building the distance tables …');
const solve = buildTable([{ state: SOLVED }]);
console.log(`  solved:   ${solve.seen.toLocaleString()} states, depth ${solve.depth}`);
if (solve.seen !== N_STATES) { console.error('  wrong state count — aborting.'); process.exit(1); }

/* A second table for the orientation-only set: there "done" is one colour on
   top and one colour underneath, so the search has many goals rather than one.
   Both halves of that matter. Every corner facing the right way is not enough
   on its own — a top corner dropped into a bottom slot can be perfectly
   oriented and still put a white sticker in the middle of the yellow face, and
   an algorithm found against that weaker goal would not be a 2x2 OLL
   algorithm at all. So the goal set is: every corner oriented, and no corner
   in the other layer. */
const orientedGoals = [];
for (const top of permutations([URF, UFL, ULB, UBR])) {
  for (const bottom of permutations([DFR, DLF, DRB])) {
    const cp = [0,1,2,3,4,5,6,7];
    [URF, UFL, ULB, UBR].forEach((pos, i) => { cp[pos] = top[i]; });
    [DFR, DLF, DRB].forEach((pos, i) => { cp[pos] = bottom[i]; });
    orientedGoals.push({ state: { cp, co: [0,0,0,0,0,0,0,0] } });
  }
}
const orient = buildTable(orientedGoals);
console.log(`  oriented: ${orient.seen.toLocaleString()} states, depth ${orient.depth}`);

const D_SOLVED = {};
const D_ADJ    = { [DFR]: DLF, [DLF]: DFR };
const D_DIAG   = { [DLF]: DRB, [DRB]: DLF };

const unoriented = (s) => UP.some(p => s.co[p] !== 0);

function collect({ bottom, filter, table }) {
  const seen = new Set();
  const cases = [];
  for (const s of statesWithBottom(bottom)) {
    if (!filter(s)) continue;
    const key = orbitKey(s);
    if (seen.has(key)) continue;
    seen.add(key);
    const members = orbit(s);
    let best = null;
    for (const m of members) {
      const d = table.dist[m.idx];
      if (!best || d < best.d || (d === best.d && m.idx < best.idx)) best = { ...m, d };
    }
    cases.push({ state: best.state, depth: best.d, members: members.length });
  }
  return cases;
}

const ORI_ORDER = ['Sune', 'Antisune', 'T', 'U', 'L', 'Pi', 'H'];

function lastLayerSet(bottom) {
  const cases = collect({ bottom, filter: unoriented, table: solve });
  const byFamily = new Map();
  for (const c of cases) {
    const fam = ORI_NAME.get(oriOf(c.state)) || oriOf(c.state);
    if (!byFamily.has(fam)) byFamily.set(fam, []);
    byFamily.get(fam).push(c);
  }
  const rows = [];
  for (const fam of ORI_ORDER) {
    const list = (byFamily.get(fam) || []).sort((a, b) => a.depth - b.depth || indexOf(a.state) - indexOf(b.state));
    list.forEach((c, i) => {
      rows.push({
        family: fam,
        name: `${fam} ${i + 1}`,
        perm: topPerm(c.state),
        algs: algsFor(solve.dist, c.state, 4),
        depth: c.depth,
      });
    });
  }
  return rows;
}

const out = {};

out.CLL = lastLayerSet(D_SOLVED);
out.EG1 = lastLayerSet(D_ADJ);
out.EG2 = lastLayerSet(D_DIAG);

/* Orientation only: the bottom layer is already facing the right way, the top
   is not, and where the corners end up is the next step's problem. */
out.OLL = (() => {
  const cases = collect({ bottom: D_SOLVED, filter: unoriented, table: orient });
  // Orientation ignores permutation, so squash the orbit list down to one case
  // per twist pattern.
  const byOri = new Map();
  for (const c of cases) {
    const k = oriOf(c.state);
    const prev = byOri.get(k);
    if (!prev || c.depth < prev.depth) byOri.set(k, c);
  }
  return [...byOri.entries()]
    .map(([k, c]) => {
      const first = algsFor(orient.dist, c.state, 1)[0];
      /* The app defines a case as "the state this algorithm's inverse builds",
         because that is how it makes a trainer scramble. For a set whose
         algorithms finish the puzzle those are the same state; for an
         orientation set they are not — the algorithm leaves the corners in a
         different order than it found them, so its inverse is a *different*
         state with the same twist pattern. The alternates therefore have to be
         solutions of that state, not of the one the search started from, or
         every one of them but the first would be an algorithm for the case
         next door. */
      const pattern = modelOf(invert(first).split(' '));
      /* `first` came from a different search than the rest, so the stem rule
         in algsFor never saw it: `first` plus a closing U is the same alg. */
      const algs = [first, ...algsFor(orient.dist, pattern, 6)
        .filter(a => a !== first && stem(a) !== first && stem(a) !== stem(first))].slice(0, 4);
      return {
        family: ORI_NAME.get(k) || k,
        name: ORI_NAME.get(k) || k,
        perm: topPerm(c.state),
        algs,
        depth: c.depth,
      };
    })
    .sort((a, b) => ORI_ORDER.indexOf(a.family) - ORI_ORDER.indexOf(b.family));
})();

/* Both layers oriented, neither necessarily permuted. */
out.PBL = (() => {
  const rows = [];
  const bottoms = [['solved', D_SOLVED], ['adjacent swap', D_ADJ], ['diagonal swap', D_DIAG]];
  for (const [bname, bottom] of bottoms) {
    const cases = collect({ bottom, filter: (s) => !unoriented(s), table: solve });
    for (const c of cases) {
      if (c.depth === 0) continue;                       // already solved
      rows.push({
        family: `bottom ${bname}`,
        name: `${bname} / ${topPerm(c.state)}`,
        perm: topPerm(c.state),
        algs: algsFor(solve.dist, c.state, 4),
        depth: c.depth,
      });
    }
  }
  return rows;
})();

/* The last word is the app's own simulator, not this file's cube model: every
   algorithm is run against the state its case's first algorithm builds, and
   nothing is written if one of them comes up short. */
const DONE_CHECK = {
  OLL:  (f) => new Set(f.U.flat()).size === 1 && new Set(f.D.flat()).size === 1,
  PBL:  solvedFacelets, CLL: solvedFacelets, EG1: solvedFacelets, EG2: solvedFacelets,
};
function solvedFacelets(f) {
  return ['U','R','F','D','L','B'].every(F => f[F].flat().every(s => s === F));
}
const AUF_TOKENS = ['', 'U', 'U2', "U'"];
let failures = 0;
for (const [key, rows] of Object.entries(out)) {
  const done = DONE_CHECK[key];
  for (const r of rows) {
    const pattern = invert(r.algs[0]);
    for (const alg of r.algs) {
      const ok = AUF_TOKENS.some(pre => AUF_TOKENS.some(post =>
        done(faceletsFor([pattern, pre, alg, post].filter(Boolean).join(' '), 2))));
      if (!ok) { console.error(`  FAIL ${key} ${r.name}: ${alg}`); failures++; }
    }
  }
}
if (failures) { console.error(`${failures} algorithms failed the simulator check — nothing written.`); process.exit(1); }
console.log('every generated algorithm re-checked against js/cubenet.js: clean');

for (const [k, v] of Object.entries(out)) {
  console.log(`${k}: ${v.length} cases, ${v.reduce((n, r) => n + r.algs.length, 0)} algorithms, ` +
              `longest ${Math.max(...v.map(r => r.depth))} moves`);
}

import { writeFileSync } from 'node:fs';

/* ---------------------------------------------------------
   Emit the two files the app reads
   --------------------------------------------------------- */
const slug = (s) => s.replace(/[^A-Za-z0-9]+/g, '-').replace(/^-|-$/g, '');

const SET_META = {
  OLL: {
    setId: '222-OLL', prefix: '222OLL',
    label: 'OLL', title: 'Orient every corner — the first step of Ortega',
    describe: (r) => `${r.family} twist — orient all four corners, wherever they end up`,
    caseName: (r) => r.name,
    group: () => 'Orientation',
  },
  PBL: {
    setId: '222-PBL', prefix: '222PBL',
    label: 'PBL', title: 'Permute both layers at once — the last step of Ortega',
    describe: (r) => `bottom ${r.family.replace('bottom ', '')} · top ${r.perm}`,
    caseName: (r) => r.name,
    group: (r) => r.family,
  },
  CLL: {
    setId: '222-CLL', prefix: 'CLL',
    label: 'CLL', title: 'Bottom layer done — finish the top in one algorithm',
    describe: (r) => `${r.family} twist · top corners ${r.perm}`,
    caseName: (r) => r.name,
    group: (r) => r.family,
  },
  EG1: {
    setId: '222-EG1', prefix: 'EG1',
    label: 'EG-1', title: 'Bottom layer oriented with one adjacent swap — finish in one algorithm',
    describe: (r) => `${r.family} twist · top corners ${r.perm}`,
    caseName: (r) => r.name,
    group: (r) => r.family,
  },
  EG2: {
    setId: '222-EG2', prefix: 'EG2',
    label: 'EG-2', title: 'Bottom layer oriented with a diagonal swap — finish in one algorithm',
    describe: (r) => `${r.family} twist · top corners ${r.perm}`,
    caseName: (r) => r.name,
    group: (r) => r.family,
  },
};

const ORDER = ['OLL', 'PBL', 'CLL', 'EG1', 'EG2'];

const caseId = (meta, r, i) => `${meta.prefix}-${slug(r.name)}` + (meta.prefix === '222PBL' ? `-${i + 1}` : '');

let casesJs = `/* ===========================================================
   Tagda Timer — 2x2 algorithm sets, for the trainer and the library.

   GENERATED by tools/gen-222.mjs. Do not hand-edit.

   Not scraped and not remembered: every case below is an equivalence
   class of real cube states, and every algorithm is a shortest solution
   of that state found by exhaustive search over the whole 3,674,160-state
   group. The generator cross-checks its cube model against js/cubenet.js
   before it will emit anything, and tools/verify-alglibrary.html re-runs
   every algorithm here against its own case in the browser.

   A case is the family of states one algorithm covers, since a U turn
   before the algorithm and a U turn after it are both free. That is why
   CLL is 40 cases here rather than the 42 most sheets print: in the H
   family a half turn of U leaves the twist pattern alone, so two of its
   six pictures are two of the others turned round. The same 624 states
   are covered either way.
   =========================================================== */

`;

let libJs = `/* ===========================================================
   Tagda Timer — 2x2 algorithm library: alternates per case.

   GENERATED by tools/gen-222.mjs. Do not hand-edit.

   Lazy-loaded by js/alglibrary.js, never on the timer's boot path.

   Every alternate is a shortest — or one-move-from-shortest —
   solution of its case in <R, U, F>, listed with the R/U-only ones
   first because those are the ones that execute without a regrip.
   =========================================================== */

import { OLL_222, PBL_222, CLL_222, EG1_222, EG2_222 } from './algs2.js';

`;

const EXPORT_NAME = { OLL: 'OLL_222', PBL: 'PBL_222', CLL: 'CLL_222', EG1: 'EG1_222', EG2: 'EG2_222' };
const q = (s) => JSON.stringify(s);

for (const key of ORDER) {
  const meta = SET_META[key];
  const rows = out[key];
  casesJs += `export const ${EXPORT_NAME[key]} = [\n`;
  let lib = `const ${key}_LIBRARY = {\n`;
  rows.forEach((r, i) => {
    const id = caseId(meta, r, i);
    casesJs += `  { id: ${q(id)}, name: ${q(meta.caseName(r))}, group: ${q(meta.group(r))}, ` +
               `label: ${q(meta.describe(r))}, alg: ${q(r.algs[0])} },\n`;
    lib += `  ${q(id)}: { alternates: [\n` +
      r.algs.map(a => `    { alg: ${q(a)}, moveCount: ${a.split(' ').length} },\n`).join('') +
      `  ] },\n`;
  });
  casesJs += `];\n\n`;
  lib += `};\n\n`;
  libJs += lib;
}

libJs += `export const SETS = {\n`;
for (const key of ORDER) {
  const meta = SET_META[key];
  const grouped = new Set(out[key].map(r => meta.group(r))).size > 1;
  libJs += `  ${q(meta.setId)}: {
    id: ${q(meta.setId)},
    event: '222',
    n: 2,
    label: ${q(meta.label)},
    title: ${q(meta.title)},
    cases: ${EXPORT_NAME[key]},
    library: ${key}_LIBRARY,
    done: ${key === 'OLL' ? q('oriented2') : q('solved')},
${key === 'OLL' ? "    picture: 'orientation',\n" : ''}
    trainerMode: ${q('222' + key.toLowerCase())},
    source: 'generated',
${grouped ? `    groups: ${JSON.stringify([...new Set(out[key].map(r => meta.group(r)))])},
    groupOf: (c) => c.group,
    defaultGroup: null,\n` : ''}    caseLabel: (c) => c.name,
    describe: (c) => c.label,
  },\n`;
}
libJs += `};\n`;

writeFileSync(new URL('../js/algs2.js', import.meta.url), casesJs);
writeFileSync(new URL('../js/alglibrary-222.js', import.meta.url), libJs);
console.log('wrote js/algs2.js and js/alglibrary-222.js');
